// scripts/build_topics_3_to_5.js
// Verbs, Adverbs, Adjectives (Topics 3, 4, 5)
const { q } = require('./q_helper');

function getVerbs() {
  const items = [];
  // A1: 15 items
  items.push(
    q('vrb_a1_1', 'A1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Choose the correct third-person singular present form: "Tom ______ to school every day."',
      ['walk', 'walks', 'walking', 'is walk'], 1,
      'He/She/It in the Present Simple takes -s: "Tom walks".', 'British Council A1'),
    q('vrb_a1_2', 'A1', 'open_bracket', 'Open Bracket (Past Simple)', 'Producing',
      'Change the verb in brackets into Past Simple: "Yesterday, she (go) ______ to the library."',
      ['went', 'goed', 'gone', 'going'], 0,
      '"Go" is an irregular verb whose past tense is "went".', 'test-english A1'),
    q('vrb_a1_3', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "They doesn\'t like cold winter weather."',
      ['Correct', 'Incorrect - "They" requires auxiliary "don\'t"'], 1,
      'Subject pronoun "They" takes "do not / don\'t", not "doesn\'t".', 'Cambridge A1'),
    q('vrb_a1_4', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which verb is an IRREGULAR past tense verb?',
      ['Played', 'Watched', 'Bought', 'Cooked'], 2,
      '"Bought" is the irregular past of "buy" (played, watched, cooked are regular -ed).', 'Wordwall A1'),
    q('vrb_a1_5', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Look! The children ______ football in the school playground.',
      ['play', 'are playing', 'plays', 'played'], 1,
      'Action happening right now signaled by "Look!" takes Present Continuous: "are playing".', 'VOA English A1'),
    q('vrb_a1_6', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [she / English / speaks / very / well]',
      ['She speaks English very well.', 'She very well speaks English.', 'Very well she English speaks.', 'English speaks she very well.'], 0,
      'Subject (She) + Verb (speaks) + Object (English) + Adverbial (very well).', 'Bamboozle A1'),
    q('vrb_a1_7', 'A1', 'checking_error', 'Checking Error', 'Explaining',
      'Find the mistake: "She [A: can] [B: plays] the piano [C: very] [D: skillfully]."',
      ['A: can', 'B: plays', 'C: very', 'D: skillfully'], 1,
      'Modal auxiliaries like "can" are followed by the bare infinitive: "can play" (not plays).', 'Oxford A1'),
    q('vrb_a1_8', 'A1', 'matching', 'Matching', 'Memory',
      'Match the base verb "eat" with its past participle form:',
      ['ate', 'eaten', 'eating', 'eats'], 1,
      'Base "eat" -> Past "ate" -> Past Participle "eaten".', 'Elementary Verb Forms'),
    q('vrb_a1_9', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "I am having two brothers and one sister."',
      ['Correct', 'Incorrect - "have" meaning possess is a stative verb in present simple'], 1,
      '"Have" denoting possession is stative and cannot take progressive aspect: "I have two brothers".', 'British Council A1'),
    q('vrb_a1_10', 'A1', 'open_bracket', 'Open Bracket (Auxiliary)', 'Producing',
      'Complete the question: "(Do / Does) ______ your parents live in Siem Reap?"',
      ['Do', 'Does', 'Are', 'Is'], 0,
      '"Parents" is plural, so use the auxiliary "Do": "Do your parents live...".', 'test-english A1'),
    q('vrb_a1_11', 'A1', 'cloze', 'Cloze Test', 'Understanding',
      'My grandfather ______ up at 5:30 AM every morning.',
      ['wakes', 'wake', 'is waking', 'woken'], 0,
      'Daily routine requires Present Simple third-person singular: "wakes".', 'Cambridge A1'),
    q('vrb_a1_12', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which verb is a MODAL auxiliary verb?',
      ['Can', 'Jump', 'Sing', 'Read'], 0,
      '"Can" is a modal auxiliary verb expressing ability.', 'Wordwall A1'),
    q('vrb_a1_13', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'They ______ to the cinema last night because they were too tired.',
      ['didn\'t go', 'didn\'t went', 'don\'t go', 'weren\'t go'], 0,
      'Negative Past Simple uses "didn\'t + bare infinitive": "didn\'t go".', 'VOA English A1'),
    q('vrb_a1_14', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [listening / to / music / is / he / his / bedroom / in]',
      ['He is listening to music in his bedroom.', 'He is in his bedroom listening to music.', 'In his bedroom is he listening to music.', 'Listening to music is he in his bedroom.'], 0,
      'Subject (He) + Present Continuous (is listening) + Prepositional phrase (to music) + Place (in his bedroom).', 'Syntax A1'),
    q('vrb_a1_15', 'A1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the error: "Did you [A: saw] [B: the new] movie [C: at the] [D: cinema]?"',
      ['A: saw', 'B: the new', 'C: at the', 'D: cinema'], 0,
      'Auxiliary "Did" takes the bare infinitive: "Did you SEE...", not "saw".', 'Elementary Traps')
  );

  // A2: 15 items
  items.push(
    q('vrb_a2_1', 'A2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Select the modal verb of polite permission: "______ I borrow your pen for a moment?"',
      ['May', 'Must', 'Should', 'Will'], 0,
      '"May I...?" is standard formal polite permission in English.', 'British Council A2'),
    q('vrb_a2_2', 'A2', 'open_bracket', 'Open Bracket (Infinitive/Gerund)', 'Producing',
      'Use the correct verb pattern: "She decided (study) ______ abroad next semester."',
      ['to study', 'studying', 'study', 'studied'], 0,
      'The verb "decide" takes a to-infinitive: "decided to study".', 'test-english A2'),
    q('vrb_a2_3', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "I look forward to meet you next week."',
      ['Correct', 'Incorrect - "look forward to" takes a gerund (-ing)'], 1,
      '"Look forward to" has a prepositional "to", requiring a gerund: "look forward to meeting you".', 'Cambridge A2'),
    q('vrb_a2_4', 'A2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "He [A: suggested] [B: to go] to the [C: beach] for the [D: weekend]."',
      ['A: suggested', 'B: to go', 'C: beach', 'D: weekend'], 1,
      '"Suggest" is followed by a gerund or that-clause, never a to-infinitive: "suggested going".', 'Oxford A2'),
    q('vrb_a2_5', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'You ______ smoke inside the hospital; it is strictly prohibited by law.',
      ['must not', 'don\'t have to', 'might not', 'needn\'t'], 0,
      '"Must not" expresses strict prohibition by law or regulation.', 'Modals A2'),
    q('vrb_a2_6', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which verb takes a GERUND (-ing) after it?',
      ['Enjoy', 'Want', 'Decide', 'Hope'], 0,
      '"Enjoy" is followed by a gerund ("enjoy reading"), whereas want, decide, and hope take to-infinitives.', 'Verb Patterns A2'),
    q('vrb_a2_7', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [she / how / knows / to / a / drive / car]',
      ['She knows how to drive a car.', 'She knows to drive how a car.', 'How to drive a car knows she.', 'A car knows she how to drive.'], 0,
      'Subject (She) + Verb (knows) + Interrogative infinitive (how to drive a car).', 'Wordwall A2'),
    q('vrb_a2_8', 'A2', 'cloze', 'Cloze Test', 'Understanding',
      'When I was young, I ______ swim across the river easily.',
      ['could', 'can', 'might', 'must'], 0,
      'Past general ability is expressed by "could".', 'Modals A2'),
    q('vrb_a2_9', 'A2', 'matching', 'Matching', 'Understanding',
      'Match the verb with its pattern: "refuse" ->',
      ['+ to-infinitive', '+ gerund (-ing)', '+ bare infinitive', '+ past participle'], 0,
      '"Refuse" takes a to-infinitive: "refused to answer".', 'Cambridge A2'),
    q('vrb_a2_10', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "You don\'t have to come if you are busy tomorrow."',
      ['Correct - expresses absence of obligation', 'Incorrect - should be "must not"'], 0,
      '"Don\'t have to" correctly conveys that an action is optional (absence of obligation).', 'test-english A2'),
    q('vrb_a2_11', 'A2', 'open_bracket', 'Open Bracket (Phrasal Verb)', 'Producing',
      'Complete the phrasal verb meaning extinguish: "Please (put) ______ out your cigarette."',
      ['put', 'take', 'give', 'turn'], 0,
      '"Put out" means extinguish a fire or cigarette.', 'Phrasal Verbs A2'),
    q('vrb_a2_12', 'A2', 'checking_error', 'Checking Error', 'Explaining',
      'Find the mistake: "She [A: enjoys] [B: to read] [C: mystery] [D: novels]."',
      ['A: enjoys', 'B: to read', 'C: mystery', 'D: novels'], 1,
      '"Enjoy" requires a gerund: "enjoys READING", not "to read".', 'Verb Patterns A2'),
    q('vrb_a2_13', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which verb is STATIVE (does not normally take continuous aspect)?',
      ['Believe', 'Run', 'Sing', 'Eat'], 0,
      '"Believe" is a stative verb of mental state (e.g., "I believe you", never *"I am believing you").', 'Stative Verbs A2'),
    q('vrb_a2_14', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'If you have a fever, you ______ see a doctor.',
      ['should', 'could', 'may', 'would'], 0,
      '"Should" gives advice and recommendation.', 'VOA English A2'),
    q('vrb_a2_15', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [promised / she / help / to / with / homework / my / me]',
      ['She promised to help me with my homework.', 'She promised to me help with my homework.', 'With my homework she promised to help me.', 'To help me with my homework she promised.'], 0,
      'Subject (She) + Verb (promised) + To-Infinitive (to help me) + Prepositional phrase (with my homework).', 'Wordwall A2')
  );

  // B1: 15 items
  items.push(
    q('vrb_b1_1', 'B1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Distinguish transitive vs intransitive: "The company plans to ______ prices next quarter."',
      ['raise', 'rise', 'arise', 'raising'], 0,
      '"Raise" is transitive and requires a direct object ("prices"). "Rise" is intransitive.', 'Cambridge B1'),
    q('vrb_b1_2', 'B1', 'open_bracket', 'Open Bracket (Meaning Shift)', 'Producing',
      'Notice the meaning: "He stopped (smoke) ______ three years ago because of health concerns."',
      ['smoking', 'to smoke', 'smoke', 'smoked'], 0,
      '"Stop + gerund" means to quit a habit or action permanently.', 'test-english B1'),
    q('vrb_b1_3', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "On the way to work, I stopped to buy a newspaper."',
      ['Correct - "stop + to-infinitive" indicates pausing in order to do something', 'Incorrect - "stop" must always take -ing'], 0,
      '"Stop + to-infinitive" expresses pausing one action in order to perform another.', 'Oxford B1'),
    q('vrb_b1_4', 'B1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "The sun [A: raises] [B: in the east] [C: and sets] [D: in the west]."',
      ['A: raises', 'B: in the east', 'C: and sets', 'D: in the west'], 0,
      'The sun rises (intransitive verb "rise"), not "raises".', 'B1 Confusing Pairs'),
    q('vrb_b1_5', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The teacher made the students ______ their essays before leaving the room.',
      ['rewrite', 'to rewrite', 'rewriting', 'rewrote'], 0,
      'Causative "make" takes bare infinitive: "made the students rewrite".', 'Causatives B1'),
    q('vrb_b1_6', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which verb takes an object followed by a BARE infinitive (without to)?',
      ['Let', 'Allow', 'Permit', 'Force'], 0,
      '"Let" takes a bare infinitive ("let him go"). Allow, permit, and force take a to-infinitive ("allow him to go").', 'Causative Patterns B1'),
    q('vrb_b1_7', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Assemble: [advised / he / smoking / me / to / quit]',
      ['He advised me to quit smoking.', 'He advised to quit smoking me.', 'Me he advised to quit smoking.', 'To quit smoking he advised me.'], 0,
      'Subject (He) + Verb (advised) + Object (me) + Infinitive (to quit smoking).', 'Syntax B1'),
    q('vrb_b1_8', 'B1', 'cloze', 'Cloze Test', 'Understanding',
      'I remember ______ the front door before leaving, but now it is unlocked!',
      ['locking', 'to lock', 'lock', 'locked'], 0,
      '"Remember + gerund" recalls a past action completed earlier.', 'B1 Verb Complementation'),
    q('vrb_b1_9', 'B1', 'matching', 'Matching', 'Understanding',
      'Match the modal with its meaning: "You must have left your wallet at home."',
      ['Strong logical deduction in the past', 'Past obligation', 'Polite request', 'Future certainty'], 0,
      '"Must have + past participle" expresses high confidence/logical deduction in the past.', 'Modals of Deduction B1'),
    q('vrb_b1_10', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "She avoided to answer the journalist\'s difficult question."',
      ['Correct', 'Incorrect - "avoid" requires a gerund (-ing)'], 1,
      '"Avoid" takes a gerund: "avoided answering".', 'test-english B1'),
    q('vrb_b1_11', 'B1', 'open_bracket', 'Open Bracket (Past Habit)', 'Producing',
      'Complete the discontinued habit: "My father (use / play) ______ the guitar when he was in college."',
      ['used to play', 'was used to play', 'is used to playing', 'use to play'], 0,
      '"Used to + bare infinitive" describes past habits that no longer happen.', 'Cambridge B1'),
    q('vrb_b1_12', 'B1', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the error: "He [A: had better] [B: to leave] now [C: or he] [D: will miss] his flight."',
      ['A: had better', 'B: to leave', 'C: or he', 'D: will miss'], 1,
      '"Had better" is followed by a bare infinitive without "to": "had better leave".', 'Modal Idioms B1'),
    q('vrb_b1_13', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which verb pairs with BOTH a gerund and infinitive with VIRTUALLY NO change in meaning?',
      ['Begin', 'Remember', 'Stop', 'Forget'], 0,
      '"Begin" can take either to-infinitive or gerund without meaningful distinction ("began to rain" / "began raining").', 'Verb Complementation B1'),
    q('vrb_b1_14', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The noise from the construction site kept me ______ all night.',
      ['awake', 'awaking', 'to awake', 'awoken'], 0,
      '"Keep someone awake" is the standard collocated resultative structure.', 'Resultatives B1'),
    q('vrb_b1_15', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [cannot / laughing / I / help / whenever / joke / tells / he / that]',
      ['I cannot help laughing whenever he tells that joke.', 'Whenever he tells that joke I cannot help laughing.', 'He tells that joke whenever I cannot help laughing.', 'Laughing I cannot help whenever he tells that joke.'], 0,
      'Idiom "cannot help + V-ing" (unable to prevent oneself from doing something).', 'Idioms B1')
  );

  // B2: 15 items
  items.push(
    q('vrb_b2_1', 'B2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Choose the causative structure with "get": "The manager got the contractor ______ the blueprints by Friday."',
      ['to revise', 'revise', 'revising', 'revised'], 0,
      'Causative "get + person" requires a to-infinitive: "got the contractor to revise". (Contrast with "have someone revise").', 'Cambridge B2 First'),
    q('vrb_b2_2', 'B2', 'open_bracket', 'Open Bracket (Modal Deduction)', 'Producing',
      'Express negative past deduction: "He (cannot / commit) ______ the crime because he was overseas at the time."',
      ['cannot have committed', 'could not commit', 'must not have committed', 'should not commit'], 0,
      '"Cannot have + past participle" conveys logical impossibility in the past.', 'test-english B2'),
    q('vrb_b2_3', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The committee demanded that the president resigns immediately."',
      ['Correct in informal British English, but in formal English the subjunctive "resign" is required', 'Ungrammatical in all contexts'], 0,
      'Formal mandative subjunctive requires the base form: "demanded that the president RESIGN".', 'Subjunctive B2'),
    q('vrb_b2_4', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "She [A: regrets] [B: informing] you that your application [C: has been] [D: unsuccessful]."',
      ['A: regrets', 'B: informing', 'C: has been', 'D: unsuccessful'], 1,
      'When formally delivering bad news, use "regret + to-infinitive": "regret TO INFORM you". "Regret informing" means feeling sorry about having done it in the past.', 'Oxford B2'),
    q('vrb_b2_5', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The witness claims ______ a dark sedan speeding away from the scene of the robbery.',
      ['to have seen', 'having seen', 'to see', 'saw'], 0,
      '"Claim + perfect infinitive" (to have seen) expresses an earlier completed action.', 'Advanced Infinitives B2'),
    q('vrb_b2_6', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which verb CANNOT be used in the passive voice because it is strictly INTRANSITIVE?',
      ['Arrive', 'Design', 'Destroy', 'Produce'], 0,
      '"Arrive" has no direct object and cannot be passivized (*"The station was arrived by him").', 'Transitivity B2'),
    q('vrb_b2_7', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [she / have / the / her / repaired / car / at / had / garage]',
      ['She had her car repaired at the garage.', 'She had repaired her car at the garage.', 'Her car she had repaired at the garage.', 'At the garage had she her car repaired.'], 0,
      'Causative passive: Subject (She) + had + Object (her car) + Past Participle (repaired) + Place (at the garage).', 'Causative B2'),
    q('vrb_b2_8', 'B2', 'cloze', 'Cloze Test', 'Understanding',
      'The board insisted that all financial statements ______ audited by an independent firm.',
      ['be', 'are', 'were', 'must be'], 0,
      'Mandative subjunctive with "insist" takes the base form: "be audited".', 'British Council B2'),
    q('vrb_b2_9', 'B2', 'matching', 'Matching', 'Understanding',
      'Match the structure: "I would rather you didn\'t smoke here." What does "didn\'t smoke" express?',
      ['Hypothetical present preference', 'Past completed action', 'Future obligation', 'Polite permission'], 0,
      '"Would rather + subject + past tense" expresses a polite present preference for another person\'s behavior.', 'B2 Hypothetical Structures'),
    q('vrb_b2_10', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "He was seen leave the building through the back exit."',
      ['Correct', 'Incorrect - in passive voice, verbs of perception require to-infinitive ("seen TO LEAVE")'], 1,
      'In the passive, verbs of perception take a to-infinitive: "He was seen TO LEAVE".', 'Perception Verbs B2'),
    q('vrb_b2_11', 'B2', 'open_bracket', 'Open Bracket', 'Producing',
      'Complete the past intention: "We (hope) ______ to visit the temple yesterday, but the road was flooded."',
      ['had hoped', 'have hoped', 'were hoping', 'would hope'], 0,
      'Past Perfect "had hoped" signifies an unfulfilled past intention.', 'Unfulfilled Past B2'),
    q('vrb_b2_12', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the error: "They [A: would live] in a small village [B: before] they [C: moved] to the [D: capital]."',
      ['A: would live', 'B: before', 'C: moved', 'D: capital'], 0,
      '"Would" cannot express past states (only repeated dynamic actions); use "used to live".', 'Past Habits B2'),
    q('vrb_b2_13', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which verb takes an OBJECT COMPLEMENT (SVOC)?',
      ['Elect (They elected him president)', 'Sleep (He slept)', 'Give (She gave him a gift)', 'Run (They ran)'], 0,
      '"Elect" takes a direct object + object complement ("elected him president").', 'Sentence Patterns B2'),
    q('vrb_b2_14', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The minister was ______ to have resigned after the financial scandal broke.',
      ['reported', 'reporting', 'report', 'reportable'], 0,
      'Personal reporting passive: "Subject + be reported + to-infinitive".', 'Reporting Passives B2'),
    q('vrb_b2_15', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [you / had / better / an / umbrella / take / case / in / it / rains]',
      ['You had better take an umbrella in case it rains.', 'In case it rains you had better take an umbrella.', 'Had you better take an umbrella in case it rains.', 'Take an umbrella you had better in case it rains.'], 0,
      'Subject (You) + Modal idiom (had better take) + Object (an umbrella) + Condition (in case it rains).', 'Syntax B2')
  );

  // C1 & C2: 20 items (10 C1 + 10 C2)
  items.push(
    q('vrb_c1_1', 'C1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Identify the catenative verb structure with correct complementation:',
      ['He claims to have avoided paying the luxury tax.', 'He claims having avoided to pay the luxury tax.', 'He claims to avoid pay the luxury tax.', 'He claims to have avoided to pay the luxury tax.'], 0,
      '"Claim" licenses to-infinitive, which in turn licenses gerund "paying" after "avoid".', 'Cambridge C1 Advanced'),
    q('vrb_c1_2', 'C1', 'open_bracket', 'Open Bracket (Subjunctive)', 'Producing',
      'Formal resolution: "Be it resolved that the charter (amend) ______ without delay."',
      ['be amended', 'is amended', 'should be amended', 'was amended'], 0,
      'Formal third-person imperative / mandative subjunctive: "be amended".', 'Subjunctive C1'),
    q('vrb_c1_3', 'C1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "The legislation proposes that every citizen [A: pays] taxes [B: in accordance] [C: with] [D: their] income."',
      ['A: pays - in high formal legislative style, subjunctive "pay" is expected!', 'B: in accordance', 'C: with', 'D: their'], 0,
      'Formal legislative mandates require the subjunctive base form: "proposes that every citizen PAY...".', 'Legislative Register C1'),
    q('vrb_c1_4', 'C1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "Were the proposal to be accepted, substantial funding would be allocated."',
      ['Correct - inverted second conditional expressing formal hypothesis', 'Incorrect - should be "Was the proposal"'], 0,
      'Inverted conditional replaces "If the proposal were to be accepted" with "Were the proposal to be accepted".', 'Inversion C1'),
    q('vrb_c1_5', 'C1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Assemble: [had / no / he / sooner / arrived / than / meeting / the / commenced]',
      ['No sooner had he arrived than the meeting commenced.', 'Had he arrived no sooner than the meeting commenced.', 'The meeting commenced no sooner than he had arrived.', 'No sooner the meeting commenced than had he arrived.'], 0,
      'Negative fronted inversion: "No sooner had he arrived than...".', 'Negative Inversion C1'),
    q('vrb_c1_6', 'C1', 'cloze', 'Cloze Test', 'Understanding',
      'The ambassador was ______ to have negotiated the clandestine ceasefire agreement.',
      ['purported', 'purporting', 'purport', 'purportedly'], 0,
      '"Be purported to + infinitive" is an advanced evidential reporting passive.', 'Advanced Academic C1'),
    q('vrb_c1_7', 'C1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which verb resists passivization due to symmetrical/middle semantic properties?',
      ['Resemble', 'Praise', 'Evaluate', 'Critique'], 0,
      '"Resemble" is a middle stative verb that cannot form a passive (*"His father is resembled by him").', 'Middle Verbs C1'),
    q('vrb_c1_8', 'C1', 'matching', 'Matching', 'Understanding',
      'Match the aspectual nuance: "I was wondering if you could assist me." What does past continuous convey here?',
      ['Pragmatic politeness / Tentativeness', 'Interrupted past action', 'Past habit', 'Unfulfilled intention'], 0,
      'Past continuous with mental verbs ("was wondering / was hoping") creates polite social distance.', 'Pragmatic Grammar C1'),
    q('vrb_c1_9', 'C1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'He resented ______ about his previous financial insolvency during the cross-examination.',
      ['being questioned', 'to be questioned', 'questioning', 'having questioned'], 0,
      '"Resent + passive gerund (-ing)": "resented being questioned".', 'Gerund Complementation C1'),
    q('vrb_c1_10', 'C1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "Had I known about the protocol breach, I would have intervened immediately."',
      ['Correct - inverted third conditional', 'Incorrect - conditional requires "if"'], 0,
      'Inversion of auxiliary "Had" is standard literary and formal third conditional syntax.', 'Inverted Conditionals C1'),

    // C2 (10 items)
    q('vrb_c2_1', 'C2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Identify the archaic optative subjunctive wishing formula:',
      ['Long live the King!', 'May the King lives long!', 'The King will live long!', 'Living long is the King!'], 0,
      '"Long live the King!" is an archaic formulaic optative subjunctive expressing a formal wish.', 'Formulaic Subjunctive C2'),
    q('vrb_c2_2', 'C2', 'open_bracket', 'Open Bracket (Subjunctive Clause)', 'Producing',
      'Formal legal mandate: "The magistrate ordered that the prisoner (remand) ______ in custody."',
      ['be remanded', 'is remanded', 'should be remanded', 'was remanded'], 0,
      'Formal mandative subjunctive: "be remanded".', 'Legal English C2'),
    q('vrb_c2_3', 'C2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "Come [A: what] [B: may], we [C: shall] remain steadfast in our [D: resolve]."',
      ['A: what', 'B: may', 'C: shall', 'D: resolve - No error! Sentence is an impeccable formulaic subjunctive!'], 3,
      '"Come what may" is a completely correct classical idiom with inverted subjunctive syntax.', 'C2 Formulaic Idioms'),
    q('vrb_c2_4', 'C2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Reconstruct: [suffice / it / to / say / that / negotiations / have / collapsed]',
      ['Suffice it to say that negotiations have collapsed.', 'To say it suffice that negotiations have collapsed.', 'That negotiations have collapsed suffice it to say.', 'Suffice to say it that negotiations have collapsed.'], 0,
      'Formulaic third-person subjunctive: "Suffice it to say that...".', 'C2 Rhetoric'),
    q('vrb_c2_5', 'C2', 'cloze', 'Cloze Test', 'Understanding',
      'He spoke softly, ______ he arouse the suspicions of the border guards.',
      ['lest', 'unless', 'inasmuch as', 'provided that'], 0,
      '"Lest" means "for fear that" and takes a bare subjunctive verb: "lest he arouse".', 'Archaic Subjunctive C2'),
    q('vrb_c2_6', 'C2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which verb exhibits DATIVE SHIFT with preposition "for" rather than "to"?',
      ['Buy (buy someone something / buy something for someone)', 'Give', 'Lend', 'Send'], 0,
      '"Buy" shifts with benefactive "for" ("buy for him"). Give, lend, and send shift with recipient "to".', 'Dative Alternation C2'),
    q('vrb_c2_7', 'C2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The committee recommended that the treaty ______ ratified without reservation.',
      ['be', 'is', 'was', 'should be'], 0,
      'Mandative subjunctive with "recommend" takes base form "be".', 'C2 Mandative'),
    q('vrb_c2_8', 'C2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The diplomat was to have met the foreign minister yesterday, but sudden illness prevented the summit."',
      ['Correct - "was to have + past participle" conveys an unfulfilled scheduled past destiny', 'Incorrect - double past auxiliary is ungrammatical'], 0,
      '"Was to have + past participle" is high-register syntax for an official past plan that failed to materialize.', 'Historical Destiny C2'),
    q('vrb_c2_9', 'C2', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the defect: "Try [A: as] he [B: might], he [C: could not] [D: unfasten the lock]."',
      ['A: as', 'B: might', 'C: could not', 'D: unfasten the lock - Flawless concessive inversion!'], 3,
      '"Try as he might" is an established inverted concessive formula meaning "although he tried hard".', 'C2 Inversion'),
    q('vrb_c2_10', 'C2', 'open_bracket', 'Open Bracket', 'Producing',
      'Complete the inverted hypothetical: "(Were / Had) ______ it not for your generous assistance, we would have foundered."',
      ['Were', 'Had', 'Was', 'If'], 0,
      '"Were it not for..." is standard inverted counterfactual syntax for present/general conditions.', 'C2 Counterfactuals')
  );

  return items;
}

module.exports = { getVerbs };
