// scripts/build_prep_conj_inter_art.js
// Prepositions, Conjunctions, Interjections, Articles (Topics 6, 7, 8, 9)
const { q } = require('./q_helper');

function getPrepositions() {
  const items = [];
  // A1 (15 items)
  items.push(
    q('prep_a1_1', 'A1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Choose the preposition of time for clock times: "The school bell rings ______ 7:00 AM."',
      ['at', 'in', 'on', 'to'], 0,
      'Exact clock times take "at": "at 7:00 AM".', 'British Council A1'),
    q('prep_a1_2', 'A1', 'open_bracket', 'Open Bracket (Days)', 'Producing',
      'Insert the preposition for days: "We do not have classes (in / on) ______ Sunday."',
      ['on', 'in', 'at', 'by'], 0,
      'Days of the week take "on": "on Sunday".', 'test-english A1'),
    q('prep_a1_3', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "My birthday is in 15th August."',
      ['Correct', 'Incorrect - specific dates take "on" ("on 15th August")'], 1,
      'Specific calendar dates take "on", while months alone take "in": "on 15th August" vs "in August".', 'Cambridge A1'),
    q('prep_a1_4', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which phrase takes the preposition "IN"?',
      ['in July', 'at Monday', 'on 5 o\'clock', 'at 2026'], 0,
      'Months take "in" ("in July"). Days take on; clock times take at; years take in.', 'Wordwall A1'),
    q('prep_a1_5', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The cat is sleeping ______ the kitchen table.',
      ['under', 'between', 'during', 'since'], 0,
      'Locative preposition indicating beneath: "under the table".', 'VOA English A1'),
    q('prep_a1_6', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [she / lives / Siem Reap / in]',
      ['She lives in Siem Reap.', 'She in Siem Reap lives.', 'Siem Reap in she lives.', 'Lives she in Siem Reap.'], 0,
      'Cities and countries take "in": "lives in Siem Reap".', 'Bamboozle A1'),
    q('prep_a1_7', 'A1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "We [A: usually] [B: go to] school [C: on] [D: the morning]."',
      ['A: usually', 'B: go to', 'C: on', 'D: the morning'], 2,
      'Parts of the day take "in": "IN the morning" (except "at night").', 'Oxford A1'),
    q('prep_a1_8', 'A1', 'matching', 'Matching', 'Memory',
      'Match the night expression: "______ night"',
      ['At night', 'In night', 'On night', 'To night'], 0,
      'The fixed expression is "at night".', 'Elementary Collocations'),
    q('prep_a1_9', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "The book is on the desk."',
      ['Correct - "on" indicates surface contact', 'Incorrect - say "in the desk"'], 0,
      '"On" correctly indicates resting on top of a surface.', 'test-english A1'),
    q('prep_a1_10', 'A1', 'open_bracket', 'Open Bracket (Years)', 'Producing',
      'Insert preposition for years: "Angkor Wat was built (in / at) ______ the 12th century."',
      ['in', 'at', 'on', 'by'], 0,
      'Centuries and years take "in": "in the 12th century".', 'British Council A1'),
    q('prep_a1_11', 'A1', 'cloze', 'Cloze Test', 'Understanding',
      'The children walked ______ the bridge to reach the other side.',
      ['across', 'between', 'underneath', 'into'], 0,
      '"Across" denotes movement from one side of a surface to the opposite side.', 'Cambridge A1'),
    q('prep_a1_12', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which word is a PREPOSITION OF MOVEMENT?',
      ['Into', 'Under', 'At', 'On'], 0,
      '"Into" indicates motion towards the inside of something.', 'Wordwall A1'),
    q('prep_a1_13', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Put the milk ______ the refrigerator, please.',
      ['into', 'onto', 'across', 'through'], 0,
      'Movement inside an enclosed space takes "into" or "in".', 'VOA English A1'),
    q('prep_a1_14', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [standing / is / door / the / at / he]',
      ['He is standing at the door.', 'He is at standing the door.', 'At the door standing is he.', 'The door is standing he at.'], 0,
      'Specific exact point takes "at": "standing at the door".', 'Syntax A1'),
    q('prep_a1_15', 'A1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the mistake: "They [A: arrived] [B: to] the airport [C: on] [D: time]."',
      ['A: arrived', 'B: to - "arrive" takes "at" or "in", never "to"!', 'C: on', 'D: time'], 1,
      'We say "arrive AT the airport" or "arrive IN a city", never *arrive to.', 'Arrive Prepositions A1')
  );

  // A2 (15 items)
  items.push(
    q('prep_a2_1', 'A2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Select the dependent preposition: "She is very interested ______ world literature."',
      ['in', 'about', 'on', 'with'], 0,
      'The adjective "interested" takes the dependent preposition "in": "interested in".', 'test-english A2'),
    q('prep_a2_2', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The young boy is afraid ______ spiders and snakes.',
      ['of', 'with', 'from', 'at'], 0,
      'Adjective collocation: "afraid of".', 'Cambridge A2'),
    q('prep_a2_3', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "It depends from the weather whether we go camping."',
      ['Correct', 'Incorrect - "depend" takes the preposition "on", not "from"'], 1,
      'Collocation: "depend on", never *depend from.', 'British Council A2'),
    q('prep_a2_4', 'A2', 'open_bracket', 'Open Bracket (Movement)', 'Producing',
      'Supply the preposition: "The train passed (through / across) ______ the long mountain tunnel."',
      ['through', 'across', 'over', 'into'], 0,
      '"Through" indicates movement in 3D space with limits around it (like a tunnel).', 'Oxford A2'),
    q('prep_a2_5', 'A2', 'checking_error', 'Checking Error', 'Explaining',
      'Find the mistake: "She [A: is good] [B: in] playing [C: the] [D: piano]."',
      ['A: is good', 'B: in - skills take "good AT"!', 'C: the', 'D: piano'], 1,
      'Abilities and skills take "good at": "good AT playing the piano".', 'Good at A2'),
    q('prep_a2_6', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which preposition correctly completes: "listening ______ music"?',
      ['to', 'at', 'on', 'with'], 0,
      'The verb "listen" requires "to": "listen to music".', 'Wordwall A2'),
    q('prep_a2_7', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [divided / the / them / money / was / between / two / the]',
      ['The money was divided between the two of them.', 'Between the two of them the money was divided.', 'The two of them was divided the money between.', 'Was the money divided between the two of them.'], 0,
      '"Between" is used for division among two entities: "between the two".', 'Between vs Among A2'),
    q('prep_a2_8', 'A2', 'cloze', 'Cloze Test', 'Understanding',
      'He jumped ______ the swimming pool to cool off.',
      ['into', 'onto', 'towards', 'through'], 0,
      'Motion from outside into water takes "into".', 'Movement A2'),
    q('prep_a2_9', 'A2', 'matching', 'Matching', 'Understanding',
      'Match the adjective: "proud" ->',
      ['proud of', 'proud in', 'proud with', 'proud for'], 0,
      'Dependent preposition: "proud of".', 'Cambridge A2'),
    q('prep_a2_10', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "The marathon runner walked across the finish line."',
      ['Correct - "across" indicates crossing a line or boundary', 'Incorrect'], 0,
      '"Across" is standard for traversing lines, roads, or rivers.', 'test-english A2'),
    q('prep_a2_11', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'I have been living in this apartment ______ three years.',
      ['for', 'since', 'during', 'from'], 0,
      '"For" is used with a duration/period of time ("for three years").', 'For vs Since A2'),
    q('prep_a2_12', 'A2', 'open_bracket', 'Open Bracket (Starting Point)', 'Producing',
      'Supply preposition: "She has worked as a teacher (for / since) ______ 2018."',
      ['since', 'for', 'during', 'until'], 0,
      '"Since" marks the specific starting point in the past: "since 2018".', 'British Council A2'),
    q('prep_a2_13', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which phrase takes "DURING" rather than "for"?',
      ['during the summer holiday', 'for three months', 'for two hours', 'for a week'], 0,
      '"During" is followed by a known named event or noun phrase; "for" takes time duration numbers.', 'During vs For A2'),
    q('prep_a2_14', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [waited / for / station / she / at / him / the]',
      ['She waited for him at the station.', 'She waited at the station for him.', 'For him she waited at the station.', 'At the station she for him waited.'], 0,
      'Subject (She) + Verb + Dependent Prep (waited for him) + Place (at the station).', 'Syntax A2'),
    q('prep_a2_15', 'A2', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the error: "He [A: apologized] [B: to] the teacher [C: with] his [D: late arrival]."',
      ['A: apologized', 'B: to', 'C: with - "apologize FOR something"!', 'D: late arrival'], 2,
      'The preposition for the cause of apology is "for": "apologized FOR his late arrival".', 'Collocations A2')
  );

  // B1 (15 items)
  items.push(
    q('prep_b1_1', 'B1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Distinguish "between" vs "among": "The scholarship funds were distributed equally ______ the four winning schools."',
      ['among', 'between', 'within', 'amid'], 0,
      '"Among" is used for distribution involving more than two group members.', 'Cambridge B1'),
    q('prep_b1_2', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'She finally succeeded ______ obtaining her university degree with top honors.',
      ['in', 'on', 'at', 'to'], 0,
      '"Succeed in + gerund": "succeeded in obtaining".', 'test-english B1'),
    q('prep_b1_3', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "Despite of the heavy traffic, we arrived on schedule."',
      ['Correct', 'Incorrect - "Despite" does NOT take "of" (say "Despite the traffic" or "In spite of")'], 1,
      '"Despite" takes a direct noun phrase without "of"; "In spite of" requires "of".', 'Oxford B1'),
    q('prep_b1_4', 'B1', 'open_bracket', 'Open Bracket (Complex Preposition)', 'Producing',
      'Complete the complex preposition: "We proceeded (in / on) ______ spite of the sudden thunderstorm."',
      ['in', 'on', 'at', 'with'], 0,
      'The fixed 3-word preposition is "in spite of".', 'British Council B1'),
    q('prep_b1_5', 'B1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "She [A: insisted] [B: to pay] [C: for] [D: our dinner]."',
      ['A: insisted', 'B: to pay - "insist on + gerund"!', 'C: for', 'D: our dinner'], 1,
      '"Insist on doing something": "insisted ON PAYING for dinner".', 'Dependent Prepositions B1'),
    q('prep_b1_6', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which verb takes the dependent preposition "FROM"?',
      ['Prevent (prevent someone from doing something)', 'Object', 'Rely', 'Accuse'], 0,
      '"Prevent from". Object takes to; rely takes on; accuse takes of.', 'Verb Patterns B1'),
    q('prep_b1_7', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Assemble: [behalf / spoke / of / on / all / staff / she / the]',
      ['She spoke on behalf of all the staff.', 'On behalf of all the staff spoke she.', 'She all the staff on behalf of spoke.', 'All the staff spoke she on behalf of.'], 0,
      'Complex prepositional idiom: "on behalf of all the staff".', 'Syntax B1'),
    q('prep_b1_8', 'B1', 'cloze', 'Cloze Test', 'Understanding',
      'The detective accused the suspect ______ embezzling state treasury funds.',
      ['of', 'for', 'with', 'about'], 0,
      'Collocation: "accuse someone OF a crime".', 'B1 Collocations'),
    q('prep_b1_9', 'B1', 'matching', 'Matching', 'Understanding',
      'Match the adjective: "capable" ->',
      ['capable of', 'capable with', 'capable to', 'capable for'], 0,
      '"Capable of + gerund": "capable of winning".', 'Cambridge B1'),
    q('prep_b1_10', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The meeting will take place at Monday afternoon."',
      ['Correct', 'Incorrect - specific days and parts of days take "on" ("on Monday afternoon")'], 1,
      'When a day name modifies a time of day, use "on": "ON Monday afternoon".', 'Time Prepositions B1'),
    q('prep_b1_11', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Due ______ unexpected engine trouble, the flight was delayed by four hours.',
      ['to', 'of', 'for', 'with'], 0,
      '"Due to + noun" expresses causation.', 'B1 Connectors'),
    q('prep_b1_12', 'B1', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the error: "He [A: is accused] [B: for] [C: stealing] the [D: jewelry]."',
      ['A: is accused', 'B: for - should be "OF stealing"!', 'C: stealing', 'D: jewelry'], 1,
      '"Accuse of", not "accuse for".', 'Dependent Prepositions B1'),
    q('prep_b1_13', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which prepositional phrase means "representing someone"?',
      ['On behalf of', 'In front of', 'In view of', 'By means of'], 0,
      '"On behalf of" means acting as a representative of someone.', 'Complex Prepositions B1'),
    q('prep_b1_14', 'B1', 'open_bracket', 'Open Bracket', 'Producing',
      'Supply dependent preposition: "They congratulated him (on / for) ______ winning the championship."',
      ['on', 'for', 'with', 'about'], 0,
      '"Congratulate someone ON an achievement".', 'Collocations B1'),
    q('prep_b1_15', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [she / proud / is / achievements / her / students\' / of]',
      ['She is proud of her students\' achievements.', 'She is her students\' achievements proud of.', 'Proud of her students\' achievements is she.', 'Her students\' achievements she is proud of.'], 0,
      'Subject (She) + Verb (is) + Adjective + Preposition (proud of) + Object.', 'Syntax B1')
  );

  // B2 (15 items)
  items.push(
    q('prep_b2_1', 'B2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Complete the formal legal phrase: "The contract was executed ______ accordance with statutory requirements."',
      ['in', 'on', 'at', 'with'], 0,
      '"In accordance with" is the standard formal legal phrase.', 'Cambridge B2 First'),
    q('prep_b2_2', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
      '______ regard to your inquiry of 12th May, we are pleased to confirm your reservation.',
      ['With', 'In', 'At', 'By'], 0,
      '"With regard to" (or "In regard to").', 'Formal Correspondence B2'),
    q('prep_b2_3', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The person whom I spoke with was very knowledgeable."',
      ['Correct in standard English, though formal registers prefer fronted "The person with whom I spoke"', 'Completely incorrect'], 0,
      'Preposition stranding is standard in modern English; preposition fronting ("with whom") is formal.', 'Preposition Stranding B2'),
    q('prep_b2_4', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "She [A: has been] [B: barred] [C: to enter] the [D: competition]."',
      ['A: has been', 'B: barred', 'C: to enter - "barred FROM entering"!', 'D: competition'], 2,
      '"Bar someone FROM doing something" (+ gerund).', 'Oxford B2'),
    q('prep_b2_5', 'B2', 'open_bracket', 'Open Bracket', 'Producing',
      'Provide preposition: "He is completely oblivious (to / of) ______ the risks involved in the venture."',
      ['to', 'of', 'with', 'about'], 0,
      '"Oblivious to" (or "of") denotes unawareness.', 'B2 Dependent Prepositions'),
    q('prep_b2_6', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which prepositional phrase means "taking something into account"?',
      ['In light of', 'In lieu of', 'At the mercy of', 'In quest of'], 0,
      '"In light of" means considering/taking into account. ("In lieu of" means instead of).', 'Complex Idioms B2'),
    q('prep_b2_7', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [accordance / acted / the / with / instructions / doctor\'s / in / he]',
      ['He acted in accordance with the doctor\'s instructions.', 'In accordance with the doctor\'s instructions he acted.', 'He in accordance with the doctor\'s instructions acted.', 'Acted he in accordance with the doctor\'s instructions.'], 0,
      'Subject (He) + Verb (acted) + Complex prepositional phrase (in accordance with...).', 'B2 Syntax'),
    q('prep_b2_8', 'B2', 'cloze', 'Cloze Test', 'Understanding',
      'The government policy proved detrimental ______ public healthcare services.',
      ['to', 'for', 'with', 'at'], 0,
      '"Detrimental to": causing harm or damage to.', 'Collocations B2'),
    q('prep_b2_9', 'B2', 'matching', 'Matching', 'Understanding',
      'Match the preposition: "exempt" ->',
      ['exempt from', 'exempt to', 'exempt with', 'exempt of'], 0,
      '"Exempt from" (e.g., "exempt from military service").', 'test-english B2'),
    q('prep_b2_10', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The executive resigned in protest against the proposed merger."',
      ['Correct - "in protest against" is the established fixed phrase', 'Incorrect'], 0,
      '"In protest against/at" is standard formal usage.', 'British Council B2'),
    q('prep_b2_11', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'He was acquitted ______ all charges of espionage after a six-month trial.',
      ['of', 'from', 'with', 'for'], 0,
      '"Acquit someone OF charges".', 'Legal Vocabulary B2'),
    q('prep_b2_12', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the error: "The new tax [A: applies] [B: on] all [C: imported] consumer [D: goods]."',
      ['A: applies', 'B: on - "applies TO"!', 'C: imported', 'D: goods'], 1,
      '"Apply to" (meaning have relevance or legal force over).', 'Collocations B2'),
    q('prep_b2_13', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which adjective governs the dependent preposition "OF"?',
      ['Innocent (innocent of a crime)', 'Prone', 'Vulnerable', 'Allergic'], 0,
      '"Innocent of". Prone to, vulnerable to, allergic to.', 'Dependent Prepositions B2'),
    q('prep_b2_14', 'B2', 'open_bracket', 'Open Bracket', 'Producing',
      'Supply the preposition: "The minister was compromised (by / through) ______ his association with the lobbyist."',
      ['by', 'with', 'at', 'on'], 0,
      'Agentive/instrumental cause with passive: "compromised by his association".', 'Passive Prepositions B2'),
    q('prep_b2_15', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Assemble: [compromise / agreed / on / reached / both / terms / a / parties]',
      ['Both parties reached an agreed compromise on terms.', 'Both parties agreed on terms reached a compromise.', 'Reached both parties a compromise agreed on terms.', 'On terms both parties reached an agreed compromise.'], 0,
      'Subject (Both parties) + Verb (reached) + Object (an agreed compromise on terms).', 'Syntax B2')
  );

  // C1 & C2 (20 items: 10 C1 + 10 C2)
  items.push(
    q('prep_c1_1', 'C1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Select the formal Latinate phrase meaning "in place of / instead of":',
      ['In lieu of', 'In light of', 'In spite of', 'In view of'], 0,
      '"In lieu of" strictly means in place of / instead of (e.g., "accepted shares in lieu of salary").', 'Cambridge C1 Advanced'),
    q('prep_c1_2', 'C1', 'open_bracket', 'Open Bracket', 'Producing',
      'Supply the formal fronted preposition: "The treaty, (under / by) ______ the terms of which trade was resumed, expired in 1914."',
      ['under', 'by', 'on', 'at'], 0,
      '"Under the terms of which..." is standard formal treaty language.', 'Pied-Piping C1'),
    q('prep_c1_3', 'C1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "The proposal is [A: completely] [B: at variance] [C: to] the council\'s [D: stated objectives]."',
      ['A: completely', 'B: at variance', 'C: to - "at variance WITH"!', 'D: stated objectives'], 2,
      'The fixed idiom is "at variance WITH" (meaning in contradiction or disagreement with).', 'Idiomatic Prepositions C1'),
    q('prep_c1_4', 'C1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The ambassador spoke under the aegis of the United Nations Security Council."',
      ['Correct - "under the aegis of" means under the protection/sponsorship of', 'Incorrect - ungrammatical idiom'], 0,
      '"Under the aegis of" is an established classical diplomatic idiom.', 'Diplomatic Register C1'),
    q('prep_c1_5', 'C1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Reconstruct: [whom / to / diplomat / the / credentials / the / presented / were / bowed]',
      ['The diplomat to whom the credentials were presented bowed.', 'To whom the credentials were presented the diplomat bowed.', 'The credentials to whom the diplomat were presented bowed.', 'Bowed the diplomat to whom the credentials were presented.'], 0,
      'Pied-piping relative clause: "The diplomat to whom the credentials were presented bowed."', 'C1 Syntax'),
    q('prep_c1_6', 'C1', 'cloze', 'Cloze Test', 'Understanding',
      'The company was deemed to be ______ violation of international trade sanctions.',
      ['in', 'at', 'on', 'by'], 0,
      'Legal collocation: "in violation of".', 'Legal English C1'),
    q('prep_c1_7', 'C1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which prepositional phrase means "at intense disagreement / in bitter conflict"?',
      ['At loggerheads with', 'At liberty to', 'At the mercy of', 'At odds with'], 0,
      '"At loggerheads with" describes a state of stubborn confrontation.', 'C1 Idioms'),
    q('prep_c1_8', 'C1', 'matching', 'Matching', 'Understanding',
      'Match the formal phrase: "with a view to" -> what verb form follows?',
      ['+ gerund (-ing)', '+ bare infinitive', '+ past participle', '+ clause with that'], 0,
      '"With a view to" is followed by a gerund: "with a view to establishing diplomatic ties".', 'C1 Complementation'),
    q('prep_c1_9', 'C1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'His actions were ______ compatible with the ethical standards expected of a public servant.',
      ['hardly', 'in', 'un', 'dis'], 0,
      '"Hardly compatible with" is a formal academic collocation.', 'Collocations C1'),
    q('prep_c1_10', 'C1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "They traded concessions on reciprocal basis."',
      ['Incorrect - requires the preposition "on a reciprocal basis"', 'Correct'], 0,
      'The established phrase is "on a reciprocal basis" (with indefinite article).', 'C1 Precision'),

    // C2 (10 items)
    q('prep_c2_1', 'C2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Identify the Latinate legal preposition meaning "without prejudice to":',
      ['Salvo', 'Coram', 'Ultra', 'Infra'], 0,
      '"Salvo" (from Latin salvus) is used in classical statutory English meaning "saving / without prejudice to".', 'C2 Legal Jurisprudence'),
    q('prep_c2_2', 'C2', 'open_bracket', 'Open Bracket', 'Producing',
      'Supply the high-register idiom: "The two factions remain at (loggerheads / heads) ______ over sovereign maritime rights."',
      ['loggerheads', 'crossroads', 'headwinds', 'crosshairs'], 0,
      '"At loggerheads" (meaning intractable dispute).', 'C2 Idiomatic English'),
    q('prep_c2_3', 'C2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the subtle defect: "He was [A: exonerated] [B: for] any [C: complicity] [D: in the plot]."',
      ['A: exonerated', 'B: for - "exonerated FROM (or of)"!', 'C: complicity', 'D: in the plot'], 1,
      '"Exonerate from/of blame", not *exonerate for.', 'C2 Legal Collocations'),
    q('prep_c2_4', 'C2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Reconstruct: [aegis / the / under / auspices / and / council / the / of / meeting / convened / was]',
      ['The meeting was convened under the aegis and auspices of the council.', 'Under the aegis and auspices of the council the meeting was convened.', 'The council was convened under the aegis and auspices of the meeting.', 'Convened was the meeting under the aegis and auspices of the council.'], 0,
      'High diplomatic prose style: "under the aegis and auspices of...".', 'C2 Diplomatic Style'),
    q('prep_c2_5', 'C2', 'cloze', 'Cloze Test', 'Understanding',
      'The minister acted in total ______ of established parliamentary conventions.',
      ['contravention', 'contraventing', 'contraventionment', 'contraventive'], 0,
      '"In contravention of": in violation or defiance of.', 'C2 Legal Lexis'),
    q('prep_c2_6', 'C2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which prepositional idiom means "in the very act of committing a crime"?',
      ['In flagrante delicto', 'Sub judice', 'Prima facie', 'Ipso facto'], 0,
      '"In flagrante delicto" (caught red-handed).', 'Latin Legal Phrases C2'),
    q('prep_c2_7', 'C2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The case is currently sub ______, and public commentary is legally restricted.',
      ['judice', 'rosa', 'silentio', 'lege'], 0,
      '"Sub judice" (under judicial consideration, hence prohibited from public discussion).', 'C2 Legal English'),
    q('prep_c2_8', 'C2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The proceedings were conducted sub rosa, behind barred doors."',
      ['Correct - "sub rosa" is a classical idiom meaning in secret / confidentially', 'Incorrect - ungrammatical'], 0,
      '"Sub rosa" (under the rose) means confidentially / in secret.', 'Classical Idioms C2'),
    q('prep_c2_9', 'C2', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the flaw: "He [A: acted] [B: under the guise] [C: with] a neutral [D: observer]."',
      ['A: acted', 'B: under the guise', 'C: with - "under the guise OF"!', 'D: observer'], 2,
      '"Under the guise of...", not *with.', 'Fixed Prepositional Idioms C2'),
    q('prep_c2_10', 'C2', 'open_bracket', 'Open Bracket', 'Producing',
      'Complete the formal Latinate phrase: "The judgment stands (per / pro) ______ incuriam, having overlooked binding precedent."',
      ['per', 'pro', 'in', 'de'], 0,
      '"Per incuriam" (through lack of care or regard for a statutory provision).', 'C2 Jurisprudence')
  );

  return items;
}

module.exports = { getPrepositions };
