// scripts/build_inter_art_tenses.js
// Interjections, Articles, Tenses Present, Tenses Past, Tenses Future
const { q } = require('./q_helper');

function getInterjections() {
  const items = [];
  const levels = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'];
  const counts = { A1: 15, A2: 15, B1: 15, B2: 15, C1: 10, C2: 10 };

  const pool = {
    A1: [
      q('int_a1_1', 'A1', 'multiple_choice', 'Multiple Choice', 'Understanding',
        'Which interjection expresses sudden physical pain?', ['Wow!', 'Ouch!', 'Hey!', 'Yay!'], 1,
        '"Ouch!" is the standard exclamation of sudden pain.', 'British Council A1'),
      q('int_a1_2', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
        '"______! Look at that shooting star in the night sky!"', ['Wow', 'Ouch', 'Ugh', 'Shh'], 0,
        '"Wow!" expresses wonder, amazement, or awe.', 'test-english A1'),
      q('int_a1_3', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
        'Evaluate: "Shh! The baby is sleeping in the next room."',
        ['Correct - "Shh" urges silence or quietness', 'Incorrect - interjections cannot be used in a sentence'], 0,
        '"Shh!" is an onomatopoeic interjection urging quiet.', 'Cambridge A1'),
      q('int_a1_4', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
        'Which interjection expresses JOY or celebration?', ['Yay!', 'Ouch!', 'Ugh!', 'Oops!'], 0,
        '"Yay!" expresses triumph, celebration, or joy.', 'Wordwall A1'),
      q('int_a1_5', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
        'Arrange: [did / you / look / hey / that / see / ?]',
        ['Hey, did you see that?', 'Did you see that hey?', 'See that hey did you?', 'Hey see that you did?'], 0,
        'Conversational opener: "Hey, did you see that?".', 'Bamboozle A1'),
      q('int_a1_6', 'A1', 'checking_error', 'Checking Error', 'Explaining',
        'Spot the flaw: "Oops [A: I] [B: accidentally] [C: dropped] the [D: milk jug]."',
        ['A: I - missing punctuation after interjection: "Oops! I..." or "Oops, I..."', 'B: accidentally', 'C: dropped', 'D: milk jug'], 0,
        'Interjections must be punctuated with an exclamation point or comma.', 'Punctuation A1'),
      q('int_a1_7', 'A1', 'matching', 'Matching', 'Memory',
        'Match: "Oops!" ->', ['Expresses a minor accidental mistake', 'Expresses extreme anger', 'Calls for complete silence', 'Shows greetings'], 0,
        '"Oops!" acknowledges an accidental spill or small mistake.', 'Oxford A1'),
      q('int_a1_8', 'A1', 'open_bracket', 'Open Bracket', 'Producing',
        'Select the greeting interjection: "(Hello / Goodbye) ______! How are you today?"',
        ['Hello', 'Goodbye', 'Ouch', 'Oops'], 0,
        '"Hello!" is the universal greeting interjection.', 'Elementary Interjections'),
      q('int_a1_9', 'A1', 'cloze', 'Cloze Test', 'Understanding',
        '"______, that spider looks scary!"', ['Eek', 'Yay', 'Bingo', 'Bravo'], 0,
        '"Eek!" expresses sudden shock, fear, or alarm.', 'test-english A1'),
      q('int_a1_10', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
        'Evaluate: "Hurrah! Our team won the football match!"',
        ['Correct - "Hurrah!" expresses victory/triumph', 'Incorrect'], 0,
        '"Hurrah!" is an established exclamation of victory.', 'British Council A1'),
      q('int_a1_11', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
        '"______! Don\'t touch that hot stove!"', ['Hey', 'Yay', 'Hmm', 'Aha'], 0,
        '"Hey!" is used to attract urgent attention or issue a warning.', 'VOA English A1'),
      q('int_a1_12', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
        'Which interjection expresses DISGUST?', ['Yuck!', 'Yum!', 'Yay!', 'Hurrah!'], 0,
        '"Yuck!" expresses disgust. "Yum!" expresses deliciousness.', 'Wordwall A1'),
      q('int_a1_13', 'A1', 'open_bracket', 'Open Bracket', 'Producing',
        'Complete the exclamation of relief: "(Phew / Ouch) ______! That was a close call!"',
        ['Phew', 'Ouch', 'Ugh', 'Oops'], 0,
        '"Phew!" expresses relief after suspense or danger.', 'Cambridge A1'),
      q('int_a1_14', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
        'Put in order: [you / congratulations / graduated / on / having]',
        ['Congratulations on having graduated!', 'Having graduated on congratulations you!', 'You on having graduated congratulations!', 'Congratulations you on having graduated!'], 0,
        'Exclamative formula: "Congratulations on having graduated!".', 'Syntax A1'),
      q('int_a1_15', 'A1', 'checking_error', 'Checking Error', 'Explaining',
        'Identify the defect: "Oh [A: what a] [B: beautiful] [C: sunrise] [D: is it!]"',
        ['A: what a', 'B: beautiful', 'C: sunrise', 'D: is it! - exclamatives do not invert: "what a beautiful sunrise it is!"'], 3,
        'Exclamative sentences retain normal subject-verb order: "what a beautiful sunrise it is!".', 'Exclamative Syntax A1')
    ],
    A2: [
      q('int_a2_1', 'A2', 'multiple_choice', 'Multiple Choice', 'Understanding',
        'What does the conversational filler "Hmm..." indicate?',
        ['Thinking / contemplation before answering', 'Sudden physical pain', 'Victory celebration', 'Anger'], 0,
        '"Hmm" indicates hesitation, contemplation, or reflection.', 'test-english A2'),
      q('int_a2_2', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
        '"______, I didn\'t see you standing there!"', ['Oh', 'Hurrah', 'Bravo', 'Yuck'], 0,
        '"Oh!" expresses surprise or mild startle.', 'Cambridge A2'),
      q('int_a2_3', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
        'Evaluate: "Aha! I finally found where I left my car keys!"',
        ['Correct - "Aha!" expresses sudden realization or discovery', 'Incorrect'], 0,
        '"Aha!" marks the triumph of discovery or sudden understanding.', 'British Council A2'),
      q('int_a2_4', 'A2', 'open_bracket', 'Open Bracket', 'Producing',
        'Supply the applause interjection: "(Bravo / Bah) ______! That was a magnificent violin solo!"',
        ['Bravo', 'Bah', 'Ugh', 'Ouch'], 0,
        '"Bravo!" expresses acclaim and applause for an artistic performance.', 'Oxford A2'),
      q('int_a2_5', 'A2', 'checking_error', 'Checking Error', 'Explaining',
        'Spot the flaw: "Well [A: I] [B: am not] [C: sure about] [D: that plan]."',
        ['A: I - missing comma after introductory discourse interjection "Well,"', 'B: am not', 'C: sure about', 'D: that plan'], 0,
        'Introductory discourse markers like "Well," require a comma.', 'Punctuation A2'),
      q('int_a2_6', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
        'Which interjection expresses BOREDOM or FRUSTRATION?', ['Ugh!', 'Yippee!', 'Bingo!', 'Bravo!'], 0,
        '"Ugh!" expresses disgust, exhaustion, or frustration.', 'Wordwall A2'),
      q('int_a2_7', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [idea / what / brilliant / a / !]',
      ['What a brilliant idea!', 'A brilliant idea what!', 'Idea what a brilliant!', 'What brilliant a idea!'], 0,
      'Exclamative structure: "What a + adjective + noun!".', 'Syntax A2'),
      q('int_a2_8', 'A2', 'cloze', 'Cloze Test', 'Understanding',
        '"______! That was a close call; the car almost hit us."', ['Phew', 'Yum', 'Oops', 'Yay'], 0,
        '"Phew!" indicates narrow escape and relief.', 'test-english A2'),
      q('int_a2_9', 'A2', 'matching', 'Matching', 'Understanding',
        'Match: "Uh-huh" ->', ['Informal affirmative / agreement ("yes")', 'Strong negative disagreement', 'Call for emergency help', 'Formal greeting'], 0,
        '"Uh-huh" is an informal affirmative response.', 'Cambridge A2'),
      q('int_a2_10', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
        'Evaluate: "Gosh, this suitcase is incredibly heavy!"',
        ['Correct - "Gosh" is a mild euphemistic exclamation of surprise', 'Incorrect'], 0,
        '"Gosh" is a common euphemism for expressing mild surprise.', 'British Council A2'),
      q('int_a2_11', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
        '"______! I told you not to touch that hot pan!"', ['See', 'Yay', 'Bingo', 'Phew'], 0,
        '"See!" is used to vindicate a prior warning.', 'VOA English A2'),
      q('int_a2_12', 'A2', 'open_bracket', 'Open Bracket', 'Producing',
        'Complete the exclamation of success: "(Bingo / Bah) ______! That is the exact address we needed!"',
        ['Bingo', 'Bah', 'Ugh', 'Ouch'], 0,
        '"Bingo!" announces the exact match or discovery.', 'Idioms A2'),
      q('int_a2_13', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
        'Which interjection is an informal greeting?', ['Hi!', 'Bah!', 'Ouch!', 'Ugh!'], 0,
        '"Hi!" is an informal greeting.', 'Wordwall A2'),
      q('int_a2_14', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
        'Put in order: [luck / good / with / your / exam / !]',
        ['Good luck with your exam!', 'Your exam with good luck!', 'With your exam good luck!', 'Luck good with your exam!'], 0,
        'Exclamative wish formula: "Good luck with your exam!".', 'Syntax A2'),
      q('int_a2_15', 'A2', 'checking_error', 'Checking Error', 'Explaining',
        'Identify the mistake: "How [A: beautiful] [B: is the garden] [C: in] [D: spring!]"',
        ['A: beautiful', 'B: is the garden - exclamatives do not invert: "the garden is"!', 'C: in', 'D: spring!'], 1,
        '"How + adjective + subject + verb!": "How beautiful THE GARDEN IS in spring!".', 'Exclamatives A2')
    ],
    B1: [
      q('int_b1_1', 'B1', 'multiple_choice', 'Multiple Choice', 'Understanding',
        'Which literary interjection conveys deep sorrow, regret, or grief?', ['Alas!', 'Yippee!', 'Aha!', 'Phew!'], 0,
        '"Alas!" is a classical exclamation of grief, pity, or regret.', 'Cambridge B1'),
      q('int_b1_2', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
        '"______! We have searched everywhere, but the ancient parchment is lost forever."',
        ['Alas', 'Bravo', 'Bingo', 'Yay'], 0,
        '"Alas" introduces tragic loss or mournful regret.', 'test-english B1'),
      q('int_b1_3', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
        'Evaluate: "Indeed, the experimental results substantiate the initial hypothesis."',
        ['Correct - "Indeed" functions as an emphatic affirmative discourse adverbial/interjection', 'Incorrect'], 0,
        '"Indeed" affirms and emphasizes agreement in formal discourse.', 'Oxford B1'),
      q('int_b1_4', 'B1', 'open_bracket', 'Open Bracket', 'Producing',
        'Supply the interjection of exasperation: "(Bother / Bravo) ______! I forgot to save the document before the computer crashed!"',
        ['Bother', 'Bravo', 'Hurrah', 'Eureka'], 0,
        '"Bother!" is a mild British exclamation of annoyance.', 'British Council B1'),
      q('int_b1_5', 'B1', 'checking_error', 'Checking Error', 'Explaining',
        'Spot the flaw: "Alas, [A: the valiant] knight [B: was] [C: fallen] in [D: battle.]"',
        ['A: the valiant', 'B: was', 'C: fallen - in modern English say "had fallen" or "fell"', 'D: battle.'], 2,
        'Say "had fallen" or "fell in battle".', 'B1 Literary Syntax'),
      q('int_b1_6', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
        'Which interjection is uttered upon experiencing a sudden scientific or creative discovery?',
        ['Eureka!', 'Alas!', 'Bah!', 'Ouch!'], 0,
        '"Eureka!" (from Greek heureka - "I have found it!") celebrates sudden creative breakthrough.', 'Wordwall B1'),
      q('int_b1_7', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
        'Assemble: [all / after / indeed / right / you / were]',
        ['Indeed, you were right after all.', 'After all you were right indeed.', 'You were right indeed after all.', 'Right you were indeed after all.'], 0,
        'Emphatic confirmation: "Indeed, you were right after all."', 'Syntax B1'),
      q('int_b1_8', 'B1', 'cloze', 'Cloze Test', 'Understanding',
        '"______! The deadline is in twenty minutes and we haven\'t finished printing!"',
        ['Heavens', 'Yay', 'Bravo', 'Bingo'], 0,
        '"Heavens!" or "Good heavens!" expresses shock, anxiety, or dismay.', 'test-english B1'),
      q('int_b1_9', 'B1', 'matching', 'Matching', 'Understanding',
        'Match: "By all means!" ->', ['Enthusiastic permission / agreement ("certainly")', 'Refusal', 'Sympathy', 'Disbelief'], 0,
        '"By all means!" grants polite, willing permission.', 'Cambridge B1'),
      q('int_b1_10', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
        'Evaluate: "Darn it! I missed the last bus home!"',
        ['Correct - mild colloquial euphemism for annoyance', 'Incorrect'], 0,
        '"Darn it!" is a mild, acceptable colloquial euphemism.', 'British Council B1'),
      q('int_b1_11', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
        '"______, let us examine the second proposition on the agenda."', ['Now', 'Ouch', 'Yay', 'Oops'], 0,
        'Discourse marker "Now" signals a transition to a new topic.', 'VOA English B1'),
      q('int_b1_12', 'B1', 'open_bracket', 'Open Bracket', 'Producing',
        'Supply the interjection: "(Goodness / Yuck) ______ gracious! What an enormous library!"',
        ['Goodness', 'Yuck', 'Oops', 'Bah'], 0,
        'Fixed idiom: "Goodness gracious!" expressing astonishment.', 'Idioms B1'),
      q('int_b1_13', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which phrase is an exclamation of CONDOLENCE?',
      ['My deepest condolences!', 'Congratulations!', 'Hurrah!', 'Bingo!'], 0,
      '"My deepest condolences!" expresses sympathy in bereavement.', 'Social Conventions B1'),
      q('int_b1_14', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
        'Arrange: [grief / what / tragedy / alas / and / a / !]',
        ['Alas, what a tragedy and grief!', 'What a tragedy and grief, alas!', 'And grief alas what a tragedy!', 'A tragedy what alas and grief!'], 0,
        'Literary exclamation: "Alas, what a tragedy and grief!".', 'Syntax B1'),
      q('int_b1_15', 'B1', 'checking_error', 'Checking Error', 'Explaining',
        'Find the mistake: "Dear me [A: I] [B: had no idea] [C: the situation] was [D: so grave]."',
        ['A: I - missing comma after "Dear me,"', 'B: had no idea', 'C: the situation', 'D: so grave'], 0,
        '"Dear me," requires a comma before the main clause.', 'Punctuation B1')
    ],
    B2: [
      q('int_b2_1', 'B2', 'multiple_choice', 'Multiple Choice', 'Understanding',
        'What pragmatic function does "Come off it!" serve in British discourse?',
        ['Rejects an assertion as exaggerated, absurd, or implausible', 'Expresses formal agreement', 'Invites someone to speak louder', 'Calls for an immediate ceasefire'], 0,
        '"Come off it!" is a colloquial British interjection dismissing an absurd claim.', 'Cambridge B2 First'),
      q('int_b2_2', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
        '"______! That argument is sheer nonsense; look at the empirical data!"',
        ['Rubbish', 'Bravo', 'Hear', 'Bingo'], 0,
        '"Rubbish!" dismisses a thesis as invalid or absurd.', 'test-english B2'),
      q('int_b2_3', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
        'Evaluate: "Hear, hear! The minister\'s proposal deserves unanimous endorsement."',
        ['Correct - parliamentary interjection shouting approval of a speaker\'s remarks', 'Incorrect'], 0,
        '"Hear, hear!" (shortened from "Hear him, hear him") expresses approval in assemblies.', 'Oxford B2'),
      q('int_b2_4', 'B2', 'open_bracket', 'Open Bracket', 'Producing',
        'Provide the parliamentary exclamation of agreement: "(Hear / Here) ______ hear!"',
        ['Hear, hear', 'Here, here', 'Hear, here', 'Here, hear'], 0,
        'Spelled "Hear, hear!" (meaning "listen to him!").', 'Spelling Traps B2'),
      q('int_b2_5', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "Here, here! [A: We fully] [B: support] the [C: motion] [D: on the table]."',
      ['A: We fully', 'B: support', 'C: motion', 'Spelled "Here, here!" instead of "Hear, hear!"'], 3,
      'The traditional spelling is "Hear, hear!" (not *Here, here).', 'Parliamentary English B2'),
      q('int_b2_6', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
        'Which interjection functions as a PARENTHETICAL HEDGING DEVICE?',
        ['Mind you', 'Hurrah', 'Bingo', 'Yum'], 0,
        '"Mind you" cautions the listener to consider an important counter-qualification.', 'Discourse Markers B2'),
      q('int_b2_7', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
        'Assemble: [it / expensive / is / you / mind / a / car / luxury]',
        ['Mind you, it is an expensive luxury car.', 'It is an expensive luxury car, mind you.', 'A luxury car it is expensive, mind you.', 'Luxury car mind you it is an expensive.'], 0,
        'Parenthetical qualification: "Mind you, it is an expensive luxury car."', 'Syntax B2'),
      q('int_b2_8', 'B2', 'cloze', 'Cloze Test', 'Understanding',
        '"______! Do you expect us to believe that fabricated excuse?"', ['Come now', 'Hurrah', 'Bravo', 'Yum'], 0,
        '"Come now!" urges reasonableness and challenges prevarication.', 'B2 Conversational Idioms'),
      q('int_b2_9', 'B2', 'matching', 'Matching', 'Understanding',
        'Match: "For heaven\'s sake!" ->', ['Exasperated appeal or impatience', 'Joyful celebration', 'Polite greeting', 'Farewell'], 0,
        'Expresses exasperation or intense pleading.', 'British Council B2'),
      q('int_b2_10', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
        'Evaluate: "So be it; if they reject our peaceful terms, war is inevitable."',
        ['Correct - classical formulaic resignation / acceptance meaning "let it be so"', 'Incorrect'], 0,
        '"So be it" is an established formulaic subjunctive of resignation.', 'Formulaic Subjunctive B2'),
      q('int_b2_11', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
        '"______, let us not jump to hasty conclusions before the forensic report arrives."',
        ['Now then', 'Oops', 'Yuck', 'Ouch'], 0,
        '"Now then" calms agitation and refocuses discussion.', 'Discourse B2'),
      q('int_b2_12', 'B2', 'open_bracket', 'Open Bracket', 'Producing',
        'Complete the warning: "(Look / Watch) ______ out! That scaffolding is collapsing!"',
        ['Look', 'Watch', 'See', 'Take'], 0,
        'Exclamative warning: "Look out!" or "Watch out!".', 'Emergency Exclamations B2'),
      q('int_b2_13', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
        'Which phrase is an EXCLAMATION OF IMPATIENCE?',
        ['Get on with it!', 'Take your time!', 'By all means!', 'Be my guest!'], 0,
        '"Get on with it!" urges someone to hurry or proceed without delay.', 'Wordwall B2'),
      q('int_b2_14', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
        'Put in order: [heaven\'s / for / what / on / doing / sake / you / are / earth / ?]',
        ['For heaven\'s sake, what on earth are you doing?', 'What on earth are you doing for heaven\'s sake?', 'Doing what on earth are you for heaven\'s sake?', 'For heaven\'s sake doing what on earth are you?'], 0,
        'Double exclamative reinforcement: "For heaven\'s sake, what on earth are you doing?".', 'Syntax B2'),
      q('int_b2_15', 'B2', 'checking_error', 'Checking Error', 'Explaining',
        'Spot the mistake: "Well, [A: that is] [B: certainly] a [C: rather unexpected] [D: development!]"',
        ['A: that is', 'B: certainly', 'C: rather unexpected', 'D: development! - Flawless sentence!'], 3,
        'The sentence is completely correct.', 'Error Checking B2')
    ],
    C1: [
      q('int_c1_1', 'C1', 'multiple_choice', 'Multiple Choice', 'Understanding',
        'Analyze the rhetorical presentational interjection: "Lo and behold, the missing heir stepped into the hall!" What does it signal?',
        ['A dramatic, unexpected revelation or turn of events', 'An apology', 'An imperative prohibition', 'A concessive condition'], 0,
        '"Lo and behold!" dramatically heralds an astonishing discovery or spectacle.', 'Cambridge C1 Advanced'),
      q('int_c1_2', 'C1', 'open_bracket', 'Open Bracket (Archaic Interjection)', 'Producing',
        'Supply the archaic exclamative: "(Hark / Hush) ______! Didst thou not hear the nocturnal chime?"',
        ['Hark', 'Hush', 'Lo', 'Alas'], 0,
        '"Hark!" (from Old English heorcnian) is an archaic imperative interjection meaning "listen attentively!".', 'Archaic Rhetoric C1'),
      q('int_c1_3', 'C1', 'checking_error', 'Checking Error', 'Explaining',
        'Spot the flaw: "Lo and behold [A: the prodigal] [B: son] [C: returned] [D: to his homeland.]"',
        ['A: the prodigal - missing comma after introductory interjection "Lo and behold,"', 'B: son', 'C: returned', 'D: to his homeland.'], 0,
        'Parenthetical interjection: "Lo and behold, the prodigal son returned...".', 'Punctuation C1'),
      q('int_c1_4', 'C1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
        'Evaluate: "Woe betide anyone who dares violate the sanctity of this sanctuary."',
        ['Correct - archaic formulaic subjunctive curse/warning meaning "bad fortune will come to"', 'Incorrect - ungrammatical English'], 0,
        '"Woe betide..." is an established classical optative/curse formula.', 'C1 Classical Idioms'),
      q('int_c1_5', 'C1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
        'Assemble: [woe / to / those / who / justice / pervert]',
        ['Woe unto those who pervert justice!', 'Those who pervert justice woe unto!', 'Unto those who pervert justice woe!', 'Pervert justice woe unto those who!'], 0,
        'Biblical/Classical exclamative formula: "Woe unto those who pervert justice!".', 'C1 Rhetoric'),
      q('int_c1_6', 'C1', 'cloze', 'Cloze Test', 'Understanding',
        '"______! What an unprincipled breach of diplomatic etiquette!"', ['Fie', 'Yay', 'Bingo', 'Yum'], 0,
        '"Fie!" is an archaic interjection expressing righteous moral indignation or disgust.', 'Literary English C1'),
      q('int_c1_7', 'C1', 'odd_one_out', 'Odd One Out', 'Memory',
        'Which term describes primary interjections that lack word-internal grammatical composition?',
        ['Primary interjections (e.g. Ouch, Phew)', 'Secondary interjections (e.g. Heavens, Heavens above)', 'Nominal compounds', 'Phrasal verbs'], 0,
        'Primary interjections are non-derived expressive vocalizations.', 'Linguistic Grammar C1'),
      q('int_c1_8', 'C1', 'matching', 'Matching', 'Understanding',
        'Match: "God forbid!" ->', ['Expresses fervent hope that a catastrophe does NOT occur', 'Blessing', 'Farewell', 'Celebration'], 0,
        'Formulaic optative subjunctive wishing to ward off disaster.', 'Formulaic Expressions C1'),
      q('int_c1_9', 'C1', 'fill_blank', 'Fill in the Blank', 'Producing',
        '"______ forbid that such a tragedy should ever recur!"', ['Heaven', 'World', 'Earth', 'Life'], 0,
        '"Heaven forbid that..." is the established formal formulaic subjunctive.', 'C1 Subjunctive Idioms'),
      q('int_c1_10', 'C1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
        'Evaluate: "Perish the thought that our sovereign institutions could fall into tyranny."',
        ['Correct - formulaic subjunctive expressing absolute abhorrence of an idea', 'Incorrect'], 0,
        '"Perish the thought" rejects a suggestion as unthinkable.', 'C1 Formulaic Subjunctive')
    ],
    C2: [
      q('int_c2_1', 'C2', 'multiple_choice', 'Multiple Choice', 'Understanding',
        'What syntactic status do true primary interjections hold within generative clausal grammar?',
        ['Syntactically extra-clausal parentheticals devoid of argument-structure dependency', 'Heads of verb phrases', 'Prepositional adjuncts', 'Relative pro-forms'], 0,
        'Primary interjections are peripheral, extra-sentential expressive tokens outside clausal dependency trees.', 'Theoretical Syntax C2'),
      q('int_c2_2', 'C2', 'open_bracket', 'Open Bracket (Archaic Oath)', 'Producing',
        'Supply the archaic Shakespearean exclamation: "(Marry / Merry) ______! I never beheld such audacity!"',
        ['Marry', 'Merry', 'Mary', 'Marie'], 0,
        '"Marry!" was an Elizabethan exclamation/oath derived from the name of the Virgin Mary.', 'Shakespearean Lexis C2'),
      q('int_c2_3', 'C2', 'checking_error', 'Checking Error', 'Explaining',
        'Identify the flaw: "Alack and [A: well-a-day] [B: the kingdom] [C: were plunged] into [D: mourning]."',
        ['A: well-a-day', 'B: the kingdom', 'C: were plunged - singular "kingdom" takes "WAS plunged"!', 'D: mourning'], 2,
        'Singular subject "the kingdom" takes "was plunged".', 'Archaic Concord C2'),
      q('int_c2_4', 'C2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
        'Reconstruct: [perish / the / thought / that / honor / should / die]',
        ['Perish the thought that honor should die!', 'That honor should die perish the thought!', 'The thought perish that honor should die!', 'Honor should die perish the thought that!'], 0,
        'Classical optative subjunctive formula: "Perish the thought that...".', 'Classical Rhetoric C2'),
      q('int_c2_5', 'C2', 'cloze', 'Cloze Test', 'Understanding',
        '"______! What ungodly treachery is this that strikes in the night?"', ['Zounds', 'Yay', 'Oops', 'Bingo'], 0,
        '"Zounds!" (archaic oath: "God\'s wounds") expresses profound indignation.', 'Historical English C2'),
      q('int_c2_6', 'C2', 'odd_one_out', 'Odd One Out', 'Memory',
        'Which item is an ARCHETYPE OF SECONDARY INTERJECTION?',
        ['Good grief! (derived from standard lexical noun phrase)', 'Ouch!', 'Ugh!', 'Phew!'], 0,
        '"Good grief" is a secondary interjection derived from lexical morphemes.', 'Morphological Categorization C2'),
      q('int_c2_7', 'C2', 'fill_blank', 'Fill in the Blank', 'Producing',
        '"Woe is me, for I am ______!" cried the desolate monarch.', ['undone', 'undoing', 'undid', 'undone-ness'], 0,
        'Classical literary lamentation: "Woe is me, for I am undone!".', 'Biblical Syntax C2'),
      q('int_c2_8', 'C2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
        'Evaluate: "Alack the day that ever I was born!"',
        ['Correct - archaic Shakespearean lamentation of tragedy', 'Incorrect'], 0,
        '"Alack the day!" is an authentic Shakespearean tragic lamentation.', 'Elizabethan Syntax C2'),
      q('int_c2_9', 'C2', 'checking_error', 'Checking Error', 'Explaining',
        'Spot the flaw: "Out [A: upon it!] [B: I will] [C: have none of] [D: your treasonous counsel.]"',
        ['A: upon it!', 'B: I will', 'C: have none of', 'D: your treasonous counsel. - Flawless classical dramatic idiom!'], 3,
        '"Out upon it!" is an authentic classical exclamation of condemnation.', 'C2 Drama'),
      q('int_c2_10', 'C2', 'open_bracket', 'Open Bracket', 'Producing',
        'Complete the Shakespearean exclamation of disdain: "(Fie / Fee) ______ on thee, false traitor!"',
        ['Fie', 'Fee', 'Foe', 'Fum'], 0,
        '"Fie on thee!" expresses utter moral contempt.', 'Classical Rhetoric C2')
    ]
  };

  levels.forEach(lvl => {
    (pool[lvl] || []).forEach(item => items.push(item));
  });

  return items;
}

module.exports = { getInterjections };
