// scripts/build_pos_tests.js
// Parts of Speech: Nouns, Pronouns, Verbs, Adverbs (Topics 1 - 4)
const { q } = require('./q_helper');

function getNouns() {
  const items = [];
  
  // A1: 15 items
  items.push(
    q('noun_a1_1', 'A1', 'multiple_choice', 'Multiple Choice', 'Memory',
      'Which word is a noun in the following sentence: "The happy children play in the garden."',
      ['happy', 'children', 'play', 'in'], 1,
      '"Children" is a plural noun naming people. "Happy" is an adjective, "play" is a verb, and "in" is a preposition.', 'British Council A1'),
    q('noun_a1_2', 'A1', 'open_bracket', 'Open Bracket (Plural)', 'Producing',
      'Write the correct plural form of the noun in brackets: "There are two (bus) ______ waiting at the station."',
      ['buses', 'buss', 'busses', 'busies'], 0,
      'Nouns ending in -s, -sh, -ch, -x, or -z form their plural by adding -es: "buses".', 'Elementary Spelling Rules'),
    q('noun_a1_3', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate this sentence: "She has three childs and two cats."',
      ['Correct', 'Incorrect - the plural of "child" is "children"'], 1,
      '"Child" is an irregular noun; its standard plural is "children", not "childs".', 'test-english A1'),
    q('noun_a1_4', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which noun is the ODD ONE OUT because it is NOT a proper noun?',
      ['Siem Reap', 'Angkor Wat', 'School', 'Monday'], 2,
      '"School" is a common noun. "Siem Reap", "Angkor Wat", and "Monday" are proper nouns and are capitalized.', 'Wordwall ELT'),
    q('noun_a1_5', 'A1', 'fill_blank', 'Fill in the Blank', 'Understanding',
      'Please give me an ______ from the fruit basket.',
      ['apple', 'banana', 'orange juice', 'bread'], 0,
      '"An" is used before singular countable nouns beginning with a vowel sound: "an apple".', 'VOA English A1'),
    q('noun_a1_6', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange these words into a grammatical sentence: [has / a / red / brother / my / car]',
      ['My brother has a red car.', 'A red car has my brother.', 'My brother a red car has.', 'Has my brother a red car.'], 0,
      'Standard English word order is Subject (My brother) + Verb (has) + Object (a red car).', 'Bamboozle Word Order'),
    q('noun_a1_7', 'A1', 'checking_error', 'Checking Error', 'Explaining',
      'Find the mistake in the sentence: "The two [A: woman] [B: are] [C: reading] books in the [D: library]."',
      ['A: woman', 'B: are', 'C: reading', 'D: library'], 0,
      '"Two" requires the plural noun "women", not singular "woman".', 'Cambridge A1'),
    q('noun_a1_8', 'A1', 'matching', 'Matching', 'Memory',
      'Match the singular noun "tooth" with its correct irregular plural form:',
      ['tooths', 'teeth', 'toothes', 'teethes'], 1,
      'The irregular plural of "tooth" is "teeth" (vowel mutation).', 'Oxford A1'),
    q('noun_a1_9', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate this sentence: "Monday is the first day of the week."',
      ['Correct - "Monday" is capitalized as a proper noun', 'Incorrect - days of the week are common nouns'], 0,
      'Names of the days of the week are proper nouns and must always be capitalized.', 'British Council A1'),
    q('noun_a1_10', 'A1', 'open_bracket', 'Open Bracket (Plural)', 'Producing',
      'Change the noun in brackets into plural: "I saw three (baby) ______ in the clinic."',
      ['babys', 'babies', 'babyes', 'babyies'], 1,
      'Nouns ending in consonant + y change the "y" to "i" and add "-es": "babies".', 'Spelling Rules A1'),
    q('noun_a1_11', 'A1', 'cloze', 'Cloze Test', 'Understanding',
      'My father bought a new ______ for his home office yesterday.',
      ['computer', 'computering', 'computes', 'computered'], 0,
      'The blank requires a singular countable noun following the article "a new": "computer".', 'test-english A1'),
    q('noun_a1_12', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which word is the ODD ONE OUT (not a noun)?',
      ['Table', 'Window', 'Run', 'Teacher'], 2,
      '"Run" is a verb (action), while table, window, and teacher are nouns.', 'ELT Warmup Games'),
    q('noun_a1_13', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'A person who teaches students in a classroom is called a ______.',
      ['teacher', 'teaching', 'teaches', 'taught'], 0,
      'The noun naming the profession is "teacher" (noun with agent suffix -er).', 'British Council A1'),
    q('noun_a1_14', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Unscramble to make a correct sentence: [birds / the / sing / trees / in / the]',
      ['The birds sing in the trees.', 'In the trees sing the birds the.', 'The trees sing the birds in.', 'Birds the in the trees sing.'], 0,
      'Subject (The birds) + Verb (sing) + Prepositional Phrase (in the trees).', 'Wordwall English'),
    q('noun_a1_15', 'A1', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the error: "There are [A: five] [B: boxs] [C: on] the [D: floor]."',
      ['A: five', 'B: boxs', 'C: on', 'D: floor'], 1,
      'Nouns ending in -x add -es to form the plural: "boxes", not "boxs".', 'Spelling Traps A1')
  );

  // A2: 15 items
  items.push(
    q('noun_a2_1', 'A2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Which of the following is an UNCOUNTABLE noun?',
      ['Chair', 'Furniture', 'Table', 'Desk'], 1,
      '"Furniture" is an uncountable collective mass noun in English; individual pieces are called "pieces of furniture".', 'test-english A2'),
    q('noun_a2_2', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Could you please give me a slice of ______?',
      ['bread', 'breads', 'a bread', 'some breads'], 0,
      '"Bread" is uncountable. We use partitives like "a slice of bread" or "a loaf of bread".', 'Cambridge A2'),
    q('noun_a2_3', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The teacher gave us many useful advices for the exam."',
      ['Correct', 'Incorrect - "advice" is uncountable and cannot take -s or "many"'], 1,
      '"Advice" is strictly uncountable. Say "a lot of advice" or "pieces of advice".', 'British Council A2'),
    q('noun_a2_4', 'A2', 'open_bracket', 'Open Bracket (Plural)', 'Producing',
      'Supply the plural form: "The chef used three sharp (knife) ______ to prepare dinner."',
      ['knifes', 'knives', 'knifees', 'knivs'], 1,
      'Nouns ending in -fe (knife, life, wife) change -fe to -ves: "knives".', 'Oxford Practice A2'),
    q('noun_a2_5', 'A2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the mistake: "She [A: bought] [B: two] [C: new] [D: furnitures] for her bedroom."',
      ['A: bought', 'B: two', 'C: new', 'D: furnitures'], 3,
      '"Furniture" has no plural form. Say "two pieces of furniture".', 'test-english A2'),
    q('noun_a2_6', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which noun is the ODD ONE OUT because it is COUNTABLE?',
      ['Information', 'Luggage', 'Suitcase', 'Water'], 2,
      '"Suitcase" is countable (one suitcase, two suitcases). Information, luggage, and water are uncountable.', 'Wordwall A2'),
    q('noun_a2_7', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Unscramble the question: [much / how / have / luggage / you / do / ?]',
      ['How much luggage do you have?', 'How many luggage do you have?', 'How luggage do you have much?', 'Luggage how much you do have?'], 0,
      'Uncountable "luggage" requires quantifier "How much": "How much luggage do you have?".', 'Bamboozle A2'),
    q('noun_a2_8', 'A2', 'matching', 'Matching', 'Understanding',
      'Which quantifier correctly pairs with the uncountable noun "traffic"?',
      ['a few', 'heavy', 'many', 'several'], 1,
      'We say "heavy traffic" or "a lot of traffic". "Few", "many", and "several" only modify countable nouns.', 'Collocations A2'),
    q('noun_a2_9', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The news on TV is very shocking tonight."',
      ['Correct - "news" is singular in grammatical concord', 'Incorrect - "news" ends in -s so it requires "are"'], 0,
      'Although "news" ends in -s, it is an uncountable singular noun that takes a singular verb: "The news is...".', 'VOA English A2'),
    q('noun_a2_10', 'A2', 'fill_blank', 'Fill in the Blank', 'Understanding',
      'There ______ too much noise in this café; let us study in the library.',
      ['are', 'is', 'were', 'have'], 1,
      '"Noise" used as a general mass noun is uncountable and agrees with singular "is".', 'Cambridge A2'),
    q('noun_a2_11', 'A2', 'open_bracket', 'Open Bracket', 'Producing',
      'Form the compound noun: "You need a valid (pass / port) ______ to travel abroad."',
      ['passport', 'pass-porter', 'passporte', 'passing-port'], 0,
      'The single closed compound noun is "passport".', 'Word Formation A2'),
    q('noun_a2_12', 'A2', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the error: "He [A: has] [B: a lot of] [C: homeworks] [D: tonight]."',
      ['A: has', 'B: a lot of', 'C: homeworks', 'D: tonight'], 2,
      '"Homework" is uncountable in English. Say "a lot of homework" or "assignments".', 'School English Traps'),
    q('noun_a2_13', 'A2', 'cloze', 'Cloze Test', 'Understanding',
      'We need to buy two ______ of toothpaste at the supermarket.',
      ['tubes', 'bottles', 'slices', 'loaves'], 0,
      'The standard container partitive for toothpaste is "tubes of toothpaste".', 'Partitives A2'),
    q('noun_a2_14', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which irregular plural has a vowel change inside the word?',
      ['Children', 'Oxen', 'Men', 'Sheep'], 2,
      '"Man" -> "Men" undergoes vowel mutation. ("Children" and "oxen" add -(r)en; "sheep" has zero plural).', 'Irregular Plurals A2'),
    q('noun_a2_15', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange correctly: [gives / honest / my / always / friend / advice]',
      ['My friend always gives honest advice.', 'Always my friend gives honest advice.', 'My friend gives always honest advice.', 'Honest advice my friend always gives.'], 0,
      'Subject (My friend) + Frequency Adverb (always) + Verb (gives) + Object (honest advice).', 'Wordwall A2')
  );

  // B1: 15 items
  items.push(
    q('noun_b1_1', 'B1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'What is the correct plural form of the compound noun "sister-in-law"?',
      ['sister-in-laws', 'sisters-in-law', 'sisters-in-laws', 'sister-ins-law'], 1,
      'In compound nouns with prepositions, pluralize the principal noun: "sisters-in-law".', 'Cambridge B1 Preliminary'),
    q('noun_b1_2', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The staff ______ meeting in the boardroom right now to discuss the new project.',
      ['is', 'are', 'was', 'has'], 1,
      'In British ELT, collective nouns like "staff" or "team" take a plural verb when referring to the individual members acting.', 'British Council B1'),
    q('noun_b1_3', 'B1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the error: "A group of [A: researchers] [B: has published] three [C: papers] on [D: climatology]."',
      ['A: researchers', 'B: has published', 'C: papers', 'D: climatology - no error in sentence!'], 3,
      'The sentence is completely correct! "Papers" here countably means published academic articles.', 'test-english B1'),
    q('noun_b1_4', 'B1', 'open_bracket', 'Open Bracket (Nominalization)', 'Producing',
      'Convert the verb into a noun: "Their sudden (decide) ______ to sell the company surprised everyone."',
      ['decision', 'decidement', 'decisiveness', 'deciding'], 0,
      'The nominalization formed from "decide" is "decision".', 'Word Formation B1'),
    q('noun_b1_5', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The police is investigating the recent break-in at the store."',
      ['Correct', 'Incorrect - "police" is always grammatically plural and takes "are"'], 1,
      '"Police" is always a plural collective noun without -s: "The police ARE investigating".', 'Oxford B1 Traps'),
    q('noun_b1_6', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which noun has a plural form ending in "-ves"?',
      ['Roof', 'Cliff', 'Thief', 'Chef'], 2,
      '"Thief" -> "thieves". Roofs, cliffs, and chefs are regular and simply add -s.', 'Spelling Irregularities B1'),
    q('noun_b1_7', 'B1', 'cloze', 'Cloze Test', 'Understanding',
      'Her ______ of ancient Khmer history impressed the visiting university professors.',
      ['knowledges', 'knowledge', 'knowledging', 'knowledgability'], 1,
      '"Knowledge" is uncountable and never takes plural -s: "Her knowledge of...".', 'B1 Academic Vocabulary'),
    q('noun_b1_8', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [scissors / these / are / sharp / very / sewing]',
      ['These sewing scissors are very sharp.', 'These sharp sewing are scissors very.', 'Scissors sewing these are very sharp.', 'Very sharp are these sewing scissors.'], 0,
      '"These sewing scissors" (pair noun taking plural determiner and verb) + are + very sharp.', 'test-english B1'),
    q('noun_b1_9', 'B1', 'matching', 'Matching', 'Memory',
      'Which collective noun traditionally groups fish together?',
      ['A flock of fish', 'A herd of fish', 'A school of fish', 'A pack of fish'], 2,
      'The collective noun for fish is "a school of fish" (or "shoal").', 'Collective Nouns B1'),
    q('noun_b1_10', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "The acoustics in the newly built concert hall are magnificent."',
      ['Correct - "acoustics" referring to sound qualities takes a plural verb', 'Incorrect - ends in -ics so it must be singular'], 0,
      'When nouns ending in -ics refer to physical qualities (acoustics, athletics), they take plural agreement.', 'B1 Concord Rules'),
    q('noun_b1_11', 'B1', 'checking_error', 'Checking Error', 'Explaining',
      'Find the mistake: "She [A: bought] [B: a pair of] [C: jeans] that [D: was] on sale."',
      ['A: bought', 'B: a pair of', 'C: jeans', 'D: was'], 3,
      'When "that" refers back to "jeans" (or jeans directly), it takes "were", or if referring to "a pair", "was" is accepted, but in: "She bought jeans that WERE on sale."', 'Cambridge B1'),
    q('noun_b1_12', 'B1', 'open_bracket', 'Open Bracket', 'Producing',
      'Add the suffix for the abstract noun: "Regular exercise promotes good physical and mental (healthy) ______."',
      ['health', 'healthiness', 'healthful', 'healthement'], 0,
      'The abstract noun is "health".', 'Word Formation B1'),
    q('noun_b1_13', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which of these is an ABSTRACT noun (not physical/concrete)?',
      ['Bravery', 'Statue', 'River', 'Passport'], 0,
      '"Bravery" represents an intangible quality or concept (abstract noun).', 'Wordwall B1'),
    q('noun_b1_14', 'B1', 'fill_blank', 'Fill in the Blank', 'Understanding',
      'A large crowd of ______ gathered outside the national stadium.',
      ['spectator', 'spectators', 'spectatoring', 'spectatress'], 1,
      '"A crowd of..." takes a plural countable noun: "spectators".', 'B1 Sentence Completion'),
    q('noun_b1_15', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange into a clean sentence: [customs / the / airport / officers / inspected / our / at / bags]',
      ['Customs officers inspected our bags at the airport.', 'At the airport inspected customs officers our bags.', 'Our bags inspected customs officers at the airport.', 'Customs inspected officers our bags at the airport.'], 0,
      'Compound Subject (Customs officers) + Verb (inspected) + Direct Object (our bags) + Place (at the airport).', 'Syntax B1')
  );

  // B2: 15 items
  items.push(
    q('noun_b2_1', 'B2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'In which sentence does "glass" function as an uncountable mass noun?',
      ['He accidentally stepped on broken glass on the floor.', 'She poured herself a glass of orange juice.', 'He needs new glasses to read small print.', 'There was a glass on the bedside table.'], 0,
      'In option A, "glass" refers to the substance/material itself, making it uncountable mass.', 'Oxford B2 Practice'),
    q('noun_b2_2', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'There is a serious ______ of clean drinking water in the drought-affected region.',
      ['scarceness', 'scarcity', 'scarce', 'scarcifulness'], 1,
      'The formal abstract noun derived from the adjective "scarce" is "scarcity".', 'Word Formation B2'),
    q('noun_b2_3', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the error: "The committee [A: have] [B: signed] [C: their] names on [D: its] charter."',
      ['A: have', 'B: signed', 'C: their', 'D: its - clash in pronoun concord!'], 3,
      'Pronoun concord must be consistent: if using plural "have" and "their names", you must say "their charter", not "its".', 'Concord B2'),
    q('noun_b2_4', 'B2', 'open_bracket', 'Open Bracket (Plural)', 'Producing',
      'Provide the plural of the classical loan: "Scientists discovered several new (species) ______ in the rainforest."',
      ['species', 'specieses', 'specie', 'specii'], 0,
      '"Species" is an invariable noun whose singular and plural forms are identical.', 'Cambridge B2 First'),
    q('noun_b2_5', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "Economics have always been her favorite academic discipline."',
      ['Correct', 'Incorrect - academic subjects ending in -ics take a singular verb'], 1,
      'Names of academic subjects (economics, physics, mathematics) take a singular verb: "Economics has always been...".', 'test-english B2'),
    q('noun_b2_6', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which compound noun pluralizes ONLY the first element?',
      ['Passer-by', 'Mother-in-law', 'Attorney general', 'Toothbrush'], 3,
      '"Toothbrush" pluralizes the second noun: "toothbrushes". The others pluralize the head noun (passers-by, mothers-in-law, attorneys general).', 'Compound Plurals B2'),
    q('noun_b2_7', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Order into a formal sentence: [expansion / approved / the / factory / board / of / the / has]',
      ['The board has approved the expansion of the factory.', 'The factory expansion has the board approved of.', 'Of the factory the expansion has approved the board.', 'Has the board approved expansion the factory of.'], 0,
      'Subject (The board) + Auxiliary and Verb (has approved) + Object (the expansion of the factory).', 'B2 Syntax'),
    q('noun_b2_8', 'B2', 'cloze', 'Cloze Test', 'Understanding',
      'The government has introduced stricter ______ against illegal logging.',
      ['measures', 'measurings', 'measurements', 'measured'], 0,
      '"Measures" in the plural is a specific political/legal noun meaning official actions or sanctions.', 'Collocations B2'),
    q('noun_b2_9', 'B2', 'matching', 'Matching', 'Understanding',
      'Match the verb "persevere" with its correct noun form:',
      ['Perseverance', 'Perseveration', 'Perseverment', 'Perseverity'], 0,
      'The noun derived from "persevere" is "perseverance".', 'Cambridge B2 Word List'),
    q('noun_b2_10', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The luggage were loaded onto the cargo plane by the ground crew."',
      ['Correct', 'Incorrect - "luggage" is uncountable and requires singular "was"'], 1,
      '"Luggage" is strictly uncountable and takes a singular verb: "The luggage WAS loaded".', 'test-english B2'),
    q('noun_b2_11', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the error: "A [A: five-years-old] child [B: was] [C: rescued] from the [D: building]."',
      ['A: five-years-old', 'B: was', 'C: rescued', 'D: building'], 0,
      'When a compound numeral modifies a noun pre-nominally, the noun remains singular: "a five-year-old child".', 'Compound Modifiers B2'),
    q('noun_b2_12', 'B2', 'open_bracket', 'Open Bracket', 'Producing',
      'Form the noun: "The (fail) ______ of the bank triggered an economic panic."',
      ['failure', 'failingness', 'failment', 'failed'], 0,
      'The nominalization of "fail" is "failure".', 'Word Formation B2'),
    q('noun_b2_13', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which noun can be BOTH countable and uncountable with a shift in meaning?',
      ['Coffee', 'Information', 'Luggage', 'Furniture'], 0,
      '"Coffee" is uncountable as a liquid mass, but countable when ordering cups/portions: "two coffees, please".', 'B2 Semantic Shifts'),
    q('noun_b2_14', 'B2', 'fill_blank', 'Fill in the Blank', 'Understanding',
      'The company\'s sudden ______ of bankruptcy caused stock prices to plummet.',
      ['declaration', 'declarement', 'declarance', 'declarity'], 0,
      'The correct nominalization is "declaration".', 'Academic Nouns B2'),
    q('noun_b2_15', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Assemble the sentence: [concord / subject-verb / essential / is / for / academic / writing]',
      ['Subject-verb concord is essential for academic writing.', 'Academic writing is essential for subject-verb concord.', 'Essential is subject-verb concord for academic writing.', 'For academic writing is subject-verb concord essential.'], 0,
      'Subject (Subject-verb concord) + Verb (is) + Complement (essential) + Prepositional phrase (for academic writing).', 'B2 Syntax')
  );

  // C1 & C2: 20 items (10 C1 + 10 C2)
  items.push(
    q('noun_c1_1', 'C1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Select the plural form of the Greek loan noun "criterion":',
      ['criteria', 'criterions', 'criterias', 'criterium'], 0,
      'Nouns of Greek origin ending in -on form their plural in -a: "criterion" -> "criteria".', 'Cambridge C1 Advanced'),
    q('noun_c1_2', 'C1', 'open_bracket', 'Open Bracket (Latin Plural)', 'Producing',
      'Provide the classical plural form of the noun in brackets: "Multiple (hypothesis) ______ were proposed to explain the cosmic phenomenon."',
      ['hypotheses', 'hypothesis', 'hypothesises', 'hypothesea'], 0,
      'Greek loan nouns ending in -is change to -es: "hypotheses" (pronounced /haɪˈpɒθəsiːz/).', 'Academic Lexis C1'),
    q('noun_c1_3', 'C1', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the error: "This [A: data] [B: are] [C: completely] [D: inconclusive]."',
      ['A: data', 'B: are - in formal academic style, data can be plural (datum -> data), but with "This" singular demonstrative, there is a mismatch!'], 0,
      '"This" is singular while "are" is plural. Write either "These data are..." (formal) or "This data is..." (standard).', 'C1 Concord Nuance'),
    q('noun_c1_4', 'C1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "Jack and Jill\'s wedding was attended by three hundred guests."',
      ['Correct - shared/joint possession uses \'s only on the final name', 'Incorrect - both Jack and Jill must take \'s'], 0,
      'When two or more nouns jointly possess a single entity (their shared wedding), only the final noun takes the apostrophe-s.', 'Chicago Manual of Style C1'),
    q('noun_c1_5', 'C1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange this academic sentence: [phenomenon / fascinating / is / this / optical / rare / a]',
      ['This is a fascinating, rare optical phenomenon.', 'This optical phenomenon is a rare fascinating.', 'A fascinating optical phenomenon is rare this.', 'Fascinating optical phenomenon this is a rare.'], 0,
      'Demonstrative Subject (This) + Verb (is) + Predicate Noun Phrase (a fascinating, rare optical phenomenon).', 'C1 Advanced Word Order'),
    q('noun_c1_6', 'C1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which Latinate noun forms its plural in "-i"?',
      ['Radius', 'Index', 'Matrix', 'Apex'], 0,
      '"Radius" -> "radii" (plural in -i). "Index" becomes "indices", "matrix" becomes "matrices", "apex" becomes "apices".', 'Classical Plurals C1'),
    q('noun_c1_7', 'C1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The archaeological excavation unearthed the fossilized ______ of an unknown hominid.',
      ['remains', 'remain', 'remaining', 'remaindership'], 0,
      '"Remains" (meaning a corpse or ancient relics) is a pluralia tantum noun that occurs only in the plural.', 'Lexical Syntax C1'),
    q('noun_c1_8', 'C1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "They [A: examined] [B: three] [C: different] [D: phenomenons] in the particle accelerator."',
      ['A: examined', 'B: three', 'C: different', 'D: phenomenons'], 3,
      'The standard academic plural of "phenomenon" is "phenomena".', 'C1 Advanced Vocabulary'),
    q('noun_c1_9', 'C1', 'cloze', 'Cloze Test', 'Understanding',
      'The company was placed into ______ after failing to service its sovereign bond debts.',
      ['receivership', 'receivement', 'receivers', 'receivability'], 0,
      '"Receivership" is the specialized legal state where an independent receiver administers a bankrupt company.', 'C1 Business English'),
    q('noun_c1_10', 'C1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "John\'s and Mary\'s cars were parked in adjacent bays."',
      ['Correct - separate ownership requires \'s on each individual noun', 'Incorrect - only the second name can take \'s'], 0,
      'Because they own separate cars ("cars" plural), both individual owners must receive the genitive marker: "John\'s and Mary\'s cars".', 'C1 Genitive Mastery'),

    // C2 (10 items)
    q('noun_c2_1', 'C2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Which of the following is a zero-plural noun used in hunting and measurement jargon?',
      ['Brace', 'Glove', 'Shoe', 'Sleeve'], 0,
      '"Brace" (meaning a pair of game animals or birds) takes zero plural after numerals: "three brace of pheasants".', 'C2 Proficiency Lexicology'),
    q('noun_c2_2', 'C2', 'open_bracket', 'Open Bracket (Archaic Plural)', 'Producing',
      'Supply the zero plural in historical context: "The merchant traded five (head) ______ of prime Angus cattle."',
      ['head', 'heads', 'heades', 'headen'], 0,
      'In livestock terminology, "head" maintains an invariant zero plural after numbers: "five head of cattle".', 'Historical Syntax C2'),
    q('noun_c2_3', 'C2', 'checking_error', 'Checking Error', 'Explaining',
      'Find the syntactic defect: "The [A: barracks] [B: was] completely [C: renovated] last year, but now [D: they are] decaying again."',
      ['A: barracks', 'B: was', 'C: renovated', 'D: they are - shifted pronominal number!'], 3,
      'While "barracks" can be singular or plural, switching from singular "was" to plural "they are" within the same sentence violates concord consistency.', 'C2 Stylistic Concord'),
    q('noun_c2_4', 'C2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Reconstruct the formal legal clause: [jurisprudence / this / established / case / landmark / of / body / a / new]',
      ['This landmark case established a new body of jurisprudence.', 'A new body of jurisprudence established this landmark case.', 'Established this landmark case a new body of jurisprudence.', 'Of jurisprudence a new body established this landmark case.'], 0,
      'Subject (This landmark case) + Verb (established) + Direct Object (a new body of jurisprudence).', 'C2 Academic Prose'),
    q('noun_c2_5', 'C2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which noun exhibits morphological MUTATION PLURAL without an affix?',
      ['Foot (feet)', 'Bacterium (bacteria)', 'Formula (formulae)', 'Index (indices)'], 0,
      '"Foot" -> "feet" is an internal vowel mutation (umlaut/ablaut) inherited from Proto-Germanic.', 'Historical Linguistics C2'),
    q('noun_c2_6', 'C2', 'fill_blank', 'Fill in the Blank', 'Understanding',
      'The ambassador was granted ______ from diplomatic prosecution under the Vienna Convention.',
      ['immunity', 'immuneness', 'immunitude', 'immunitas'], 0,
      '"Immunity" is the precise formal legal noun.', 'C2 Diplomatic Register'),
    q('noun_c2_7', 'C2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The committee has reached consensus, but their individual motives remain opaque."',
      ['Correct - intentional conceptual shift from unified entity to distinct individuals', 'Incorrect - collective nouns can never shift agreement'], 0,
      'In sophisticated English, writers may deliberate move from singular (unified act) to plural (individual members\' mental states).', 'C2 Rhetorical Concord'),
    q('noun_c2_8', 'C2', 'cloze', 'Cloze Test', 'Understanding',
      'His prose was characterized by extraordinary ______, avoiding all verbose redundancies.',
      ['brevity', 'briefness', 'briefment', 'brevation'], 0,
      '"Brevity" is the high-register classical noun denoting concise expressiveness.', 'C2 Stylistics'),
    q('noun_c2_9', 'C2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "Every [A: means] [B: have] [C: been] [D: exhausted] in the search."',
      ['A: means', 'B: have - "Every" requires singular agreement!', 'C: been', 'D: exhausted'], 1,
      '"Every" modifies singular countables: "means" when preceded by "every" is grammatically singular and requires "has been".', 'C2 Traps'),
    q('noun_c2_10', 'C2', 'open_bracket', 'Open Bracket (Hebrew Loan Plural)', 'Producing',
      'What is the plural of the Hebrew loan noun "cherub" in traditional theological contexts?',
      ['cherubim', 'cherubs', 'cherubes', 'cherubites'], 0,
      'The traditional Biblical/theological plural of "cherub" is "cherubim" (or "seraph" -> "seraphim").', 'C2 Loan Morphology')
  );

  return items;
}

module.exports = { getNouns };
