// scripts/build_voice_clauses_sentences.js
// Topics 13, 14, 15: Active & Passive Voice, Clauses, Sentence Structures & Fragments
const { q } = require('./q_helper');

function getVoice() {
  const items = [];

  // ==========================================
  // TOPIC 13: VOICE - A1 (15 items)
  // ==========================================
  items.push(
    q('voice_a1_1', 'A1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Choose the correct passive verb: "English ______ all over the world."',
      ['is spoken', 'speaks', 'is speak', 'spoken'], 0,
      'Present passive formula: "is/are + past participle (V3)". "English is spoken".', 'British Council A1'),
    q('voice_a1_2', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "The car was washed by my father yesterday."',
      ['Correct - past passive "was + V3" with agent "by my father"', 'Incorrect'], 0,
      'Past passive: "was washed by...".', 'test-english A1'),
    q('voice_a1_3', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which sentence is in the PASSIVE voice?',
      ['The window was broken by the ball.', 'Tom kicked the red ball.', 'Anna opened the front door.', 'We ate lunch together.'], 0,
      '"was broken" has "be + past participle". The others are active.', 'Wordwall A1'),
    q('voice_a1_4', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'This delicious cake was ______ by my mother.',
      ['made', 'make', 'making', 'maked'], 0,
      'Passive requires past participle V3: "was made".', 'Cambridge A1'),
    q('voice_a1_5', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange into passive: [written / this book / was / by Mark Twain]',
      ['This book was written by Mark Twain.', 'Was written this book by Mark Twain.', 'By Mark Twain this book was written.', 'This book written was by Mark Twain.'], 0,
      'Subject (This book) + was + V3 (written) + by-agent.', 'Bamboozle A1'),
    q('voice_a1_6', 'A1', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the error: "The letters [A: are] [B: deliver] [C: every] [D: morning]."',
      ['B: deliver - should be V3 "delivered" in passive', 'A: are', 'C: every', 'D: morning'], 0,
      'Present passive needs V3: "are delivered".', 'Oxford A1'),
    q('voice_a1_7', 'A1', 'matching', 'Matching', 'Memory',
      'Match the active "They build houses" to its passive form:',
      ['Houses are built by them.', 'Houses were built by them.', 'Houses is built.', 'Houses are build.'], 0,
      'Present simple active -> Present simple passive: "Houses are built".', 'test-english A1'),
    q('voice_a1_8', 'A1', 'open_bracket', 'Open Bracket', 'Producing',
      'Fill in the bracket: "The museum (visit) ______ by thousands of tourists every summer."',
      ['is visited', 'visits', 'was visit', 'is visiting'], 0,
      'Present simple passive singular: "is visited".', 'British Council A1'),
    q('voice_a1_9', 'A1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Which preposition introduces the agent who performs the action in passive voice?',
      ['by', 'with', 'from', 'at'], 0,
      'We use "by" for the agent: "painted by Picasso".', 'VOA English A1'),
    q('voice_a1_10', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "The homework was did by Alex."',
      ['Incorrect - past participle of "do" is "done", not "did"', 'Correct'], 0,
      'Use V3: "was done", never *was did.', 'Cambridge A1'),
    q('voice_a1_11', 'A1', 'cloze', 'Cloze Test', 'Understanding',
      'Rice ______ in many Asian countries.',
      ['is grown', 'are grown', 'grows by', 'is grew'], 0,
      'Rice is uncountable (singular): "is grown".', 'test-english A1'),
    q('voice_a1_12', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which sentence is ACTIVE voice?',
      ['The chef prepared the salad.', 'The salad was prepared by the chef.', 'The room is cleaned every day.', 'The letters were sent on Monday.'], 0,
      '"The chef prepared" is active because the subject performs the verb.', 'Wordwall A1'),
    q('voice_a1_13', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'These photos ______ taken during our holiday in Rome.',
      ['were', 'was', 'is', 'did'], 0,
      'Plural subject "These photos" + past passive takes "were taken".', 'British Council A1'),
    q('voice_a1_14', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [found / the lost keys / were / in the garden]',
      ['The lost keys were found in the garden.', 'In the garden found were the lost keys.', 'Were found the lost keys in the garden.', 'The lost keys in the garden were found.'], 0,
      'Subject + were + V3 (found) + location.', 'Bamboozle A1'),
    q('voice_a1_15', 'A1', 'error_correction', 'Error Correction', 'Explaining',
      'Fix the sentence: "The movie was direct by Steven Spielberg."',
      ['The movie was directed by Steven Spielberg.', 'The movie direct by Steven Spielberg.', 'The movie was directs by Steven Spielberg.', 'The movie is direct by Steven Spielberg.'], 0,
      'Regular verb past participle requires -ed: "directed".', 'test-english A1')
  );

  // ==========================================
  // TOPIC 13: VOICE - A2 (15 items)
  // ==========================================
  items.push(
    q('voice_a2_1', 'A2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Change to passive: "Alexander Graham Bell invented the telephone."',
      ['The telephone was invented by Alexander Graham Bell.', 'The telephone is invented by Alexander Graham Bell.', 'The telephone were invented by Alexander Graham Bell.', 'Alexander Graham Bell was invented the telephone.'], 0,
      'Past simple active -> "was/were + V3": "was invented".', 'test-english A2'),
    q('voice_a2_2', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Seatbelts must ______ at all times during the flight.',
      ['be worn', 'worn', 'be wear', 'been worn'], 0,
      'Modal passive formula: "modal + be + V3" -> "must be worn".', 'British Council A2'),
    q('voice_a2_3', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "The ancient bridge can be seen from our hotel window."',
      ['Correct - modal passive "can + be + V3 (seen)"', 'Incorrect'], 0,
      'Correct modal passive construction: "can be seen".', 'Cambridge A2'),
    q('voice_a2_4', 'A2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "Millions of [A: emails] [B: are] [C: send] across [D: the world] every day."',
      ['C: send - should be past participle "sent"', 'A: emails', 'B: are', 'D: the world'], 0,
      '"send" is irregular: V3 is "sent" -> "are sent".', 'Oxford A2'),
    q('voice_a2_5', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which verb form is a valid passive infinitive?',
      ['to be cleaned', 'to being cleaned', 'to have clean', 'to be clean'], 0,
      'Passive infinitive is "to be + V3": "to be cleaned".', 'Wordwall A2'),
    q('voice_a2_6', 'A2', 'open_bracket', 'Open Bracket', 'Producing',
      'Turn into past passive: "The thief (catch) ______ by the police last night."',
      ['was caught', 'was catched', 'is caught', 'were caught'], 0,
      'Singular subject in past passive: "was caught".', 'test-english A2'),
    q('voice_a2_7', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [cannot / without a ticket / be / entered / the theater]',
      ['The theater cannot be entered without a ticket.', 'Without a ticket entered cannot be the theater.', 'Cannot be entered the theater without a ticket.', 'The theater cannot entered be without a ticket.'], 0,
      'Modal passive negative: Subject + cannot + be + V3 + prepositional phrase.', 'Bamboozle A2'),
    q('voice_a2_8', 'A2', 'matching', 'Matching', 'Memory',
      'Match the active modal "You should clean the room" to passive:',
      ['The room should be cleaned.', 'The room should cleaned.', 'The room must been cleaned.', 'The room was should clean.'], 0,
      '"should + clean" -> "should be cleaned".', 'Cambridge A2'),
    q('voice_a2_9', 'A2', 'cloze', 'Cloze Test', 'Understanding',
      'The Pyramids of Giza ______ thousands of years ago.',
      ['were built', 'was built', 'are built', 'built'], 0,
      'Plural subject + past time indicator = "were built".', 'VOA English A2'),
    q('voice_a2_10', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "My bicycle was stolen yesterday while I was in the shop."',
      ['Correct - agent is unknown so "by someone" is omitted', 'Incorrect'], 0,
      'In passive, when the agent is unknown or obvious, we omit "by...".', 'test-english A2'),
    q('voice_a2_11', 'A2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Which sentence correctly shows instrument with "with" vs agent with "by"?',
      ['The letter was written with a pen by John.', 'The letter was written by a pen with John.', 'The letter was written of a pen from John.', 'The letter was written at a pen by John.'], 0,
      '"by" = agent (person/creator); "with" = tool or instrument.', 'Oxford A2'),
    q('voice_a2_12', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which verb CANNOT be used in the passive voice?',
      ['Arrive (intransitive)', 'Paint (transitive)', 'Destroy (transitive)', 'Write (transitive)'], 0,
      'Intransitive verbs (no direct object like "arrive", "sleep", "happen") cannot form passive.', 'Wordwall A2'),
    q('voice_a2_13', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The package will ______ tomorrow morning.',
      ['be delivered', 'delivered', 'been delivered', 'be deliver'], 0,
      'Future passive: "will be delivered".', 'British Council A2'),
    q('voice_a2_14', 'A2', 'error_correction', 'Error Correction', 'Explaining',
      'Correct the error: "All the milk was drank by the cat."',
      ['All the milk was drunk by the cat.', 'All the milk were drank by the cat.', 'All the milk is drank by the cat.', 'All the milk was drinking by the cat.'], 0,
      'Past participle V3 of "drink" is "drunk" (drink, drank, drunk).', 'Cambridge A2'),
    q('voice_a2_15', 'A2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "Smoking [A: is] [B: not] [C: allow] [D: inside] the hospital."',
      ['C: allow - must be passive V3 "allowed"', 'A: is', 'B: not', 'D: inside'], 0,
      'Present passive negative: "is not allowed".', 'test-english A2')
  );

  // ==========================================
  // TOPIC 13: VOICE - B1 (15 items)
  // ==========================================
  items.push(
    q('voice_b1_1', 'B1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Choose the correct Present Continuous passive: "Right now, the road ______."',
      ['is being repaired', 'is repairing', 'is been repaired', 'has being repaired'], 0,
      'Present continuous passive formula: "is/are being + V3".', 'British Council B1'),
    q('voice_b1_2', 'B1', 'open_bracket', 'Open Bracket', 'Producing',
      'Convert to Past Continuous passive: "When I arrived, the dinner (prepare) ______."',
      ['was being prepared', 'was preparing', 'had being prepared', 'is being prepared'], 0,
      'Past continuous passive: "was being prepared".', 'test-english B1'),
    q('voice_b1_3', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "The report has already been submitted to the manager."',
      ['Correct - Present Perfect passive "has been + V3"', 'Incorrect'], 0,
      'Present Perfect passive: "has/have been + past participle".', 'Cambridge B1'),
    q('voice_b1_4', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which passive tense uses "being"?',
      ['Continuous / Progressive passives', 'Simple passives', 'Perfect passives', 'Modal simple passives'], 0,
      'Continuous passives (present & past) require the auxiliary "being".', 'Wordwall B1'),
    q('voice_b1_5', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [has / cancelled / due to rain / the flight / been]',
      ['The flight has been cancelled due to rain.', 'Due to rain the flight cancelled has been.', 'Has been cancelled the flight due to rain.', 'The flight cancelled has been due to rain.'], 0,
      'Subject + has been + V3 (cancelled) + reason.', 'Bamboozle B1'),
    q('voice_b1_6', 'B1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "The stadium [A: was] [B: being] [C: build] when the [D: storm] struck."',
      ['C: build - must be past participle "built"', 'A: was', 'B: being', 'D: storm'], 0,
      'Continuous passive needs V3: "was being built".', 'Oxford B1'),
    q('voice_b1_7', 'B1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Active: "Someone gave Sarah a promotion." Which is the more natural passive when focusing on Sarah?',
      ['Sarah was given a promotion.', 'A promotion was given Sarah.', 'Sarah was gave a promotion.', 'A promotion was gave to Sarah.'], 0,
      'With two objects (Sarah / promotion), person as subject is most natural: "Sarah was given a promotion."', 'British Council B1'),
    q('voice_b1_8', 'B1', 'cloze', 'Cloze Test', 'Understanding',
      'The new hospital ______ by the Prime Minister next month.',
      ['will be opened', 'is opened', 'will opened', 'will being opened'], 0,
      'Future passive: "will be opened".', 'test-english B1'),
    q('voice_b1_9', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'When we got back to the parking lot, our car ______ away.',
      ['had been towed', 'has been towed', 'was being tow', 'had towed'], 0,
      'Past Perfect passive for an action completed before another past event: "had been towed".', 'Cambridge B1'),
    q('voice_b1_10', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "The mystery happened last Tuesday evening." -> Can we say "The mystery was happened"?',
      ['Incorrect - "happen" is an intransitive verb and cannot be made passive', 'Correct'], 0,
      'Intransitive verbs like "happen, occur, die, remain" have no passive form.', 'test-english B1'),
    q('voice_b1_11', 'B1', 'matching', 'Matching', 'Memory',
      'Match the active tense to its passive auxiliary:\nPresent Perfect active (has/have written)',
      ['has/have been written', 'is being written', 'was written', 'will be written'], 0,
      'Present Perfect passive = has/have been + V3.', 'Cambridge B1'),
    q('voice_b1_12', 'B1', 'error_correction', 'Error Correction', 'Explaining',
      'Fix the sentence: "The dogs are take care of by my neighbor."',
      ['The dogs are taken care of by my neighbor.', 'The dogs are took care of by my neighbor.', 'The dogs are being take care by my neighbor.', 'The dogs were take cared of by my neighbor.'], 0,
      'Phrasal verbs keep their preposition in passive: "taken care of".', 'Oxford B1'),
    q('voice_b1_13', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which sentence contains a CAUSATIVE passive structure (have/get something done)?',
      ['I had my laptop repaired yesterday.', 'I repaired my laptop yesterday.', 'My laptop was repaired.', 'A technician repaired my laptop.'], 0,
      '"have/get something done" (had my laptop repaired) expresses arranging for someone else to do the action.', 'Wordwall B1'),
    q('voice_b1_14', 'B1', 'open_bracket', 'Open Bracket', 'Producing',
      'Conjugate: "Don\'t enter the laboratory; new experiments (conduct) ______ right now."',
      ['are being conducted', 'are conducted', 'have been conducted', 'were conducted'], 0,
      'Action in progress at speech time ("right now") + passive: "are being conducted".', 'British Council B1'),
    q('voice_b1_15', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [must / taken / immediately / action / be]',
      ['Action must be taken immediately.', 'Immediately action must taken be.', 'Be taken must action immediately.', 'Action taken must be immediately.'], 0,
      'Subject (Action) + modal (must) + be + V3 (taken) + adverb (immediately).', 'test-english B1')
  );

  // ==========================================
  // TOPIC 13: VOICE - B2 (15 items)
  // ==========================================
  items.push(
    q('voice_b2_1', 'B2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Choose the correct passive reporting structure: "People believe the criminal is hiding abroad."',
      ['The criminal is believed to be hiding abroad.', 'The criminal is believed hiding abroad.', 'It believes that the criminal is hiding abroad.', 'The criminal was believed to hide abroad.'], 0,
      'Personal passive reporting structure: "Subject + is believed + to-infinitive".', 'Cambridge B2'),
    q('voice_b2_2', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "It is widely reported that inflation has decreased this quarter."',
      ['Correct - impersonal passive reporting structure "It is + V3 + that-clause"', 'Incorrect'], 0,
      'Impersonal reporting structure: "It is reported / said / thought that...".', 'British Council B2'),
    q('voice_b2_3', 'B2', 'open_bracket', 'Open Bracket', 'Producing',
      'Supply modal perfect passive: "The package (should / deliver) ______ yesterday, but it never arrived."',
      ['should have been delivered', 'should be delivered', 'should had been delivered', 'should have delivered'], 0,
      'Modal perfect passive: "should have been + V3".', 'test-english B2'),
    q('voice_b2_4', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "The proposal [A: was] [B: objected] [C: by] several committee [D: members]."',
      ['B: objected - needs preposition "objected to by"', 'A: was', 'C: by', 'D: members'], 0,
      'Prepositional verbs retain their preposition in passive: "was objected TO by".', 'Oxford B2'),
    q('voice_b2_5', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which verb CANNOT be followed by a bare infinitive in the passive ("He was made to pay")?',
      ['Make (requires "to" in passive: "was made to do")', 'Help', 'Let (replaced by "allowed to")', 'Hear'], 0,
      'Active "They made him apologize" becomes passive "He was made TO apologize" (bare infinitive gains "to").', 'Wordwall B2'),
    q('voice_b2_6', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [the ancient artifacts / are / thought / to have been / stolen]',
      ['The ancient artifacts are thought to have been stolen.', 'Are thought the ancient artifacts to have been stolen.', 'To have been stolen are thought the ancient artifacts.', 'The ancient artifacts to have been stolen are thought.'], 0,
      'Subject + are thought + to have been + V3 (perfect passive infinitive).', 'Cambridge B2'),
    q('voice_b2_7', 'B2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Choose the passive form of "They let us leave early":',
      ['We were allowed to leave early.', 'We were let leave early.', 'We were let to leave early.', 'They were allowed to leave early.'], 0,
      '"Let" is not normally used in passive; replace with "be allowed to".', 'test-english B2'),
    q('voice_b2_8', 'B2', 'cloze', 'Cloze Test', 'Understanding',
      'The candidate resented ______ during her opening speech.',
      ['being interrupted', 'to be interrupted', 'having interrupted', 'interrupted'], 0,
      '"Resent" takes a gerund: passive gerund is "being + V3" (being interrupted).', 'British Council B2'),
    q('voice_b2_9', 'B2', 'matching', 'Matching', 'Memory',
      'Match the active "People say he is a billionaire" to impersonal passive:',
      ['It is said that he is a billionaire.', 'He is said being a billionaire.', 'It says he is a billionaire.', 'He was said a billionaire.'], 0,
      'Impersonal passive: "It is said that...".', 'Cambridge B2'),
    q('voice_b2_10', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'She hopes ______ for the promotion next month.',
      ['to be selected', 'to being selected', 'being selected', 'to select'], 0,
      '"Hope" is followed by a to-infinitive; passive to-infinitive is "to be selected".', 'Oxford B2'),
    q('voice_b2_11', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "The roof needs repaired immediately."',
      ['Incorrect - say "needs repairing" or "needs to be repaired"', 'Correct'], 0,
      '"Need" takes passive gerund ("needs repairing") or passive infinitive ("needs to be repaired").', 'test-english B2'),
    q('voice_b2_12', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which sentence uses a causative structure expressing an involuntary misfortune?',
      ['He had his passport stolen at the railway station.', 'He had his teeth cleaned by the dentist.', 'He had his car serviced yesterday.', 'He had the painter paint the fence.'], 0,
      '"had his passport stolen" describes an accident/misfortune, not an arranged service.', 'Wordwall B2'),
    q('voice_b2_13', 'B2', 'error_correction', 'Error Correction', 'Explaining',
      'Fix the sentence: "The building will have finished by the end of the year."',
      ['The building will have been finished by the end of the year.', 'The building will be finish by the end of the year.', 'The building will have finish by the end of the year.', 'The building has been finished by the end of the year.'], 0,
      'Future Perfect passive requires "will have been + V3": "will have been finished".', 'Cambridge B2'),
    q('voice_b2_14', 'B2', 'open_bracket', 'Open Bracket', 'Producing',
      'Supply the causative form: "I must (get / my eyes / test) ______ next week."',
      ['get my eyes tested', 'get my eyes test', 'get tested my eyes', 'get my eyes to test'], 0,
      'Causative: "get + object + V3" -> "get my eyes tested".', 'British Council B2'),
    q('voice_b2_15', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "He [A: is] [B: alleged] [C: to] [D: stole] the priceless jewelry."',
      ['D: stole - must be perfect infinitive "to have stolen"', 'A: is', 'B: alleged', 'C: to'], 0,
      'When the alleged action occurred before the present allegation, use "to have stolen".', 'Oxford B2')
  );

  // ==========================================
  // TOPIC 13: VOICE - C1 (10 items)
  // ==========================================
  items.push(
    q('voice_c1_1', 'C1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Select the most formal impersonal passive construction with a dummy "there":',
      ['There are said to be several ancient tombs buried beneath the sand.', 'It is said there are several ancient tombs beneath the sand.', 'Several ancient tombs are said to be there buried.', 'Ancient tombs say there are beneath the sand.'], 0,
      '"There + passive verb (are said) + to be" is a standard academic reporting structure.', 'Cambridge C1'),
    q('voice_c1_2', 'C1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "A sudden crisis was occurred during the diplomatic negotiations."',
      ['Incorrect - "occur" is unaccusative/intransitive and cannot be passivized', 'Correct'], 0,
      'Unaccusative verbs (occur, happen, fall, emerge) cannot appear in the passive voice.', 'Oxford C1'),
    q('voice_c1_3', 'C1', 'open_bracket', 'Open Bracket', 'Producing',
      'Transform using passive reporting: "They estimate that the company lost millions." -> "The company is estimated (lose) ______ millions."',
      ['to have lost', 'to lose', 'having lost', 'to have been lost'], 0,
      'The loss preceded the present estimation: use perfect infinitive "to have lost".', 'test-english C1'),
    q('voice_c1_4', 'C1', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the dangling participle caused by passive misuse: "[A: Walking into] [B: the lab], [C: the solution] was [D: spilled] by the student."',
      ['A: Walking into - dangling modifier: the solution was not walking!', 'B: the lab', 'C: the solution', 'D: spilled'], 0,
      'The subject of the main clause is "the solution", which makes the participle dangle.', 'British Council C1'),
    q('voice_c1_5', 'C1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [regarded / as / the theory / has / long been / obsolete]',
      ['The theory has long been regarded as obsolete.', 'Has long been regarded as obsolete the theory.', 'The theory regarded as obsolete has long been.', 'Long been the theory has regarded as obsolete.'], 0,
      'Subject + auxiliary + adverb + been + V3 + complement: "has long been regarded as obsolete".', 'Cambridge C1'),
    q('voice_c1_6', 'C1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which verb takes a passive with "with" rather than "by" to denote contents/coverage?',
      ['Cover (covered with snow)', 'Direct (directed by Nolan)', 'Write (written by Austen)', 'Paint (painted by Monet)'], 0,
      'Stative passives denoting coverage/filling take "with": "covered with snow", "filled with water".', 'Wordwall C1'),
    q('voice_c1_7', 'C1', 'cloze', 'Cloze Test', 'Understanding',
      'No one enjoys ______ like a child in public.',
      ['being spoken down to', 'to be spoken down', 'being spoken down', 'having spoken down'], 0,
      'Phrasal prepositional verb in passive gerund keeps all particles: "being spoken down to".', 'Oxford C1'),
    q('voice_c1_8', 'C1', 'matching', 'Matching', 'Memory',
      'Match the active structure to its causative equivalent:\n"I paid a specialist to translate the document."',
      ['I had the document translated by a specialist.', 'I was translated the document.', 'The document was having translated.', 'I got to translate the document.'], 0,
      'Causative passive: "have + object + V3".', 'Cambridge C1'),
    q('voice_c1_9', 'C1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The CEO was seen ______ the headquarters through the underground garage late at night.',
      ['to leave', 'leave', 'left', 'leaving to'], 0,
      'Verbs of perception take a to-infinitive (or -ing) in the passive: "was seen TO leave / leaving".', 'test-english C1'),
    q('voice_c1_10', 'C1', 'error_correction', 'Error Correction', 'Explaining',
      'Correct: "An important conclusion was arrived after three days of debates."',
      ['An important conclusion was arrived at after three days of debates.', 'An important conclusion was arrived to after three days of debates.', 'An important conclusion arrived at after three days of debates.', 'An important conclusion was arrive at after three days.'], 0,
      'The prepositional verb is "arrive at"; the passive MUST retain "at": "was arrived at".', 'Oxford C1')
  );

  // ==========================================
  // TOPIC 13: VOICE - C2 (10 items)
  // ==========================================
  items.push(
    q('voice_c2_1', 'C2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Why is passive voice preferred here: "The compound was heated to 100°C and subsequently titrated"?',
      ['To maintain scientific objectivity and focus on the experiment rather than the researcher', 'Because the active form is grammatically incorrect in English', 'Because intransitive verbs require passive voice in lab reports', 'To increase sentence length and lexical complexity'], 0,
      'In academic and scientific discourse, passive promotes an objective, process-oriented register.', 'Cambridge C2'),
    q('voice_c2_2', 'C2', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "A magnificent bouquet of roses was given me by the committee."',
      ['Correct - in formal British English, the indirect object can remain without "to" in passive', 'Incorrect'], 0,
      'In formal/literary British English, ditransitive passivization allows "was given me", though "was given to me" is more common.', 'Oxford C2'),
    q('voice_c2_3', 'C2', 'open_bracket', 'Open Bracket', 'Producing',
      'Form passive with perfect participle: "(Warn) ______ repeatedly of the impending avalanche, the climbers nonetheless proceeded up the ridge."',
      ['Having been warned', 'Having warned', 'Being warned', 'To have been warned'], 0,
      'Passive perfect participle clause: "Having been warned".', 'test-english C2'),
    q('voice_c2_4', 'C2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the subtle register violation: "The defendant [A: is alleged] [B: to have been] [C: being influenced] [D: by external coercion]."',
      ['C: being influenced - double continuous is ungrammatical; say "to have been influenced"', 'A: is alleged', 'B: to have been', 'D: by external coercion'], 0,
      'English does not combine continuous "being" with perfect passive infinitive: use "to have been influenced".', 'Cambridge C2'),
    q('voice_c2_5', 'C2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [been / the resolution / reached / has finally / upon / agreed]',
      ['The resolution agreed upon has finally been reached.', 'Has finally been reached the resolution agreed upon.', 'The resolution has finally been reached agreed upon.', 'Agreed upon has the resolution finally been reached.'], 0,
      'Prepositional passive modifier + main passive verb: "The resolution agreed upon has finally been reached."', 'Oxford C2'),
    q('voice_c2_6', 'C2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which verb exhibits "middle voice" (active morphology with passive meaning)?',
      ['The bread cuts easily.', 'The bread was cut by John.', 'John cut the bread.', 'The bread has been cut.'], 0,
      'Middle voice (ergative/mediopassive): active in form ("cuts easily"), but patient is subject.', 'Wordwall C2'),
    q('voice_c2_7', 'C2', 'cloze', 'Cloze Test', 'Understanding',
      'There is no record of the treaty ever ______ by the governing council.',
      ['having been ratified', 'to be ratified', 'been ratified', 'being had ratified'], 0,
      'Preposition "of" requires gerund; past passive action requires "having been ratified".', 'British Council C2'),
    q('voice_c2_8', 'C2', 'matching', 'Matching', 'Memory',
      'Match the discourse function of the passive to its example:\n"End-focus principle (placing heavy new info at the end)"',
      ['The theorem was discovered independently by a secluded mathematician from Kyoto.', 'It is believed that peace will prevail.', 'The book was sold out.', 'My bike was stolen.'], 0,
      'Passive allows long, heavy agents to be placed at the end for rhetorical emphasis (end-weight/end-focus).', 'Cambridge C2'),
    q('voice_c2_9', 'C2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Under no circumstances ______ to leave the premises without written clearance.',
      ['is any personnel to be permitted', 'any personnel is to be permitted', 'permitted is any personnel', 'any personnel to be permitted is'], 0,
      'Negative adverbial inversion + passive: "Under no circumstances IS any personnel TO BE PERMITTED...".', 'Oxford C2'),
    q('voice_c2_10', 'C2', 'error_correction', 'Error Correction', 'Explaining',
      'Correct: "The committee decided that he be conferred with the honorary doctorate."',
      ['The committee decided that he be conferred the honorary doctorate.', 'The committee decided that he conferred the honorary doctorate.', 'The committee decided that he was confer the honorary doctorate.', 'The committee decided that he been conferred with the doctorate.'], 0,
      '"Confer" in ditransitive passive takes a direct object without "with": "be conferred the honorary doctorate" (or "conferred upon him").', 'Cambridge C2')
  );

  return items;
}

function getClauses() {
  const items = [];

  // ==========================================
  // TOPIC 14: CLAUSES - A1 (15 items)
  // ==========================================
  items.push(
    q('clau_a1_1', 'A1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'What must EVERY clause contain?',
      ['A subject and a verb', 'A subject and a preposition', 'Only a noun', 'Two punctuation marks'], 0,
      'A clause is a group of words that contains both a subject and a predicate verb.', 'British Council A1'),
    q('clau_a1_2', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "Because it was raining." -> Is this a complete independent clause that can stand alone as a sentence?',
      ['Incorrect - it starts with "Because", making it a dependent clause', 'Correct'], 0,
      'A dependent clause cannot stand alone as a complete sentence; it is a fragment.', 'test-english A1'),
    q('clau_a1_3', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'I like the teacher ______ explains grammar clearly.',
      ['who', 'which', 'where', 'when'], 0,
      'Use "who" for people in relative clauses.', 'Cambridge A1'),
    q('clau_a1_4', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which relative pronoun refers to THINGS, not people?',
      ['Which', 'Who', 'Whom', 'Whoever'], 0,
      '"Which" refers to animals and objects.', 'Wordwall A1'),
    q('clau_a1_5', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [she was tired / went to bed / because / Sarah]',
      ['Sarah went to bed because she was tired.', 'Because she was tired Sarah went to bed.', 'Sarah because she was tired went to bed.', 'Went to bed Sarah because she was tired.'], 0,
      'Independent clause + dependent reason clause ("because she was tired").', 'Bamboozle A1'),
    q('clau_a1_6', 'A1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "This is [A: the laptop] [B: who] [C: I bought] [D: yesterday]."',
      ['B: who - "laptop" is an object, use "which" or "that"', 'A: the laptop', 'C: I bought', 'D: yesterday'], 0,
      'Use "which" or "that" for objects, never "who".', 'Oxford A1'),
    q('clau_a1_7', 'A1', 'matching', 'Matching', 'Memory',
      'Match the relative pronoun to its antecedent:\n"Where"',
      ['Places (e.g. the city where I was born)', 'People', 'Time', 'Possessions'], 0,
      '"Where" refers to places in relative clauses.', 'test-english A1'),
    q('clau_a1_8', 'A1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Choose the clause that can stand alone as a complete sentence:',
      ['She loves playing tennis.', 'Although she loves playing tennis.', 'When she loves playing tennis.', 'Because she loves playing tennis.'], 0,
      '"She loves playing tennis" has no subordinating conjunction and expresses a complete thought.', 'Cambridge A1'),
    q('clau_a1_9', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "The restaurant where we ate was very cheap."',
      ['Correct - "where we ate" is a relative clause modifying "restaurant"', 'Incorrect'], 0,
      'Correct use of relative adverb "where".', 'test-english A1'),
    q('clau_a1_10', 'A1', 'cloze', 'Cloze Test', 'Understanding',
      'I will call you when I ______ home.',
      ['arrive', 'will arrive', 'arrived', 'arriving'], 0,
      'Time clauses with "when" use present simple to refer to the future.', 'British Council A1'),
    q('clau_a1_11', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which word introduces a condition clause?',
      ['If', 'Because', 'Who', 'Which'], 0,
      '"If" introduces a conditional clause.', 'Wordwall A1'),
    q('clau_a1_12', 'A1', 'open_bracket', 'Open Bracket', 'Producing',
      'Combine into one sentence with "who": "I met a girl. She speaks four languages." -> "I met a girl (who) ______ four languages."',
      ['who speaks', 'who speak', 'which speaks', 'who she speaks'], 0,
      'Replace the subject pronoun "She" with "who": "who speaks".', 'Cambridge A1'),
    q('clau_a1_13', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'We stayed inside ______ the weather was cold and windy.',
      ['because', 'who', 'which', 'where'], 0,
      '"because" introduces an adverbial clause of reason.', 'VOA English A1'),
    q('clau_a1_14', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [if you study / will pass / the test / you / hard]',
      ['If you study hard, you will pass the test.', 'You will pass the test you study hard if.', 'If will pass the test, you study hard.', 'You study hard if you will pass the test.'], 0,
      'Conditional clause ("If you study hard") + main clause ("you will pass the test").', 'Bamboozle A1'),
    q('clau_a1_15', 'A1', 'error_correction', 'Error Correction', 'Explaining',
      'Fix the sentence: "The man which lives next door is a doctor."',
      ['The man who lives next door is a doctor.', 'The man where lives next door is a doctor.', 'The man whose live next door is a doctor.', 'The man which live next door is a doctor.'], 0,
      'For human beings, use "who" or "that", not "which".', 'test-english A1')
  );

  // ==========================================
  // TOPIC 14: CLAUSES - A2 (15 items)
  // ==========================================
  items.push(
    q('clau_a2_1', 'A2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Which sentence contains a DEFINING relative clause (essential information, no commas)?',
      ['The student who got the highest score won a scholarship.', 'Paris, which is the capital of France, is beautiful.', 'My father, who is 55, loves gardening.', 'Mr. Smith, whom I met yesterday, is very kind.'], 0,
      'Defining relative clauses identify which person/thing is meant and have NO commas.', 'Cambridge A2'),
    q('clau_a2_2', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'That is the artist ______ paintings are displayed in the national gallery.',
      ['whose', 'who\'s', 'which', 'who'], 0,
      'Use "whose" to show possession in relative clauses.', 'British Council A2'),
    q('clau_a2_3', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "That is the girl who\'s cat was lost."',
      ['Incorrect - "who\'s" means "who is" or "who has"; possession is "whose"', 'Correct'], 0,
      'Whose = possessive pronoun. Who\'s = contraction of "who is/has".', 'test-english A2'),
    q('clau_a2_4', 'A2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "We won\'t [A: start] the movie [B: until] [C: everyone] [D: will arrive]."',
      ['D: will arrive - time clauses with "until" take present simple "arrives"', 'A: start', 'B: until', 'C: everyone'], 0,
      'Time clauses (until, when, before, after) do not use "will"; use present tense.', 'Oxford A2'),
    q('clau_a2_5', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which word introduces an adverbial clause of CONCESSION?',
      ['Although', 'Because', 'Whenever', 'Since'], 0,
      '"Although" introduces contrast/concession.', 'Wordwall A2'),
    q('clau_a2_6', 'A2', 'open_bracket', 'Open Bracket', 'Producing',
      'Complete with "unless": "You will fail the exam (study) ______ hard."',
      ['unless you study', 'unless you will study', 'unless you don\'t study', 'unless you studied'], 0,
      '"Unless" means "if not" and is followed by affirmative verb in present simple: "unless you study".', 'Cambridge A2'),
    q('clau_a2_7', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [she was ill / went to work / although / Maria]',
      ['Although Maria was ill, she went to work.', 'Maria went to work was ill although.', 'Although went to work, Maria was ill.', 'Maria although was ill she went to work.'], 0,
      'Concession clause ("Although Maria was ill,") + main clause ("she went to work.").', 'Bamboozle A2'),
    q('clau_a2_8', 'A2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'When can the relative pronoun (who/which/that) be OMITTED in a defining relative clause?',
      ['When it is the object of the relative clause (e.g. "The book [that] I read")', 'When it is the subject of the clause', 'When the sentence is negative', 'Never in English'], 0,
      'Object relative pronouns can be omitted: "The book (which) I bought". Subject pronouns cannot ("The man who called").', 'British Council A2'),
    q('clau_a2_9', 'A2', 'cloze', 'Cloze Test', 'Understanding',
      'I know the man ______ you were talking to.',
      ['whom / who / that / (no pronoun)', 'where', 'whose', 'when'], 0,
      'When referring to an object person, who/whom/that or zero pronoun is possible.', 'test-english A2'),
    q('clau_a2_10', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "London, that is a big city, has many museums."',
      ['Incorrect - "that" cannot be used in non-defining relative clauses; use "which"', 'Correct'], 0,
      'In non-defining clauses (with commas), you MUST use "which" for things, never "that".', 'Cambridge A2'),
    q('clau_a2_11', 'A2', 'matching', 'Matching', 'Memory',
      'Match the clause function:\n"Why he left so suddenly is a secret."',
      ['Noun Clause (acting as subject of the sentence)', 'Adjective Clause', 'Adverb Clause', 'Independent Clause'], 0,
      '"Why he left so suddenly" answers "What?" and serves as the noun subject.', 'Oxford A2'),
    q('clau_a2_12', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which sentence contains a NON-DEFINING relative clause?',
      ['My brother, who lives in Tokyo, is visiting next week.', 'The dog that barked all night belongs to Dave.', 'Students who work hard get good grades.', 'The car which I rented broke down.'], 0,
      'Non-defining clauses add extra, non-essential information and are set off by commas.', 'Wordwall A2'),
    q('clau_a2_13', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'I won\'t go to the beach ______ it rains.',
      ['if', 'unless', 'though', 'despite'], 0,
      'Condition: "if it rains". ("unless it rains" would mean "I will go except if it rains").', 'test-english A2'),
    q('clau_a2_14', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [what / told me / I cannot believe / you]',
      ['I cannot believe what you told me.', 'What you told me I cannot believe.', 'I cannot what you told me believe.', 'You told me what I cannot believe.'], 0,
      'Subject + verb + noun clause object: "what you told me".', 'Bamboozle A2'),
    q('clau_a2_15', 'A2', 'error_correction', 'Error Correction', 'Explaining',
      'Fix the sentence: "The hotel which we stayed at it was very clean."',
      ['The hotel which we stayed at was very clean.', 'The hotel where we stayed at was very clean.', 'The hotel that we stayed at it was very clean.', 'The hotel which we stayed was very clean.'], 0,
      'Do not include the pronoun "it" because "which" already represents the object of "at".', 'Cambridge A2')
  );

  // ==========================================
  // TOPIC 14: CLAUSES - B1 (15 items)
  // ==========================================
  items.push(
    q('clau_b1_1', 'B1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Identify the type of dependent clause: "I believe [that honesty is the best policy]."',
      ['Noun clause (direct object of "believe")', 'Adjective / Relative clause', 'Adverb clause of condition', 'Independent coordinate clause'], 0,
      'The clause answers "What do I believe?" and functions as the noun object.', 'British Council B1'),
    q('clau_b1_2', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "Although it was freezing, but they went swimming."',
      ['Incorrect - double connector error; do not use both "Although" and "but"', 'Correct'], 0,
      'Use either "Although it was freezing, they went swimming" OR "It was freezing, but they went swimming".', 'test-english B1'),
    q('clau_b1_3', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'She asked me ______ I had ever visited Japan.',
      ['whether', 'that', 'what', 'which'], 0,
      'Indirect yes/no questions use "if" or "whether" to introduce a noun clause.', 'Cambridge B1'),
    q('clau_b1_4', 'B1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "My grandmother, [A: that] [B: turned 80] [C: last week], [D: is] still active."',
      ['A: that - non-defining clauses must use "who" for people, not "that"', 'B: turned 80', 'C: last week', 'D: is'], 0,
      '"That" is NEVER used in non-defining relative clauses (clauses with commas).', 'Oxford B1'),
    q('clau_b1_5', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which word introduces an adverb clause of PURPOSE?',
      ['So that', 'Because', 'Although', 'While'], 0,
      '"So that" (or "in order that") introduces an adverbial clause of purpose.', 'Wordwall B1'),
    q('clau_b1_6', 'B1', 'open_bracket', 'Open Bracket', 'Producing',
      'Combine using a reduced relative participle clause: "The woman who is talking to the manager is my aunt." -> "The woman (talk) ______ to the manager is my aunt."',
      ['talking', 'talked', 'talks', 'to talk'], 0,
      'Active relative clause reduces to present participle (-ing): "talking to the manager".', 'British Council B1'),
    q('clau_b1_7', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [she was looking for / what / she finally found]',
      ['She finally found what she was looking for.', 'What she was looking for she finally found.', 'She was looking for what she finally found.', 'She found finally what was she looking for.'], 0,
      'Subject + verb + nominal relative clause object: "what she was looking for".', 'Bamboozle B1'),
    q('clau_b1_8', 'B1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'In which sentence does the relative clause have "whose" functioning properly?',
      ['The author whose latest novel became a bestseller attended the gala.', 'The author who\'s latest novel became a bestseller attended the gala.', 'The author which latest novel became a bestseller attended the gala.', 'The author that his latest novel became a bestseller attended the gala.'], 0,
      '"whose latest novel" correctly marks possessive antecedent.', 'test-english B1'),
    q('clau_b1_9', 'B1', 'cloze', 'Cloze Test', 'Understanding',
      'The reason ______ he missed the flight was the heavy traffic.',
      ['why', 'which', 'where', 'whose'], 0,
      '"The reason why..." introduces a relative clause of cause/reason.', 'Cambridge B1'),
    q('clau_b1_10', 'B1', 'matching', 'Matching', 'Memory',
      'Match the clause connector to its relationship:\n"Whereas"',
      ['Contrast / Comparison', 'Reason / Cause', 'Time', 'Condition'], 0,
      '"Whereas" connects contrasting clauses (e.g. "He likes cats, whereas I prefer dogs").', 'Oxford B1'),
    q('clau_b1_11', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "Can you tell me where does the train station be?"',
      ['Incorrect - indirect question noun clause requires statement word order: "where the train station is"', 'Correct'], 0,
      'Noun clauses embedded in questions use statement order (Subject + Verb), not inversion.', 'test-english B1'),
    q('clau_b1_12', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which sentence contains an ADJECTIVE (relative) clause?',
      ['The shoes that I bought yesterday are too tight.', 'I wonder where she went.', 'Because it was late, we left.', 'That she passed the exam surprised everyone.'], 0,
      '"that I bought yesterday" modifies the noun "shoes", making it an adjective clause.', 'Wordwall B1'),
    q('clau_b1_13', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
      '______ hard he tried, he could not solve the puzzle.',
      ['However', 'Although', 'Despite', 'Even'], 0,
      '"However + adjective/adverb" introduces a concessive clause: "However hard he tried...".', 'Cambridge B1'),
    q('clau_b1_14', 'B1', 'error_correction', 'Error Correction', 'Explaining',
      'Correct: "I don\'t know where did he put the car keys."',
      ['I don\'t know where he put the car keys.', 'I don\'t know where did he puts the car keys.', 'I don\'t know where he did put the keys.', 'I don\'t know where puts he the car keys.'], 0,
      'In a noun clause, do not invert or use "did": "where he put the keys".', 'Oxford B1'),
    q('clau_b1_15', 'B1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "The package [A: sent] [B: from Berlin] [C: which] [D: it arrived] this morning was damaged."',
      ['D: it arrived - pronoun "it" is redundant with "which"', 'A: sent', 'B: from Berlin', 'C: which'], 0,
      '"which" serves as the subject of "arrived"; adding "it" is a resumptive pronoun error.', 'British Council B1')
  );

  // ==========================================
  // TOPIC 14: CLAUSES - B2 (15 items)
  // ==========================================
  items.push(
    q('clau_b2_1', 'B2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Identify the structure: "Having finished the report, Mark shut down his computer."',
      ['Participle clause expressing completed prior action', 'Finite adverbial clause', 'Noun clause in apposition', 'Relative non-defining clause'], 0,
      '"Having finished the report" is a non-finite perfect participle clause functioning adverbially.', 'Cambridge B2'),
    q('clau_b2_2', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "The suspect denied what he had committed any crime."',
      ['Incorrect - use "that", not "what": "denied THAT he had committed"', 'Correct'], 0,
      '"What" means "the thing that" and cannot replace the declarative complementizer "that".', 'test-english B2'),
    q('clau_b2_3', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The company fired twenty workers, ______ caused a massive strike.',
      ['which', 'that', 'what', 'who'], 0,
      'A sentential relative clause (referring back to the entire preceding clause) uses ", which".', 'British Council B2'),
    q('clau_b2_4', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "The committee [A: recommended] [B: that] the policy [C: is] [D: revised] immediately."',
      ['C: is - should be subjunctive "be revised"', 'A: recommended', 'B: that', 'D: revised'], 0,
      'Mandative subjunctive after "recommend that": "that the policy BE revised".', 'Oxford B2'),
    q('clau_b2_5', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [surprised everyone / that he resigned / so suddenly]',
      ['That he resigned so suddenly surprised everyone.', 'Surprised everyone that he resigned so suddenly.', 'So suddenly that he resigned surprised everyone.', 'That surprised everyone he resigned so suddenly.'], 0,
      'Noun clause acting as the complete sentence subject: "That he resigned so suddenly...".', 'Cambridge B2'),
    q('clau_b2_6', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which word introduces a clause of RESULT?',
      ['So... that (He was so tired that he fell asleep)', 'In order that', 'As though', 'Whereas'], 0,
      '"so... that" expresses result/consequence.', 'Wordwall B2'),
    q('clau_b2_7', 'B2', 'open_bracket', 'Open Bracket', 'Producing',
      'Reduce the relative clause: "Any employee who violates the safety rules will be dismissed." -> "Any employee (violate) ______ the safety rules will be dismissed."',
      ['violating', 'violated', 'violates', 'to violate'], 0,
      'Active relative clause reduces to present participle: "violating the safety rules".', 'test-english B2'),
    q('clau_b2_8', 'B2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Select the sentence with a correct preposition + relative pronoun structure:',
      ['The premise upon which this theory is built has been thoroughly tested.', 'The premise which upon this theory is built has been tested.', 'The premise that upon this theory is built has been tested.', 'The premise where upon this theory is built has been tested.'], 0,
      'In formal English, preposition precedes relative pronoun: "upon which". "That" cannot follow prepositions.', 'British Council B2'),
    q('clau_b2_9', 'B2', 'cloze', 'Cloze Test', 'Understanding',
      'She looked ______ she had seen a ghost.',
      ['as if', 'although', 'because', 'so that'], 0,
      '"as if" or "as though" introduces an adverbial clause of manner/comparison.', 'Cambridge B2'),
    q('clau_b2_10', 'B2', 'matching', 'Matching', 'Memory',
      'Match the reduced clause to its full clause equivalent:\n"Left alone in the dark, the child began to cry."',
      ['Because he was left alone in the dark...', 'While he was leaving alone...', 'If he leaves alone...', 'Although he had left alone...'], 0,
      'Past participle clause expresses passive cause: "Because he was left alone...".', 'Oxford B2'),
    q('clau_b2_11', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "Much as I respect your opinion, I cannot agree with your proposal."',
      ['Correct - "Much as..." is an advanced concessive clause meaning "Even though I respect..."', 'Incorrect'], 0,
      '"Much as + subject + verb" functions as an advanced concession clause.', 'test-english B2'),
    q('clau_b2_12', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'We visited three museums, none of ______ was open on Monday.',
      ['which', 'whom', 'what', 'them'], 0,
      'Quantifier + of which/whom introduces a non-defining relative clause: "none of which". (Note: "none of them" would require a semicolon or new sentence).', 'British Council B2'),
    q('clau_b2_13', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which sentence contains a WH-EVER clause functioning as an adverbial concession?',
      ['Whatever happens, stay calm and follow instructions.', 'Take whatever you want from the fridge.', 'I will agree to whatever terms you propose.', 'Whatever is on the desk belongs to the teacher.'], 0,
      'In "Whatever happens, stay calm", the clause means "No matter what happens" and modifies the main clause.', 'Wordwall B2'),
    q('clau_b2_14', 'B2', 'error_correction', 'Error Correction', 'Explaining',
      'Fix the sentence: "He is the professor whom taught me advanced linguistics."',
      ['He is the professor who taught me advanced linguistics.', 'He is the professor which taught me advanced linguistics.', 'He is the professor whose taught me advanced linguistics.', 'He is the professor what taught me advanced linguistics.'], 0,
      '"Whom" is an objective pronoun; here the pronoun is the subject of "taught", so use "who".', 'Cambridge B2'),
    q('clau_b2_15', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "The proposal [A: on that] [B: we spent] three months [C: was rejected] [D: by the board]."',
      ['A: on that - relative pronoun "that" cannot follow a preposition; use "on which"', 'B: we spent', 'C: was rejected', 'D: by the board'], 0,
      'Never place a preposition directly before relative "that"; say "on which".', 'Oxford B2')
  );

  // ==========================================
  // TOPIC 14: CLAUSES - C1 (10 items)
  // ==========================================
  items.push(
    q('clau_c1_1', 'C1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'What type of clause is "It was the marketing director who proposed the merger"?',
      ['A cleft clause (it-cleft) used for information focus', 'A reduced participial clause', 'A coordinate independent clause', 'A nominal appositive clause'], 0,
      'Cleft sentences divide a clause to highlight a specific element ("It was X that/who Y").', 'Cambridge C1'),
    q('clau_c1_2', 'C1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "Be that as it may, we must proceed according to the original protocol."',
      ['Correct - archaic fixed subjunctive clause expressing concession ("Even if that is true")', 'Incorrect'], 0,
      '"Be that as it may" is a recognized idiomatic subjunctive concessive clause.', 'Oxford C1'),
    q('clau_c1_3', 'C1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'What strikes me most about the research ______ the meticulous methodology.',
      ['is', 'are', 'being', 'were'], 0,
      'Wh-cleft clauses with "What" usually take a singular copular verb ("is") when the focus is an abstract concept.', 'British Council C1'),
    q('clau_c1_4', 'C1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "Hard [A: though] [B: did he work], he [C: failed to meet] the [D: deadline]."',
      ['B: did he work - inverted fronted adjective clauses with "though/as" do NOT take auxiliary inversion; say "Hard though he worked"', 'A: though', 'C: failed to meet', 'D: deadline'], 0,
      'In "Adjective + though/as + Subject + Verb", normal SVO order follows: "Hard though he worked".', 'Cambridge C1'),
    q('clau_c1_5', 'C1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [he said / what / bear in mind / you should]',
      ['You should bear in mind what he said.', 'What he said bear in mind you should.', 'Bear in mind you should what he said.', 'You should what he said bear in mind.'], 0,
      'Subject + verb + phrasal idiom + nominal relative clause object.', 'test-english C1'),
    q('clau_c1_6', 'C1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which sentence contains a VERBLESS clause?',
      ['When in Rome, do as the Romans do.', 'When you are in Rome, do as the Romans do.', 'Whenever you go to Rome, do as the Romans do.', 'If you should be in Rome, do as the Romans do.'], 0,
      '"When in Rome" has ellipsis of subject and copula ("When [you are] in Rome"), forming a verbless clause.', 'Wordwall C1'),
    q('clau_c1_7', 'C1', 'cloze', 'Cloze Test', 'Understanding',
      'The minister made the bold assertion ______ all public debt would be eliminated within five years.',
      ['that', 'which', 'what', 'whom'], 0,
      'Noun complement clause: "assertion that..." explains the content of the noun (not a relative clause!).', 'Oxford C1'),
    q('clau_c1_8', 'C1', 'matching', 'Matching', 'Memory',
      'Match the cleft structure:\n"Wh-cleft (Pseudo-cleft)"',
      ['What we need is decisive leadership.', 'It was Sarah who solved the riddle.', 'All I want is a cup of coffee.', 'The reason why he left is unknown.'], 0,
      '"What we need is..." is the canonical wh-cleft (pseudo-cleft) construction.', 'Cambridge C1'),
    q('clau_c1_9', 'C1', 'open_bracket', 'Open Bracket', 'Producing',
      'Invert the conditional clause without "if": "(If you should need) ______ any assistance, please contact the front desk."',
      ['Should you need', 'Had you need', 'Were you need', 'Do you need'], 0,
      'Conditional inversion: "If you should need" -> "Should you need".', 'British Council C1'),
    q('clau_c1_10', 'C1', 'error_correction', 'Error Correction', 'Explaining',
      'Fix: "The fact which the climate is warming is undeniable."',
      ['The fact that the climate is warming is undeniable.', 'The fact what the climate is warming is undeniable.', 'The fact whose climate is warming is undeniable.', 'The fact which climate is warming is undeniable.'], 0,
      '"that the climate is warming" is a noun complement clause defining the fact, not an adjective clause.', 'Oxford C1')
  );

  // ==========================================
  // TOPIC 14: CLAUSES - C2 (10 items)
  // ==========================================
  items.push(
    q('clau_c2_1', 'C2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Analyze the italicized construction: "The deliberations having concluded, the delegates signed the treaty."',
      ['An absolute clause (nominative absolute) with its own overt subject', 'A dangling participle modifier', 'A coordinated main clause with ellipsis', 'A relative clause of result'], 0,
      'An absolute clause has its own noun subject ("The deliberations") and a non-finite participle ("having concluded"), grammatically independent from the main clause.', 'Cambridge C2'),
    q('clau_c2_2', 'C2', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "Cost what it may, the expedition will proceed to the pole."',
      ['Correct - archaic optative/concessive subjunctive clause meaning "Whatever it may cost"', 'Incorrect'], 0,
      '"Cost what it may" is an idiomatic concessive subjunctive construction in high formal English.', 'Oxford C2'),
    q('clau_c2_3', 'C2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'She was reluctant to accept the award, ______ modesty was her defining trait.',
      ['for', 'so', 'although', 'despite'], 0,
      'Literary coordinating conjunction "for" introduces an explanatory clause of cause/reason.', 'British Council C2'),
    q('clau_c2_4', 'C2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "He will support [A: whoever] [B: the committee] [C: nominates] to [D: the council]."',
      ['A: whoever - should be objective "whomever" as the direct object of "nominates"', 'B: the committee', 'C: nominates', 'D: the council'], 0,
      'In rigorous formal C2 English, when the relative pronoun is the direct object of the subordinate verb, "whomever" is prescribed.', 'Cambridge C2'),
    q('clau_c2_5', 'C2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [she persevered / daunted though / by the obstacles / she was]',
      ['Daunted though she was by the obstacles, she persevered.', 'She persevered daunted though by the obstacles she was.', 'Though daunted she was by the obstacles, she persevered.', 'By the obstacles daunted though she was she persevered.'], 0,
      'Fronted participle complement clause: "Daunted though she was by the obstacles, she persevered."', 'Oxford C2'),
    q('clau_c2_6', 'C2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which construction exemplifies a "free relative clause" (nominal relative)?',
      ['I will give you whatever you desire.', 'I will give you the thing which you desire.', 'I will give you that which is yours.', 'I will give you everything that you desire.'], 0,
      '"whatever you desire" merges antecedent and relative pronoun into a single nominal constituent.', 'Wordwall C2'),
    q('clau_c2_7', 'C2', 'cloze', 'Cloze Test', 'Understanding',
      'Strange ______ it may seem, the ancient monument aligns precisely with the winter solstice.',
      ['as', 'like', 'so', 'though as'], 0,
      '"Adjective + as/though + subject + modal" is a classical concessive clause formula.', 'British Council C2'),
    q('clau_c2_8', 'C2', 'matching', 'Matching', 'Memory',
      'Match the clause type:\n"Come Monday, we must finalize the budget."',
      ['Subjunctive temporal clause (meaning "When Monday comes")', 'Conditional counterfactual', 'Defining relative clause', 'Noun predicate clause'], 0,
      '"Come Monday" is an inverted subjunctive temporal clause formula.', 'Cambridge C2'),
    q('clau_c2_9', 'C2', 'open_bracket', 'Open Bracket', 'Producing',
      'Form inverted counterfactual conditional: "(Had they known) ______ the truth, they would never have consented."',
      ['Had they known', 'If had they known', 'Were they to know', 'Did they know'], 0,
      'Third conditional inversion: "Had they known".', 'test-english C2'),
    q('clau_c2_10', 'C2', 'error_correction', 'Error Correction', 'Explaining',
      'Correct: "The professor with whom notes I studied received a Nobel prize."',
      ['The professor whose notes I studied received a Nobel prize.', 'The professor of whom notes I studied received a Nobel prize.', 'The professor which notes I studied received a Nobel prize.', 'The professor who\'s notes I studied received a Nobel prize.'], 0,
      'Possession of notes belonging to the professor requires the relative determiner "whose notes".', 'Oxford C2')
  );

  return items;
}

function getSentenceStructures() {
  const items = [];

  // ==========================================
  // TOPIC 15: SENTENCE STRUCTURES - A1 (15 items)
  // ==========================================
  items.push(
    q('sent_a1_1', 'A1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'What are the core elements of a standard English simple sentence?',
      ['Subject + Verb (+ Object / Complement)', 'Preposition + Conjunction', 'Only an adjective', 'Verb + Adverb only'], 0,
      'A basic sentence requires at least a Subject and a Verb: "Birds fly".', 'British Council A1'),
    q('sent_a1_2', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "Running quickly down the street." -> Is this a complete sentence?',
      ['Incorrect - it is a sentence fragment (missing subject and finite verb)', 'Correct'], 0,
      'A participial phrase without a subject or finite verb is a fragment.', 'test-english A1'),
    q('sent_a1_3', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'I like tea, ______ my brother prefers coffee.',
      ['but', 'because', 'so that', 'although'], 0,
      '"but" connects two contrasting independent clauses in a compound sentence.', 'Cambridge A1'),
    q('sent_a1_4', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which word is a coordinating conjunction (FANBOYS)?',
      ['And', 'Because', 'Although', 'While'], 0,
      'FANBOYS: For, And, Nor, But, Or, Yet, So.', 'Wordwall A1'),
    q('sent_a1_5', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange into standard order: [plays / my sister / piano / the / every evening]',
      ['My sister plays the piano every evening.', 'Plays my sister the piano every evening.', 'Every evening plays the piano my sister.', 'The piano plays my sister every evening.'], 0,
      'Subject (My sister) + Verb (plays) + Object (the piano) + Time expression (every evening).', 'Bamboozle A1'),
    q('sent_a1_6', 'A1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the fragment error: "[A: We stayed home.] [B: Because it rained] [C: all afternoon.] [D: It was cold.]"',
      ['B: Because it rained - dependent clause standing alone as a fragment', 'A: We stayed home.', 'C: all afternoon.', 'D: It was cold.'], 0,
      'Dependent clauses cannot stand alone with a period.', 'Oxford A1'),
    q('sent_a1_7', 'A1', 'matching', 'Matching', 'Memory',
      'Match the sentence type:\n"The sun rises in the east."',
      ['Simple Sentence (one independent clause)', 'Compound Sentence', 'Complex Sentence', 'Compound-Complex Sentence'], 0,
      'Contains one independent clause with a subject and verb.', 'test-english A1'),
    q('sent_a1_8', 'A1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Which sentence is a COMPOUND sentence?',
      ['Jack cooked dinner, and Jill washed the dishes.', 'Jack cooked dinner before Jill arrived.', 'Cooking dinner was fun.', 'Jack, who is a chef, cooked dinner.'], 0,
      'Two independent clauses joined by comma + coordinating conjunction "and".', 'Cambridge A1'),
    q('sent_a1_9', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "She woke up late, so she missed the morning bus."',
      ['Correct - compound sentence joined by comma and "so"', 'Incorrect'], 0,
      '"so" connects cause and result between two independent clauses.', 'test-english A1'),
    q('sent_a1_10', 'A1', 'cloze', 'Cloze Test', 'Understanding',
      'Do you want to walk, ______ shall we take a taxi?',
      ['or', 'because', 'so', 'although'], 0,
      '"or" connects two alternative clauses.', 'British Council A1'),
    q('sent_a1_11', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which is a COMPLETE sentence?',
      ['The baby is sleeping.', 'In the blue car.', 'After the heavy storm.', 'To learn English quickly.'], 0,
      '"The baby is sleeping" has a subject (The baby) and a finite verb (is sleeping).', 'Wordwall A1'),
    q('sent_a1_12', 'A1', 'open_bracket', 'Open Bracket', 'Producing',
      'Connect these two clauses into one compound sentence: "It was raining. We took an umbrella." -> "It was raining, (so) ______ an umbrella."',
      ['so we took', 'because we took', 'but we took', 'or we took'], 0,
      '"so" introduces the consequence/result.', 'Cambridge A1'),
    q('sent_a1_13', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'My father works in a bank, ______ my mother is a teacher.',
      ['and', 'because', 'although', 'if'], 0,
      '"and" adds corresponding information between two coordinate clauses.', 'VOA English A1'),
    q('sent_a1_14', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [tired / was / Tom / went to bed / he / early / so]',
      ['Tom was tired, so he went to bed early.', 'So Tom was tired he went to bed early.', 'Tom went to bed early so was he tired.', 'He went to bed early so Tom was tired.'], 0,
      'Clause 1 + comma + so + Clause 2.', 'Bamboozle A1'),
    q('sent_a1_15', 'A1', 'error_correction', 'Error Correction', 'Explaining',
      'Fix the word order: "Always she arrives at school early."',
      ['She always arrives at school early.', 'She arrives always at school early.', 'At school early she always arrives.', 'Always arrives she at school early.'], 0,
      'Frequency adverbs like "always" go between subject and main verb: "She always arrives".', 'test-english A1')
  );

  // ==========================================
  // TOPIC 15: SENTENCE STRUCTURES - A2 (15 items)
  // ==========================================
  items.push(
    q('sent_a2_1', 'A2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'What is a "comma splice"?',
      ['Joining two independent clauses with only a comma and no conjunction', 'Using a comma after a subordinating clause', 'Forgetting a period at the end of a sentence', 'Putting a comma before an adjective'], 0,
      'A comma splice occurs when two complete sentences are incorrectly glued together with only a comma.', 'Cambridge A2'),
    q('sent_a2_2', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "I love swimming, it is great exercise." -> Is this punctuation correct?',
      ['Incorrect - this is a comma splice error (needs semicolon, period, or "because/for")', 'Correct'], 0,
      'Two independent clauses cannot be joined by a comma alone.', 'test-english A2'),
    q('sent_a2_3', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Although the test was difficult, ______ passed with high scores.',
      ['everyone', 'but everyone', 'so everyone', 'and everyone'], 0,
      'Do NOT add "but" or "so" after an initial "Although" clause in English.', 'British Council A2'),
    q('sent_a2_4', 'A2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "[A: The alarm rang.] [B: But nobody] [C: woke up.] [D: Because they were exhausted.]"',
      ['D: Because they were exhausted. - fragment dependent clause', 'A: The alarm rang.', 'B: But nobody', 'C: woke up.'], 0,
      '"Because they were exhausted" is a dependent clause that needs to attach to a main clause.', 'Oxford A2'),
    q('sent_a2_5', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange into a complex sentence: [finished his homework / went outside / after / David / to play]',
      ['After David finished his homework, he went outside to play.', 'David finished his homework after he went outside to play.', 'Went outside to play after David finished his homework.', 'David after finished his homework went outside to play.'], 0,
      'Subordinate clause with comma + main clause.', 'Bamboozle A2'),
    q('sent_a2_6', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which sentence is a COMPLEX sentence (one independent clause + at least one dependent clause)?',
      ['When the bell rang, the students left the classroom.', 'The students packed their bags and left.', 'The bell rang, and the students left.', 'The bell rang loudly.'], 0,
      '"When the bell rang (dependent), the students left the classroom (independent)" is complex.', 'Wordwall A2'),
    q('sent_a2_7', 'A2', 'matching', 'Matching', 'Memory',
      'Match the coordinating conjunction:\n"Nor"',
      ['Negative alternative (e.g. neither A nor B)', 'Reason', 'Time', 'Concession'], 0,
      '"Nor" links negative coordinates (and triggers subject-auxiliary inversion).', 'test-english A2'),
    q('sent_a2_8', 'A2', 'open_bracket', 'Open Bracket', 'Producing',
      'Fix the comma splice: "I missed the train, I had to take a taxi." -> "I missed the train, (so) ______ take a taxi."',
      ['so I had to', 'because I had to', 'although I had to', 'while I had to'], 0,
      'Add coordinating conjunction "so" to fix the comma splice.', 'Cambridge A2'),
    q('sent_a2_9', 'A2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Where does the comma go when an adverbial dependent clause comes FIRST?',
      ['Immediately after the dependent clause (e.g. "Before you leave, lock the door.")', 'Between the subject and verb', 'At the very end of the sentence', 'No comma is ever used'], 0,
      'Introductory dependent clauses require a comma separating them from the independent clause.', 'British Council A2'),
    q('sent_a2_10', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "Lock the door before you leave." -> Does this require a comma before "before"?',
      ['No - when the dependent clause comes second, a comma is normally NOT used', 'Yes - always put a comma before "before"'], 0,
      'When the main clause comes first, no comma precedes the subordinate clause.', 'test-english A2'),
    q('sent_a2_11', 'A2', 'cloze', 'Cloze Test', 'Understanding',
      'The weather was freezing; ______, we enjoyed our hiking trip.',
      ['nevertheless', 'because', 'so', 'and'], 0,
      'A conjunctive adverb like "nevertheless / however" follows a semicolon and precedes a comma.', 'Oxford A2'),
    q('sent_a2_12', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which is a FUSED (RUN-ON) sentence error?',
      ['The sun set darkness covered the valley.', 'The sun set, and darkness covered the valley.', 'When the sun set, darkness covered the valley.', 'The sun set; darkness covered the valley.'], 0,
      '"The sun set darkness covered..." fuses two clauses together with no punctuation or conjunction.', 'Wordwall A2'),
    q('sent_a2_13', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Neither the manager ______ the assistants were present at the meeting.',
      ['nor', 'or', 'and', 'but'], 0,
      'Correlative conjunction pair: "Neither... nor".', 'Cambridge A2'),
    q('sent_a2_14', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [she didn\'t / she was hungry / eat anything / although]',
      ['Although she was hungry, she didn\'t eat anything.', 'She didn\'t eat anything although she was hungry.', 'Although she didn\'t eat anything, she was hungry.', 'She was hungry although she didn\'t eat anything.'], 0,
      'Introductory clause with comma: "Although she was hungry, she didn\'t eat anything."', 'Bamboozle A2'),
    q('sent_a2_15', 'A2', 'error_correction', 'Error Correction', 'Explaining',
      'Fix the comma splice: "He studied hard, he passed the exam."',
      ['He studied hard, so he passed the exam.', 'He studied hard he passed the exam.', 'He studied hard, but he passed the exam.', 'He studied hard, because he passed the exam.'], 0,
      'Add coordinating conjunction "so" (or replace comma with a semicolon / period).', 'test-english A2')
  );

  // ==========================================
  // TOPIC 15: SENTENCE STRUCTURES - B1 (15 items)
  // ==========================================
  items.push(
    q('sent_b1_1', 'B1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'What defines a COMPOUND-COMPLEX sentence?',
      ['At least two independent clauses and at least one dependent clause', 'One independent clause and two dependent clauses', 'Three independent clauses joined by colons', 'A sentence with two compound subjects'], 0,
      'Compound-complex = 2+ independent clauses + 1+ dependent clauses.', 'Cambridge B1'),
    q('sent_b1_2', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "Though Mitchell prefers watching documentaries, his brother loves science fiction films, and they often debate which movie to rent."',
      ['Correct - Compound-Complex: 1 dependent clause ("Though...") + 2 independent clauses', 'Incorrect'], 0,
      'Exemplifies a valid compound-complex structure.', 'British Council B1'),
    q('sent_b1_3', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The company had a record year; ______, the CEO distributed generous bonuses.',
      ['therefore', 'because', 'although', 'but'], 0,
      'Conjunctive adverb of result: semicolon + therefore + comma.', 'test-english B1'),
    q('sent_b1_4', 'B1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the parallel structure flaw: "She enjoys [A: swimming], [B: to hike in the mountains], and [C: riding] [D: her bicycle]."',
      ['B: to hike in the mountains - should be gerund "hiking" to maintain parallelism', 'A: swimming', 'C: riding', 'D: her bicycle'], 0,
      'Parallel structure requires identical grammatical forms in a series (swimming, hiking, riding).', 'Oxford B1'),
    q('sent_b1_5', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which word CANNOT be used with a semicolon and comma as a conjunctive adverb?',
      ['Because (subordinating conjunction)', 'However (conjunctive adverb)', 'Furthermore (conjunctive adverb)', 'Consequently (conjunctive adverb)'], 0,
      '"Because" is a subordinating conjunction, not a transitional conjunctive adverb.', 'Wordwall B1'),
    q('sent_b1_6', 'B1', 'open_bracket', 'Open Bracket', 'Producing',
      'Combine into parallel form: "The job requires dedication, (patience) ______, and being hardworking." -> "dedication, patience, and ______."',
      ['hard work', 'hardworking', 'to work hard', 'worked hard'], 0,
      'Parallel series of three nouns: dedication, patience, and hard work.', 'Cambridge B1'),
    q('sent_b1_7', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [however / the product / was high / the price / was exceptional]',
      ['The price was high; however, the product was exceptional.', 'The price was high however the product was exceptional.', 'However the price was high the product was exceptional.', 'The product was exceptional however the price was high.'], 0,
      'Independent clause + semicolon + however + comma + independent clause.', 'Bamboozle B1'),
    q('sent_b1_8', 'B1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Which punctuation mark joins two closely related independent clauses WITHOUT a coordinating conjunction?',
      ['Semicolon (;)', 'Comma (,)', 'Hyphen (-)', 'Apostrophe (\')'], 0,
      'A semicolon connects two independent clauses that are closely linked in meaning.', 'British Council B1'),
    q('sent_b1_9', 'B1', 'cloze', 'Cloze Test', 'Understanding',
      'Not only did the storm destroy the bridge, ______ it knocked down the power lines.',
      ['but also', 'and also', 'so that', 'or else'], 0,
      'Correlative pair: "Not only... but also...".', 'test-english B1'),
    q('sent_b1_10', 'B1', 'matching', 'Matching', 'Memory',
      'Match the sentence error to its remedy:\n"Comma splice (I woke up, it was noon)"',
      ['Add a coordinating conjunction (I woke up, and it was noon) or use a semicolon', 'Remove the subject', 'Delete the verb', 'Add another comma'], 0,
      'Fix comma splices with semicolon, period, or coordinating conjunction.', 'Oxford B1'),
    q('sent_b1_11', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "To prepare for the exam, flashcards were reviewed by David." -> Does this sentence contain a dangling modifier?',
      ['Yes - "To prepare for the exam" implies David, but the subject of the clause is "flashcards"', 'No - perfectly correct'], 0,
      'Dangling modifier: flashcards cannot prepare for an exam. Say: "To prepare for the exam, David reviewed flashcards."', 'Cambridge B1'),
    q('sent_b1_12', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which structure exhibits FAULTY parallelism?',
      ['He likes running, reading, and to swim.', 'He likes running, reading, and swimming.', 'He likes to run, to read, and to swim.', 'He likes to run, read, and swim.'], 0,
      '"running, reading, and to swim" mixes gerunds with an infinitive.', 'Wordwall B1'),
    q('sent_b1_13', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The flight was delayed; ______, we missed our connecting train in Zurich.',
      ['consequently', 'although', 'because', 'unless'], 0,
      '"consequently" signals logical result after a semicolon.', 'test-english B1'),
    q('sent_b1_14', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [neither / nor / the teacher / the students / were convinced]',
      ['Neither the teacher nor the students were convinced.', 'Nor the students neither the teacher were convinced.', 'The teacher neither nor the students were convinced.', 'Were convinced neither the teacher nor the students.'], 0,
      'Correlative subject structure: "Neither X nor Y were convinced."', 'Bamboozle B1'),
    q('sent_b1_15', 'B1', 'error_correction', 'Error Correction', 'Explaining',
      'Correct the dangling modifier: "Walking into the kitchen, the smoke alarm sounded."',
      ['When I walked into the kitchen, the smoke alarm sounded.', 'Walking into the kitchen, the alarm made sound.', 'The smoke alarm sounded walking into the kitchen.', 'Into the kitchen walking, the smoke alarm sounded.'], 0,
      'The smoke alarm was not walking into the kitchen; clarify the human agent.', 'Oxford B1')
  );

  // ==========================================
  // TOPIC 15: SENTENCE STRUCTURES - B2 (15 items)
  // ==========================================
  items.push(
    q('sent_b2_1', 'B2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Identify the inversion structure: "Seldom ______ such a breathtaking display of fireworks."',
      ['have I seen', 'I have seen', 'did I saw', 'I saw'], 0,
      'Negative frequency adverbs (Seldom, Rarely, Never) at the start of a sentence trigger inversion: auxiliary + subject + verb.', 'Cambridge B2'),
    q('sent_b2_2', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "No sooner had we stepped outside than the torrential downpour started."',
      ['Correct - "No sooner had... than..." inversion formula', 'Incorrect'], 0,
      '"No sooner" triggers inverted past perfect and is paired with "than".', 'British Council B2'),
    q('sent_b2_3', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Hardly had the meeting begun ______ the fire alarm rang.',
      ['when', 'than', 'then', 'that'], 0,
      '"Hardly... when" (or "Scarcely... when") is the required correlative pair.', 'test-english B2'),
    q('sent_b2_4', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "Not only [A: she speaks] [B: fluent Russian], but she [C: also] [D: writes] classical poetry."',
      ['A: she speaks - negative limiter "Not only" at start requires inversion: "does she speak"', 'B: fluent Russian', 'C: also', 'D: writes'], 0,
      '"Not only DOES SHE SPEAK..." is required by fronted negative inversion.', 'Oxford B2'),
    q('sent_b2_5', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [did / realize / the danger / little / they / they were in]',
      ['Little did they realize the danger they were in.', 'They realized little did the danger they were in.', 'Did they realize little the danger they were in.', 'The danger they were in little did they realize.'], 0,
      'Negative limiter "Little" + did + subject + bare infinitive: "Little did they realize...".', 'Bamboozle B2'),
    q('sent_b2_6', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which fronted phrase does NOT trigger auxiliary inversion?',
      ['In the corner stood a grandfather clock (locative full inversion, not auxiliary)', 'Under no circumstances should you...', 'Rarely have we witnessed...', 'At no time was the public in danger...'], 0,
      'Locative prepositional inversion moves the main verb directly ("stood a clock"), unlike negative auxiliary inversion.', 'Wordwall B2'),
    q('sent_b2_7', 'B2', 'open_bracket', 'Open Bracket', 'Producing',
      'Invert with "Never": "I have never seen such courage." -> "Never (see) ______ such courage."',
      ['have I seen', 'I have seen', 'did I saw', 'saw I'], 0,
      '"Never have I seen such courage."', 'Cambridge B2'),
    q('sent_b2_8', 'B2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'What is a "periodic sentence"?',
      ['A sentence where the main independent clause is held until the very end, building suspense', 'A sentence that repeats words at regular periods', 'A sentence that contains only periods and no commas', 'A run-on sentence that spans several lines'], 0,
      'In a periodic sentence, subordinate details come first and the main thought is delayed until the climax.', 'Oxford B2'),
    q('sent_b2_9', 'B2', 'cloze', 'Cloze Test', 'Understanding',
      'Only after reading the contract carefully ______ realize the hidden costs.',
      ['did he', 'he did', 'he had', 'was he'], 0,
      '"Only after..." fronted triggers subject-auxiliary inversion in the main clause: "did he realize".', 'British Council B2'),
    q('sent_b2_10', 'B2', 'matching', 'Matching', 'Memory',
      'Match the fronted inversion trigger:\n"Under no circumstances"',
      ['Negative restriction (e.g. Under no circumstances may students leave)', 'Locative inversion', 'Comparison', 'Purpose'], 0,
      '"Under no circumstances" requires immediate auxiliary inversion: "may you...", "should we...".', 'test-english B2'),
    q('sent_b2_11', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "Having been cooked for four hours, the guests relished the roast beef." -> Is there a dangling modifier?',
      ['Yes - "the guests" were not cooked for four hours!', 'No - perfectly clear'], 0,
      'The introductory participial modifier attaches to "the guests". Fix: "...the guests relished the roast beef, which had been cooked for four hours."', 'Cambridge B2'),
    q('sent_b2_12', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which sentence is a "cumulative (loose) sentence" (main clause first, followed by modifiers)?',
      ['The old mansion loomed on the hill, its windows dark and its wooden shutters rattling in the wind.', 'Because the windows were dark and the shutters rattled, the old mansion loomed.', 'When night fell, the old mansion loomed on the hill.', 'Hardly had night fallen when the mansion loomed.'], 0,
      'A cumulative sentence opens with the main clause and accumulates explanatory details.', 'Wordwall B2'),
    q('sent_b2_13', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'So intense ______ that the athletes had to take frequent hydration breaks.',
      ['was the heat', 'the heat was', 'had the heat been', 'is the heat'], 0,
      '"So + adjective" fronted triggers inversion: "So intense was the heat that...".', 'Oxford B2'),
    q('sent_b2_14', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [on no account / must / be / left unattended / this luggage]',
      ['On no account must this luggage be left unattended.', 'Must this luggage be left unattended on no account.', 'This luggage on no account must be left unattended.', 'On no account this luggage must be left unattended.'], 0,
      'Negative fronting: "On no account + modal must + subject + passive infinitive".', 'Bamboozle B2'),
    q('sent_b2_15', 'B2', 'error_correction', 'Error Correction', 'Explaining',
      'Fix the sentence: "Scarcely had she arrived than the phone rang."',
      ['Scarcely had she arrived when the phone rang.', 'Scarcely had she arrived then the phone rang.', 'Scarcely she had arrived when the phone rang.', 'Scarcely did she arrived when the phone rang.'], 0,
      '"Scarcely" pairs with "when", whereas "No sooner" pairs with "than".', 'Cambridge B2')
  );

  // ==========================================
  // TOPIC 15: SENTENCE STRUCTURES - C1 (10 items)
  // ==========================================
  items.push(
    q('sent_c1_1', 'C1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Analyze the rhetorical balance: "Ask not what your country can do for you; ask what you can do for your country." This is an example of:',
      ['Chiasmus / Antimetabole (reversal of grammatical structures in successive clauses)', 'Asyndeton only', 'Anacoluthon', 'Polysyndeton'], 0,
      'Chiasmus / antimetabole reverses identical words and concepts across parallel balanced clauses (AB - BA).', 'Cambridge C1'),
    q('sent_c1_2', 'C1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "Only by relentless experimentation were the scientists able to synthesize the unstable isotope."',
      ['Correct - "Only by + gerund" fronting triggers main clause auxiliary inversion', 'Incorrect'], 0,
      'Fronted restrictive adverbial phrase "Only by..." requires inversion: "were the scientists able".', 'Oxford C1'),
    q('sent_c1_3', 'C1', 'open_bracket', 'Open Bracket', 'Producing',
      'Construct a conditional inversion without "if": "(If it had not been for) ______ your steadfast support, I would have succumbed to despair."',
      ['Had it not been for', 'Were it not been for', 'Should it not be for', 'Had not it been for'], 0,
      'Unreal past conditional inversion: "Had it not been for...".', 'test-english C1'),
    q('sent_c1_4', 'C1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the error: "Not until [A: did she reach] the summit [B: did she realize] [C: how treacherous] the path [D: had been]."',
      ['A: did she reach - do NOT invert inside the "Not until" dependent clause; invert only the main clause ("did she reach" -> "she reached")', 'B: did she realize', 'C: how treacherous', 'D: had been'], 0,
      'In "Not until X, Y", only the main clause Y is inverted: "Not until she reached the summit did she realize...".', 'Cambridge C1'),
    q('sent_c1_5', 'C1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [the truth / to emerge / begins / only then]',
      ['Only then does the truth begin to emerge.', 'Only then the truth begins to emerge.', 'Begins the truth only then to emerge.', 'The truth only then does begin to emerge.'], 0,
      '"Only then" + auxiliary does + subject (the truth) + base verb (begin to emerge).', 'Oxford C1'),
    q('sent_c1_6', 'C1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which stylistic device omits conjunctions between coordinate clauses for dramatic pace ("I came, I saw, I conquered")?',
      ['Asyndeton', 'Polysyndeton', 'Litotes', 'Zeugma'], 0,
      'Asyndeton deliberately removes coordinating conjunctions to create rhythm and speed.', 'Wordwall C1'),
    q('sent_c1_7', 'C1', 'cloze', 'Cloze Test', 'Understanding',
      'Were the proposal ______ approved by the senate, severe budgetary constraints would follow.',
      ['to be', 'be', 'been', 'is'], 0,
      'Second conditional inversion with passive infinitive: "Were + subject + to be + V3".', 'British Council C1'),
    q('sent_c1_8', 'C1', 'matching', 'Matching', 'Memory',
      'Match the rhetorical sentence scheme:\n"Polysyndeton"',
      ['Deliberate repetition of multiple coordinating conjunctions for emotional weight', 'Omission of conjunctions', 'Reversal of clause order', 'Abrupt shift in syntactic construction mid-sentence'], 0,
      'Polysyndeton uses multiple conjunctions in close succession (e.g. "and... and... and...").', 'Cambridge C1'),
    q('sent_c1_9', 'C1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Such ______ that thousands queued overnight outside the stadium.',
      ['was the demand for tickets', 'the demand was for tickets', 'the demand for tickets was', 'was for tickets the demand'], 0,
      '"Such was + noun phrase + that-clause" is an inverted emphatic structure.', 'Oxford C1'),
    q('sent_c1_10', 'C1', 'error_correction', 'Error Correction', 'Explaining',
      'Correct: "No sooner we had closed the windows than the thunder roared."',
      ['No sooner had we closed the windows than the thunder roared.', 'No sooner we closed the windows than the thunder roared.', 'No sooner did we closed the windows than the thunder roared.', 'No sooner had we closed the windows when the thunder roared.'], 0,
      '"No sooner" at the start of a sentence requires inversion: "No sooner had we closed...".', 'test-english C1')
  );

  // ==========================================
  // TOPIC 15: SENTENCE STRUCTURES - C2 (10 items)
  // ==========================================
  items.push(
    q('sent_c2_1', 'C2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Identify the syntactic error in: "The architect designed a skyscraper, and which won several international awards."',
      ['Faulty coordination with "and which" (coordinating a relative clause to an independent clause without a preceding relative clause)', 'Comma splice', 'Dangling participle', 'Split infinitive'], 0,
      '"And which" cannot coordinate a relative clause directly to a main clause unless preceded by an existing parallel relative clause.', 'Cambridge C2'),
    q('sent_c2_2', 'C2', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "Gazing upon the ancient ruins, an overwhelming sense of reverence swept over the historian." -> Is this a dangling modifier?',
      ['Yes - the participial phrase modifies "an overwhelming sense of reverence", which cannot gaze upon ruins', 'No - perfectly acceptable in modern prose'], 0,
      'A dangling participle must logically attach to the immediate subject of the matrix clause. The historian did the gazing, not the sense of reverence.', 'Oxford C2'),
    q('sent_c2_3', 'C2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The treatise was profound in conception, lucid in exposition, and ______ in argumentation.',
      ['compelling', 'to compel', 'it compelled', 'having compelled'], 0,
      'Strict parallel tricolon of paired adjective-prepositional phrase structures: profound..., lucid..., compelling...', 'Cambridge C2'),
    q('sent_c2_4', 'C2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the syntactic disruption: "The minister started by [A: praising the workforce], [B: outlined new incentives], and [C: concluded] [D: with a tribute]."',
      ['B: outlined new incentives - unparallel structure following preposition "by"; should be "outlining new incentives"', 'A: praising the workforce', 'C: concluded', 'D: with a tribute'], 0,
      'Parallel coordination after preposition "by": "by praising..., outlining..., and concluding...".', 'Oxford C2'),
    q('sent_c2_5', 'C2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [the truth / conceal / he attempted / much as / was revealed / everything]',
      ['Much as he attempted to conceal the truth, everything was revealed.', 'Everything was revealed much as he attempted to conceal the truth.', 'To conceal the truth much as he attempted everything was revealed.', 'Much as everything was revealed he attempted to conceal the truth.'], 0,
      'Fronted concessive clause: "Much as he attempted to conceal the truth, everything was revealed."', 'test-english C2'),
    q('sent_c2_6', 'C2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which term describes an abrupt grammatical discontinuity where a sentence starts with one construction and shifts mid-stream ("Anacoluthon")?',
      ['Anacoluthon (syntactic fracture / lack of grammatical sequence)', 'Polysyndeton', 'Chiasmus', 'Tricolon'], 0,
      'Anacoluthon is an intentional or accidental syntactic fracture where the sentence abandons its original structure mid-way.', 'Wordwall C2'),
    q('sent_c2_7', 'C2', 'cloze', 'Cloze Test', 'Understanding',
      'Little ______ that the document would spark a worldwide revolution.',
      ['did the authors imagine', 'the authors imagined', 'had the authors imagine', 'the authors did imagine'], 0,
      'Negative polarity adverb "Little" triggers inversion: "did the authors imagine".', 'British Council C2'),
    q('sent_c2_8', 'C2', 'matching', 'Matching', 'Memory',
      'Match the advanced structural phenomenon:\n"Gapping (Syntactic Ellipsis)"',
      ['Omission of identical repeated verbs in coordinate clauses (e.g. "Paul visited Rome, and Mary, Venice")', 'Duplication of auxiliaries', 'Fronting of objects', 'Inversion of tense markers'], 0,
      'Gapping deletes the lexical verb in the second coordinate clause when it matches the first.', 'Cambridge C2'),
    q('sent_c2_9', 'C2', 'open_bracket', 'Open Bracket', 'Producing',
      'Invert negative conditional clause: "(Were it not for) ______ his prompt intervention, the venture would have collapsed."',
      ['Were it not for', 'If it were not', 'Had it not for', 'Should it not be for'], 0,
      'Second conditional inversion: "Were it not for...".', 'Oxford C2'),
    q('sent_c2_10', 'C2', 'error_correction', 'Error Correction', 'Explaining',
      'Correct the faulty coordination: "He is a scholar of great renown and who has published extensively in peer-reviewed journals."',
      ['He is a scholar who possesses great renown and who has published extensively.', 'He is a scholar of great renown and published extensively.', 'He is a scholar of great renown whom has published extensively.', 'He is a scholar having great renown and which published extensively.'], 0,
      'To coordinate with "and who...", the preceding element must also be a relative clause ("who possesses... and who has published...").', 'Cambridge C2')
  );

  return items;
}

module.exports = {
  getVoice,
  getClauses,
  getSentenceStructures
};
