// scripts/build_adverbs_adjectives.js
// Adverbs and Adjectives (Topics 4 & 5)
const { q } = require('./q_helper');

function getAdverbs() {
  const items = [];
  // A1 (15 items)
  items.push(
    q('adv_a1_1', 'A1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Which word is an adverb of manner: "She sings ______."',
      ['beautiful', 'beautifully', 'beauty', 'beautify'], 1,
      '"Beautifully" is an adverb describing how she sings (verb + -ly).', 'British Council A1'),
    q('adv_a1_2', 'A1', 'open_bracket', 'Open Bracket (Adverb Formation)', 'Producing',
      'Change the adjective into an adverb: "He drives very (careful) ______."',
      ['carefully', 'careful', 'carefulness', 'carefuly'], 0,
      'Regular adverbs of manner add -ly to the adjective: "carefully".', 'test-english A1'),
    q('adv_a1_3', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "They always are happy to see us."',
      ['Correct', 'Incorrect - frequency adverbs follow the verb "to be" ("They are always happy")'], 1,
      'Adverbs of frequency follow the verb "be": "They ARE ALWAYS happy".', 'Cambridge A1'),
    q('adv_a1_4', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which word is an ADVERB OF TIME?',
      ['Yesterday', 'Quickly', 'Quietly', 'Slowly'], 0,
      '"Yesterday" tells when an action happened (time). Quickly, quietly, slowly tell how (manner).', 'Wordwall A1'),
    q('adv_a1_5', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Please speak ______; the baby is sleeping.',
      ['quietly', 'quiet', 'quietness', 'more quiet'], 0,
      'The verb "speak" is modified by the adverb of manner "quietly".', 'VOA English A1'),
    q('adv_a1_6', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [never / he / late / is / school / for]',
      ['He is never late for school.', 'He never is late for school.', 'Late for school is he never.', 'Never he is late for school.'], 0,
      'Subject (He) + Verb be (is) + Frequency adverb (never) + Complement (late for school).', 'Bamboozle A1'),
    q('adv_a1_7', 'A1', 'checking_error', 'Checking Error', 'Explaining',
      'Find the mistake: "She [A: speaks] [B: French] [C: very] [D: fluent]."',
      ['A: speaks', 'B: French', 'C: very', 'D: fluent'], 3,
      '"Speaks" requires an adverb: "fluently", not adjective "fluent".', 'Oxford A1'),
    q('adv_a1_8', 'A1', 'matching', 'Matching', 'Memory',
      'Match the adjective "fast" with its adverb form:',
      ['fastly', 'fast', 'fasterly', 'fasting'], 1,
      '"Fast" is a flat adverb; its adverb form is identical to the adjective: "He runs fast".', 'Elementary Adverbs'),
    q('adv_a1_9', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "He worked very hardly on the farm yesterday."',
      ['Correct', 'Incorrect - "hard" is the adverb meaning with effort; "hardly" means almost not'], 1,
      '"Hard" means with great energy; "hardly" means barely/almost not at all.', 'British Council A1'),
    q('adv_a1_10', 'A1', 'open_bracket', 'Open Bracket', 'Producing',
      'Turn the adjective in brackets into an adverb: "The children played (happy) ______ in the park."',
      ['happily', 'happyly', 'happifully', 'happiness'], 0,
      'Adjectives ending in consonant + y change "y" to "i" before adding -ly: "happily".', 'Spelling Rules A1'),
    q('adv_a1_11', 'A1', 'cloze', 'Cloze Test', 'Understanding',
      'I ______ drink tea in the morning; it is my daily routine.',
      ['usually', 'never', 'rarely', 'seldom'], 0,
      '"Usually" indicates habitual action matching "daily routine".', 'test-english A1'),
    q('adv_a1_12', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which word ending in -ly is an ADJECTIVE (not an adverb)?',
      ['Friendly', 'Slowly', 'Quickly', 'Easily'], 0,
      '"Friendly" describes a noun (e.g., "a friendly teacher") and is an adjective, not an adverb.', 'Wordwall A1'),
    q('adv_a1_13', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The train arrived ______ at the platform.',
      ['safely', 'safe', 'safeness', 'safer'], 0,
      '"Arrived" is modified by the adverb "safely".', 'VOA English A1'),
    q('adv_a1_14', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [outside / raining / heavily / it / is]',
      ['It is raining heavily outside.', 'It heavily is raining outside.', 'Raining heavily outside is it.', 'Outside it raining is heavily.'], 0,
      'Subject (It) + Verb (is raining) + Manner (heavily) + Place (outside).', 'Syntax A1'),
    q('adv_a1_15', 'A1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "He [A: did] [B: very] [C: good] on his [D: English exam]."',
      ['A: did', 'B: very', 'C: good', 'D: English exam'], 2,
      'Modify the verb "did" with adverb "well", not adjective "good".', 'Good vs Well A1')
  );

  // A2 (15 items)
  items.push(
    q('adv_a2_1', 'A2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Choose the correct position for "enough": "He is not ______ to join the police force."',
      ['old enough', 'enough old', 'too old', 'enough older'], 0,
      '"Enough" follows adjectives and adverbs: "old enough".', 'test-english A2'),
    q('adv_a2_2', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The coffee was ______ hot to drink immediately; I had to wait ten minutes.',
      ['too', 'very', 'enough', 'much'], 0,
      '"Too + adjective + to-infinitive" expresses an excessive degree preventing an action.', 'Cambridge A2'),
    q('adv_a2_3', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "She arrived lately to the conference because of heavy rain."',
      ['Correct', 'Incorrect - "late" means after scheduled time; "lately" means recently'], 1,
      '"Late" means unpunctual. "Lately" means recently.', 'British Council A2'),
    q('adv_a2_4', 'A2', 'open_bracket', 'Open Bracket (Comparative Adverb)', 'Producing',
      'Supply the comparative adverb: "Can you please speak (slow) ______ so I can understand?"',
      ['more slowly', 'slowlier', 'slowly', 'most slowly'], 0,
      'Adverbs ending in -ly form their comparative with "more": "more slowly".', 'Comparative Adverbs A2'),
    q('adv_a2_5', 'A2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the mistake: "She [A: plays] the violin [B: more better] [C: than] her [D: brother]."',
      ['A: plays', 'B: more better', 'C: than', 'D: brother'], 1,
      'Double comparative is wrong: "better", not "more better".', 'Double Comparatives A2'),
    q('adv_a2_6', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which adverb is an ADVERB OF DEGREE?',
      ['Extremely', 'Yesterday', 'Outside', 'Daily'], 0,
      '"Extremely" indicates intensity/degree. Yesterday is time, outside is place, daily is frequency.', 'Wordwall A2'),
    q('adv_a2_7', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [quite / the / test / difficult / was]',
      ['The test was quite difficult.', 'The test quite was difficult.', 'Quite difficult was the test.', 'Was the test quite difficult.'], 0,
      'Subject (The test) + Verb (was) + Adverb of degree (quite) + Adjective (difficult).', 'Syntax A2'),
    q('adv_a2_8', 'A2', 'matching', 'Matching', 'Understanding',
      'Match the degree adverb with its meaning: "almost" ->',
      ['Nearly, but not completely', 'Exceedingly high', 'In an unhurried way', 'At no time'], 0,
      '"Almost" indicates approximation / nearly completed.', 'test-english A2'),
    q('adv_a2_9', 'A2', 'cloze', 'Cloze Test', 'Understanding',
      'I haven\'t seen my former classmate ______; I wonder where he lives now.',
      ['lately', 'late', 'later', 'latest'], 0,
      '"Lately" means recently in the period leading up to the present.', 'Oxford A2'),
    q('adv_a2_10', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "Fortunately, everyone escaped the burning building unhurt."',
      ['Correct - "Fortunately" is a sentence adverb commenting on the whole event', 'Incorrect - sentence adverbs cannot stand at the beginning'], 0,
      'Sentence adverbs like "fortunately" correctly stand at the beginning of a clause.', 'Sentence Adverbs A2'),
    q('adv_a2_11', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The athlete ran ______ fast that nobody could overtake him.',
      ['so', 'such', 'too', 'very'], 0,
      '"So + adverb + that-clause": "ran so fast that...".', 'Degree Patterns A2'),
    q('adv_a2_12', 'A2', 'open_bracket', 'Open Bracket', 'Producing',
      'Form the adverb from "early": "He arrived (early) ______ than anyone else."',
      ['earlier', 'more early', 'more earlier', 'earliest'], 0,
      '"Early" forms comparative "earlier".', 'Irregular Comparatives A2'),
    q('adv_a2_13', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which word functions as BOTH an adjective and an adverb without -ly?',
      ['Hard', 'Careful', 'Slowly', 'Quick'], 0,
      '"Hard" is both an adjective ("hard test") and adverb ("work hard").', 'Flat Adverbs A2'),
    q('adv_a2_14', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Assemble: [fluently / speaks / three / she / languages]',
      ['She speaks three languages fluently.', 'She speaks fluently three languages.', 'Fluently she speaks three languages.', 'Three languages she speaks fluently.'], 0,
      'Standard position for adverb of manner is after the direct object: "speaks three languages fluently".', 'Word Order A2'),
    q('adv_a2_15', 'A2', 'checking_error', 'Checking Error', 'Explaining',
      'Find the mistake: "He [A: is] [B: enough strong] to [C: lift] that heavy [D: box]."',
      ['A: is', 'B: enough strong', 'C: lift', 'D: box'], 1,
      '"Enough" follows adjectives: "strong enough", not "enough strong".', 'Enough Placement A2')
  );

  // B1 (15 items)
  items.push(
    q('adv_b1_1', 'B1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Choose the sentence with correct subject-auxiliary inversion after a negative adverb:',
      ['Seldom have I seen such an awe-inspiring vista.', 'Seldom I have seen such an vista.', 'Seldom I did see such an vista.', 'Seldom saw I such an vista.'], 0,
      'When negative or restrictive adverbs (seldom, rarely, never) front a clause, inversion occurs: "Seldom have I seen".', 'Cambridge B1'),
    q('adv_b1_2', 'B1', 'open_bracket', 'Open Bracket', 'Producing',
      'Supply the inverted auxiliary: "Rarely (do / does) ______ she attend public receptions these days."',
      ['does', 'do', 'is', 'did'], 0,
      'Fronted "Rarely" with third-person singular "she" takes auxiliary "does": "Rarely does she attend".', 'Inversion B1'),
    q('adv_b1_3', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "He has finished almost his homework."',
      ['Correct', 'Incorrect - "almost" sits immediately before the word it modifies ("almost finished his homework")'], 1,
      'Focusing adverbs like "almost" immediately precede the verb/constituent modified: "has almost finished".', 'Focusing Adverbs B1'),
    q('adv_b1_4', 'B1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "Never [A: in my life] [B: I had] [C: experienced] such [D: terrifying turbulence]."',
      ['A: in my life', 'B: I had', 'C: experienced', 'D: terrifying turbulence'], 1,
      'Negative fronting requires inversion: "Never in my life HAD I experienced...".', 'Negative Inversion B1'),
    q('adv_b1_5', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The proposal was rejected ______ on financial grounds; the committee liked the design.',
      ['purely', 'pure', 'pureness', 'in pure'], 0,
      '"Purely" is a limiting/focusing adverb meaning "solely / strictly".', 'Focusing Adverbs B1'),
    q('adv_b1_6', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which adverb triggers subject-auxiliary inversion when placed at the beginning of a clause?',
      ['Hardly', 'Usually', 'Frequently', 'Obviously'], 0,
      'Negative/restrictive adverbs like "Hardly", "Scarcely", "Seldom", "Never" trigger inversion.', 'Inversion Triggers B1'),
    q('adv_b1_7', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Reconstruct: [have / rarely / heard / I / such / nonsense]',
      ['Rarely have I heard such nonsense.', 'Rarely I have heard such nonsense.', 'I have rarely such nonsense heard.', 'Such nonsense rarely have I heard.'], 0,
      'Fronted negative adverb (Rarely) + Auxiliary (have) + Subject (I) + Verb (heard) + Object (such nonsense).', 'Word Order B1'),
    q('adv_b1_8', 'B1', 'cloze', 'Cloze Test', 'Understanding',
      'The team worked ______ through the night to finish the architectural model.',
      ['tirelessly', 'tiringly', 'tiredly', 'tiresome'], 0,
      '"Tirelessly" means without resting or giving up.', 'Adverb Collocations B1'),
    q('adv_b1_9', 'B1', 'matching', 'Matching', 'Understanding',
      'Match the discourse adverb: "Frankly" ->',
      ['Speaking honestly and directly', 'In an accidental manner', 'Without any delay', 'At an earlier time'], 0,
      '"Frankly" is an evaluative stance adverb meaning "honestly speaking".', 'Stance Adverbs B1'),
    q('adv_b1_10', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "She definitely has been practicing the piano every afternoon."',
      ['Correct in informal speech; in strict grammar, mid-position adverbs sit after the first auxiliary ("has definitely been")', 'Completely unacceptable'], 0,
      'Mid-position adverbs normally sit after the first auxiliary verb: "has definitely been practicing".', 'Adverb Placement B1'),
    q('adv_b1_11', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The patient is ______ recovering from the surgical procedure.',
      ['gradually', 'gradual', 'graduality', 'in gradual'], 0,
      'Modify the continuous verb "recovering" with the manner adverb "gradually".', 'B1 Vocabulary'),
    q('adv_b1_12', 'B1', 'checking_error', 'Checking Error', 'Explaining',
      'Find the mistake: "She speaks [A: English] [B: very well], but she [C: hardly speaks] [D: no Spanish]."',
      ['A: English', 'B: very well', 'C: hardly speaks', 'D: no Spanish'], 3,
      '"Hardly" is already negative; double negation is incorrect: say "hardly speaks ANY Spanish".', 'Double Negatives B1'),
    q('adv_b1_13', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which word is a CONJUNCTIVE adverb (sentence connector)?',
      ['However', 'Because', 'Although', 'While'], 0,
      '"However" is a conjunctive adverb. Because, although, and while are subordinating conjunctions.', 'Connectors B1'),
    q('adv_b1_14', 'B1', 'open_bracket', 'Open Bracket', 'Producing',
      'Form the adverb from "extreme": "It was an (extreme) ______ difficult problem to solve."',
      ['extremely', 'extremeful', 'extreming', 'extremity'], 0,
      'Adverb modifying the adjective "difficult" is "extremely".', 'Degree Modifiers B1'),
    q('adv_b1_15', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Assemble: [had / no / started / sooner / rain / the / left / than / we]',
      ['No sooner had we left than the rain started.', 'No sooner we had left than the rain started.', 'Than we had left no sooner the rain started.', 'The rain started no sooner had we left than.'], 0,
      'Correlative inversion: "No sooner had we left than the rain started."', 'Correlative Inversion B1')
  );

  // B2 (15 items)
  items.push(
    q('adv_b2_1', 'B2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Which adverb correctly intensifies the NON-GRADABLE adjective "exhausted"?',
      ['utterly', 'very', 'fairly', 'a bit'], 0,
      'Non-gradable/extreme adjectives pair with totalizing adverbs like "utterly", "completely", or "absolutely" (not "very").', 'Oxford B2'),
    q('adv_b2_2', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Little ______ that the decision would alter the course of his entire life.',
      ['did he know', 'he knew', 'he did know', 'knew he'], 0,
      'Fronted negative/restrictive "Little" triggers subject-auxiliary inversion: "Little did he know".', 'Cambridge B2 First'),
    q('adv_b2_3', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "Only by working together we can resolve this crisis."',
      ['Correct', 'Incorrect - "Only by..." fronting requires inversion ("can we resolve")'], 1,
      '"Only + prepositional phrase" fronted requires inversion: "Only by working together CAN WE resolve...".', 'test-english B2'),
    q('adv_b2_4', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "Scarcely [A: had the plane landed] [B: than] the passengers [C: unfastened] their [D: seatbelts]."',
      ['A: had the plane landed', 'B: than - "Scarcely" pairs with "when", not "than"!', 'C: unfastened', 'D: seatbelts'], 1,
      '"Scarcely... when" is the correlative pair ("No sooner" pairs with "than").', 'Correlative Pairs B2'),
    q('adv_b2_5', 'B2', 'open_bracket', 'Open Bracket (Viewpoint Adverb)', 'Producing',
      'Form the viewpoint adverb from "economy": "(Economy) ______, the country has outperformed expectations."',
      ['Economically', 'Economic', 'Economical', 'Economizing'], 0,
      '"Economically" functions as a viewpoint/domain adverb meaning "from an economic standpoint".', 'Viewpoint Adverbs B2'),
    q('adv_b2_6', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which adverb expresses CERTAINTY rather than probability?',
      ['Undoubtedly', 'Probably', 'Presumably', 'Possibly'], 0,
      '"Undoubtedly" expresses absolute certainty; the others express degrees of likelihood.', 'Epistemic Modality B2'),
    q('adv_b2_7', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Assemble: [under / circumstances / should / no / this / opened / door / be]',
      ['Under no circumstances should this door be opened.', 'Under this door should no circumstances be opened.', 'Should under no circumstances this door be opened.', 'This door should under no circumstances opened be.'], 0,
      'Negative fronting: "Under no circumstances should this door be opened."', 'B2 Negative Inversion'),
    q('adv_b2_8', 'B2', 'cloze', 'Cloze Test', 'Understanding',
      'The witness described the suspect as being ______ five feet ten inches tall.',
      ['approximately', 'approximate', 'approximating', 'approximativeness'], 0,
      '"Approximately" modifies numerical approximations.', 'B2 Precision Lexis'),
    q('adv_b2_9', 'B2', 'matching', 'Matching', 'Understanding',
      'Match the adverb collocation: "deeply" ->',
      ['deeply regret / deeply moved', 'deeply fast / deeply loud', 'deeply dead / deeply unique', 'deeply hot / deeply cold'], 0,
      '"Deeply" collocates strongly with emotional adjectives and verbs: deeply regret, deeply moved, deeply concerned.', 'Collocations B2'),
    q('adv_b2_10', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "Not only did he win the championship, but he also broke the world record."',
      ['Correct - fronted "Not only" inverted main clause followed by "but also"', 'Incorrect - should not have inversion'], 0,
      '"Not only did he win... but he also..." is standard formal correlative inversion.', 'B2 Correlative Syntax'),
    q('adv_b2_11', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'He spoke so ______ that the audience could barely hear his closing remarks.',
      ['faintly', 'faint', 'fainting', 'faintness'], 0,
      'Adverb of manner modifying the verb "spoke": "faintly".', 'B2 Adverbs'),
    q('adv_b2_12', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "He [A: is] [B: utterly tired] after [C: running] the [D: marathon]."',
      ['A: is', 'B: utterly tired', 'C: running', 'D: marathon'], 1,
      '"Tired" is gradable, so use "very tired" or "utterly EXHAUSTED" (gradable vs ungradable clash).', 'Adverb Collocations B2'),
    q('adv_b2_13', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which adverb is a FOCUSING adverb?',
      ['Merely', 'Quickly', 'Happily', 'Gracefully'], 0,
      '"Merely" is a focusing/limiting adverb (meaning "only / just").', 'Focusing Adverbs B2'),
    q('adv_b2_14', 'B2', 'open_bracket', 'Open Bracket', 'Producing',
      'Convert to an adverb: "The board members reached agreement (unanimous) ______."',
      ['unanimously', 'unanimity', 'unanimous', 'unanimouslyness'], 0,
      '"Unanimously" describes how agreement was reached.', 'Word Formation B2'),
    q('adv_b2_15', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [rarely / seen / have / such / dedication / I / extraordinary]',
      ['Rarely have I seen such extraordinary dedication.', 'Rarely I have seen such extraordinary dedication.', 'Such extraordinary dedication have I rarely seen.', 'I have rarely seen such dedication extraordinary.'], 0,
      'Negative fronting: "Rarely have I seen such extraordinary dedication."', 'Inversion B2')
  );

  // C1 & C2 (20 items: 10 C1 + 10 C2)
  items.push(
    q('adv_c1_1', 'C1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Which adverb expresses temporal continuity up to a specific historical point in formal academic prose?',
      ['Hitherto', 'Thereafter', 'Heretofore', 'Whilom'], 0,
      '"Hitherto" means "until this time / previously".', 'Academic Lexis C1'),
    q('adv_c1_2', 'C1', 'open_bracket', 'Open Bracket', 'Producing',
      'Insert the inverted auxiliary: "On no account (should / must) ______ confidential documents be removed from the archive."',
      ['should', 'could', 'would', 'will'], 0,
      'Negative prepositional fronting: "On no account SHOULD confidential documents be removed...".', 'C1 Inversion'),
    q('adv_c1_3', 'C1', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the error: "Barely [A: the meeting had begun] [B: when] the delegates [C: staged] a walkout."',
      ['A: the meeting had begun - requires inversion: "Barely had the meeting begun"', 'B: when', 'C: staged', 'No error'], 0,
      '"Barely" at clause head requires inversion: "Barely had the meeting begun".', 'C1 Inversion Traps'),
    q('adv_c1_4', 'C1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The discovery was serendipitous, insofar as the researchers were searching for an entirely different compound."',
      ['Correct - "insofar as" functions as a formal adverbial conjunction of extent/degree', 'Incorrect'], 0,
      '"Insofar as" is formal academic syntax expressing the extent or degree to which something is true.', 'C1 Formal Syntax'),
    q('adv_c1_5', 'C1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Assemble: [only / did / then / comprehend / the / of / gravity / we / the / situation]',
      ['Only then did we comprehend the gravity of the situation.', 'Did we only then comprehend the gravity of the situation.', 'Then only did we the gravity of the situation comprehend.', 'The gravity of the situation only then did we comprehend.'], 0,
      'Fronted restrictive temporal adverbial: "Only then did we comprehend the gravity of the situation."', 'C1 Inversion'),
    q('adv_c1_6', 'C1', 'cloze', 'Cloze Test', 'Understanding',
      'The two theories are ______ incompatible; accepting one logically entails rejecting the other.',
      ['fundamentally', 'merely', 'fairly', 'scarcely'], 0,
      '"Fundamentally incompatible" is a high-level academic collocation denoting mutually exclusive principles.', 'Academic Collocations C1'),
    q('adv_c1_7', 'C1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which adverb functions as a CONCESSIVE conjunct (similar to "nevertheless")?',
      ['Nonetheless', 'Furthermore', 'Moreover', 'Consequently'], 0,
      '"Nonetheless" conveys concession/contrast; furthermore/moreover express addition; consequently expresses result.', 'Discourse Markers C1'),
    q('adv_c1_8', 'C1', 'matching', 'Matching', 'Understanding',
      'Match the position: "The board will definitely have been informed." What position is "definitely" in?',
      ['Mid-position after first auxiliary', 'End-position', 'Fronted position', 'Predicative complement'], 0,
      'In multi-auxiliary verb chains, mid-position adverbs sit after the first finite auxiliary ("will definitely have been").', 'C1 Adverb Placement'),
    q('adv_c1_9', 'C1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The treaty was ______ signed in Geneva, concluding two years of hostilities.',
      ['formally', 'formal', 'formalism', 'in formal'], 0,
      'Adverb of manner modifying the passive verb "was signed": "formally".', 'C1 Lexis'),
    q('adv_c1_10', 'C1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "Seldom if ever does one encounter an orator of such eloquence."',
      ['Correct - double negative/restrictive fronting with inverted pronoun concord', 'Incorrect - double fronting is ungrammatical'], 0,
      '"Seldom if ever" is an established formulaic restrictive phrase triggering subject-auxiliary inversion.', 'C1 Idiomatic Inversion'),

    // C2 (10 items)
    q('adv_c2_1', 'C2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'What syntactic function does "hitherto" perform in: "A hitherto unknown manuscript was discovered in the abbey"?',
      ['Pre-adjectival temporal modifier', 'Sentence conjunction', 'Locative preposition', 'Direct object complement'], 0,
      '"Hitherto" functions as a temporal adverb modifying the participial adjective "unknown".', 'C2 Morphology & Syntax'),
    q('adv_c2_2', 'C2', 'open_bracket', 'Open Bracket', 'Producing',
      'Complete the high formal inversion: "Not since the Treaty of Versailles (have / had) ______ sovereign boundaries been redrawn on this scale."',
      ['have', 'had', 'were', 'did'], 0,
      'Temporal fronted restriction with present relevance: "Not since... have sovereign boundaries been redrawn...".', 'C2 Formal Inversion'),
    q('adv_c2_3', 'C2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the defect: "In no way [A: the minister\'s remarks] [B: can be construed] as an admission of [C: culpability]."',
      ['A: the minister\'s remarks - requires inversion: "can the minister\'s remarks be construed"!', 'B: can be construed', 'C: culpability', 'No error'], 0,
      'Negative adverbial "In no way" requires auxiliary inversion: "In no way CAN the minister\'s remarks be construed".', 'C2 Inversion Traps'),
    q('adv_c2_4', 'C2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Reconstruct: [whither / nor / whence / he / knew / came / it / it / went]',
      ['He knew neither whence it came nor whither it went.', 'Whence it came nor whither it went he knew neither.', 'Neither whence it came he knew nor whither it went.', 'Nor whither it went he knew neither whence it came.'], 0,
      'Archaic directional adverbs: "whence" (from where) and "whither" (to where).', 'Classical Rhetoric C2'),
    q('adv_c2_5', 'C2', 'cloze', 'Cloze Test', 'Understanding',
      'The argument, ______ sound in premise, collapses when subjected to empirical verification.',
      ['ostensibly', 'pure', 'plain', 'merely'], 0,
      '"Ostensibly" means apparently or seemingly on the surface, but perhaps not in fact.', 'C2 Epistemic Adverbs'),
    q('adv_c2_6', 'C2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which archaic adverb means "to what place / where to"?',
      ['Whither', 'Whence', 'Thither', 'Hither'], 0,
      '"Whither" means "to where". ("Whence" means "from where"; "thither" means "to that place"; "hither" means "to this place").', 'Archaic Directionals C2'),
    q('adv_c2_7', 'C2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The resolution was passed ______, without a single dissenting voice.',
      ['nemine contradicente', 'ipso facto', 'inter alia', 'de facto'], 0,
      '"Nemine contradicente" (abbreviated nem. con.) is a Latinate parliamentary adverb meaning unanimously / with no one dissenting.', 'Latin Adverbials C2'),
    q('adv_c2_8', 'C2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "Much though I admire his erudition, I cannot endorse his methodological approach."',
      ['Correct - fronted adverbial "Much though" expressing concession', 'Incorrect - concession must start with "Although"'], 0,
      '"Adverb + though + clause" is established formal fronted concessive syntax.', 'C2 Concessive Syntax'),
    q('adv_c2_9', 'C2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "Never [A: had I] [B: seen] such vanity, [C: nor I had] [D: anticipated] such arrogance."',
      ['A: had I', 'B: seen', 'C: nor I had - negative "nor" also triggers inversion: "nor had I anticipated"!', 'D: anticipated'], 2,
      'Negative coordinator "nor" requires auxiliary inversion: "nor had I anticipated".', 'Compound Inversion C2'),
    q('adv_c2_10', 'C2', 'open_bracket', 'Open Bracket', 'Producing',
      'Supply the formal restrictive connector: "The agreement holds good (insofar / inasumch) ______ as both parties observe the covenants."',
      ['insofar', 'inasmuch', 'insomuch', 'wherever'], 0,
      '"Insofar as" specifies the boundary/extent of applicability.', 'C2 Legal Syntax')
  );

  return items;
}

function getAdjectives() {
  const items = [];
  // A1 (15 items)
  items.push(
    q('adj_a1_1', 'A1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Identify the adjective in the sentence: "The small bird built a nest in the tree."',
      ['small', 'bird', 'built', 'tree'], 0,
      '"Small" is an adjective describing the size of the noun "bird".', 'British Council A1'),
    q('adj_a1_2', 'A1', 'open_bracket', 'Open Bracket (Comparative)', 'Producing',
      'Form the comparative of the adjective: "An elephant is (big) ______ than a horse."',
      ['bigger', 'biger', 'more big', 'biggest'], 0,
      'One-syllable adjectives with C-V-C double the consonant: "bigger".', 'test-english A1'),
    q('adj_a1_3', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "She wore a dress red to the wedding party."',
      ['Correct', 'Incorrect - in English, descriptive adjectives precede the noun ("a red dress")'], 1,
      'In English, adjectives usually sit before the noun (attributive position): "a red dress".', 'Cambridge A1'),
    q('adj_a1_4', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which word is an IRREGULAR comparative adjective?',
      ['Better', 'Taller', 'Smaller', 'Older'], 0,
      '"Better" is the irregular comparative of "good" (good -> better -> best).', 'Wordwall A1'),
    q('adj_a1_5', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Today is the ______ day of the year.',
      ['hottest', 'hotter', 'most hot', 'hotest'], 0,
      'Superlative with "the" for short adjectives: "the hottest" (double t).', 'VOA English A1'),
    q('adj_a1_6', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [has / eyes / brown / beautiful / she]',
      ['She has beautiful brown eyes.', 'She has brown beautiful eyes.', 'Beautiful eyes brown she has.', 'Eyes brown beautiful she has.'], 0,
      'Opinion (beautiful) precedes Color (brown): "beautiful brown eyes".', 'Bamboozle A1'),
    q('adj_a1_7', 'A1', 'checking_error', 'Checking Error', 'Explaining',
      'Find the mistake: "Mount Everest is the [A: most high] [B: mountain] [C: in] the [D: world]."',
      ['A: most high', 'B: mountain', 'C: in', 'D: world'], 0,
      'One-syllable adjectives take -est: "the HIGHEST", not "the most high".', 'Elementary Superlatives'),
    q('adj_a1_8', 'A1', 'matching', 'Matching', 'Memory',
      'Match the adjective "bad" with its superlative form:',
      ['baddest', 'worst', 'worse', 'more bad'], 1,
      'Irregular adjective "bad" -> comparative "worse" -> superlative "worst".', 'Oxford A1'),
    q('adj_a1_9', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "This soup tastes delicious."',
      ['Correct - linking verb "taste" is followed by a predicative adjective', 'Incorrect - should use adverb "deliciously"'], 0,
      'Linking verbs of perception (taste, smell, look, feel) take predicative adjectives, not adverbs.', 'British Council A1'),
    q('adj_a1_10', 'A1', 'open_bracket', 'Open Bracket', 'Producing',
      'Provide the superlative: "He is the (friendly) ______ person in our office."',
      ['friendliest', 'most friendly', 'friendlyest', 'more friendly'], 0,
      'Two-syllable adjectives ending in -y change "y" to "i" and add -est: "friendliest".', 'test-english A1'),
    q('adj_a1_11', 'A1', 'cloze', 'Cloze Test', 'Understanding',
      'She is ______ than her older sister.',
      ['taller', 'tallest', 'more tall', 'tall'], 0,
      'Comparative with "than" for short adjective: "taller".', 'Cambridge A1'),
    q('adj_a1_12', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which word is an OPPOSITE (antonym) of "cheap"?',
      ['Expensive', 'Small', 'Quiet', 'Fast'], 0,
      '"Expensive" is the antonym of "cheap".', 'Wordwall A1'),
    q('adj_a1_13', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'My grandfather bought an ______ wooden chair at the market.',
      ['old', 'young', 'modern', 'newly'], 0,
      '"An" requires a vowel sound: "an old wooden chair".', 'VOA English A1'),
    q('adj_a1_14', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [cold / was / yesterday / weather / the / very]',
      ['The weather was very cold yesterday.', 'Yesterday the cold weather was very.', 'Very cold was the weather yesterday.', 'The weather very cold was yesterday.'], 0,
      'Subject (The weather) + Verb (was) + Adjective phrase (very cold) + Time (yesterday).', 'Syntax A1'),
    q('adj_a1_15', 'A1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "This car is [A: more cheap] [B: than] that [C: luxury] [D: sedan]."',
      ['A: more cheap', 'B: than', 'C: luxury', 'D: sedan'], 0,
      'One-syllable adjective "cheap" takes -er: "cheaper", not "more cheap".', 'Comparative Rules A1')
  );

  // A2 (15 items)
  items.push(
    q('adj_a2_1', 'A2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Distinguish -ed vs -ing: "The grammar lecture was so ______ that many students felt ______."',
      ['boring / bored', 'bored / boring', 'boring / boring', 'bored / bored'], 0,
      '-ing describes the cause/characteristic (the lecture was boring); -ed describes the feeling experienced (students felt bored).', 'test-english A2'),
    q('adj_a2_2', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'My city is not as ______ as Bangkok.',
      ['crowded', 'more crowded', 'crowdedest', 'most crowded'], 0,
      'Equative comparison uses "as + base adjective + as": "as crowded as".', 'Cambridge A2'),
    q('adj_a2_3', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The children were fascinating by the magician\'s tricks."',
      ['Correct', 'Incorrect - emotional recipient requires participial adjective "fascinated"'], 1,
      'People experiencing the feeling take -ed: "were fascinated".', 'Participial Adjectives A2'),
    q('adj_a2_4', 'A2', 'open_bracket', 'Open Bracket (OSASCOMP)', 'Producing',
      'Order the adjectives: "She wore a (Italian / black / stylish) ______ leather jacket."',
      ['stylish black Italian', 'black Italian stylish', 'Italian stylish black', 'stylish Italian black'], 0,
      'OSASCOMP: Opinion (stylish) -> Color (black) -> Origin (Italian).', 'Adjective Order A2'),
    q('adj_a2_5', 'A2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the mistake: "He is [A: the most] [B: unique] painter [C: in the entire] [D: country]."',
      ['A: the most', 'B: unique', 'C: in the entire', 'D: country'], 0,
      '"Unique" is an absolute/non-gradable adjective (meaning one of a kind); it cannot take "most".', 'Non-gradables A2'),
    q('adj_a2_6', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which adjective CANNOT be used before a noun (only predicative after linking verbs)?',
      ['Afraid', 'Happy', 'Small', 'Green'], 0,
      '"Afraid" is an a-adjective used only predicatively (e.g., "The boy is afraid", never *"an afraid boy").', 'Predicative Only A2'),
    q('adj_a2_7', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [interested / is / in / history / she / Cambodian]',
      ['She is interested in Cambodian history.', 'She is in Cambodian history interested.', 'Interested in Cambodian history she is.', 'In Cambodian history is she interested.'], 0,
      'Subject (She) + Verb (is) + Adjective (interested) + Prepositional complement (in Cambodian history).', 'Wordwall A2'),
    q('adj_a2_8', 'A2', 'cloze', 'Cloze Test', 'Understanding',
      'Traveling by bullet train is ______ more comfortable than taking the bus.',
      ['much', 'very', 'more', 'too'], 0,
      'Comparatives are modified by "much" (or "far / significantly"), never "very": "much more comfortable".', 'Modifiers of Comparatives A2'),
    q('adj_a2_9', 'A2', 'matching', 'Matching', 'Understanding',
      'Match the compound adjective: "a child who is six years old" ->',
      ['a six-year-old child', 'a six-years-old child', 'a six-year-aged child', 'a six-years child'], 0,
      'Hyphenated compound pre-nominal modifiers remain singular: "a six-year-old child".', 'Compound Adjectives A2'),
    q('adj_a2_10', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "The asleep baby looked so peaceful in the crib."',
      ['Correct', 'Incorrect - "asleep" is predicative only; say "The sleeping baby"'], 1,
      '"Asleep" cannot be used attributively before a noun; use "sleeping baby".', 'Oxford A2'),
    q('adj_a2_11', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'This restaurant is ______ expensive than the one near the harbor.',
      ['less', 'least', 'little', 'lesser'], 0,
      'Comparative of inferiority uses "less + adjective + than": "less expensive than".', 'Cambridge A2'),
    q('adj_a2_12', 'A2', 'open_bracket', 'Open Bracket', 'Producing',
      'Form the adjective from "create": "She is a highly (create) ______ graphic designer."',
      ['creative', 'creating', 'creativity', 'creation'], 0,
      'The adjective suffix is -ive: "creative".', 'Word Formation A2'),
    q('adj_a2_13', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which word is a NON-GRADABLE (extreme) adjective?',
      ['Freezing', 'Cold', 'Warm', 'Hot'], 0,
      '"Freezing" means extremely cold and cannot be modified by "very" (use "absolutely freezing").', 'Gradable vs Extreme A2'),
    q('adj_a2_14', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Assemble: [round / table / a / bought / dining / wooden / they]',
      ['They bought a round wooden dining table.', 'They bought a wooden round dining table.', 'A dining round wooden table they bought.', 'They bought round a wooden dining table.'], 0,
      'Shape (round) precedes Material (wooden), followed by Purpose noun (dining table).', 'OSASCOMP A2'),
    q('adj_a2_15', 'A2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "She [A: feels] [B: happily] [C: about] her [D: promotion]."',
      ['A: feels', 'B: happily', 'C: about', 'D: promotion'], 1,
      'Linking verb "feels" takes an adjective: "feels HAPPY", not adverb "happily".', 'Linking Verbs A2')
  );

  // B1 (15 items)
  items.push(
    q('adj_b1_1', 'B1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Order according to OSASCOMP: "He drove a ______ sports car."',
      ['sleek new Italian red', 'sleek new red Italian', 'new sleek Italian red', 'red sleek Italian new'], 1,
      'Opinion (sleek) -> Age (new) -> Color (red) -> Origin (Italian).', 'Cambridge B1'),
    q('adj_b1_2', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The longer you wait to prepare, the ______ the exam will feel.',
      ['more difficult', 'most difficult', 'difficult', 'difficulter'], 0,
      'Double proportional comparative: "The + comparative..., the + comparative...": "The longer..., the more difficult...".', 'test-english B1'),
    q('adj_b1_3', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The architecture of Florence is older than Rome."',
      ['Correct', 'Incorrect - faulty comparison: comparing architecture to a city! Say "than that of Rome"'], 1,
      'Logical comparison requires comparing like with like: "than THAT OF Rome".', 'Logical Comparison B1'),
    q('adj_b1_4', 'B1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the mistake: "She [A: gave] a [B: three-hours] [C: lecture] on [D: international law]."',
      ['A: gave', 'B: three-hours', 'C: lecture', 'D: international law'], 1,
      'Hyphenated compound adjective remains singular: "a three-hour lecture".', 'Compound Adjectives B1'),
    q('adj_b1_5', 'B1', 'open_bracket', 'Open Bracket (Negative Prefix)', 'Producing',
      'Add the correct negative prefix: "It is (responsible) ______ to drive without a seatbelt."',
      ['irresponsible', 'unresponsible', 'disresponsible', 'inresponsible'], 0,
      'Adjectives beginning with "r" take the prefix "ir-": "irresponsible".', 'Prefixes B1'),
    q('adj_b1_6', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which adjective takes the negative prefix "il-"?',
      ['Logical', 'Possible', 'Tolerant', 'Sincere'], 0,
      '"Logical" -> "illogical" (prefix il- before l).', 'Word Formation B1'),
    q('adj_b1_7', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Order: [more / the / the / we / practice / fluent / become / we]',
      ['The more we practice, the more fluent we become.', 'The more fluent we become, the more we practice.', 'The more practice we, the more fluent become we.', 'We become the more fluent, the more practice we.'], 0,
      'Proportional comparative: "The more..., the more...".', 'Proportional B1'),
    q('adj_b1_8', 'B1', 'cloze', 'Cloze Test', 'Understanding',
      'The homeless ______ provided with temporary shelter and warm meals during the blizzard.',
      ['were', 'was', 'is', 'has been'], 0,
      '"The + adjective" representing a whole class of people is plural and takes a plural verb: "The homeless WERE...".', 'The + Adjective B1'),
    q('adj_b1_9', 'B1', 'matching', 'Matching', 'Understanding',
      'Match the collocation: "crystal" ->',
      ['crystal clear', 'crystal hot', 'crystal quiet', 'crystal cheap'], 0,
      'Established compound intensifying adjective: "crystal clear".', 'Collocations B1'),
    q('adj_b1_10', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The rich has a social responsibility to assist the underprivileged."',
      ['Correct', 'Incorrect - "The rich" refers to rich people collectively and takes a plural verb "have"'], 1,
      '"The rich" is a plural collective adjective noun: "The rich HAVE...".', 'British Council B1'),
    q('adj_b1_11', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The climate of Cambodia is much hotter than ______ of northern Japan.',
      ['that', 'this', 'those', 'these'], 0,
      '"That" replaces the singular noun "the climate".', 'Comparative Pro-forms B1'),
    q('adj_b1_12', 'B1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "He [A: is] [B: senior] [C: than] me [D: in the company]."',
      ['A: is', 'B: senior', 'C: than', 'D: in the company'], 2,
      'Latin comparatives (senior, junior, superior, inferior) take "to", not "than": "senior TO me".', 'Latin Comparatives B1'),
    q('adj_b1_13', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which adjective takes preposition "TO" instead of "than" in comparative structures?',
      ['Superior', 'Better', 'Taller', 'Bigger'], 0,
      '"Superior to" (Latin comparative). Better, taller, and bigger take "than".', 'Comparative Rules B1'),
    q('adj_b1_14', 'B1', 'open_bracket', 'Open Bracket', 'Producing',
      'Supply the prefix: "Her explanation was completely (comprehensible) ______; nobody understood it."',
      ['incomprehensible', 'uncomprehensible', 'discomprehensible', 'imcomprehensible'], 0,
      '"Incomprehensible" (prefix in-).', 'Word Formation B1'),
    q('adj_b1_15', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [she / someone / looking / is / for / reliable]',
      ['She is looking for someone reliable.', 'She is looking for reliable someone.', 'Reliable someone she is looking for.', 'Someone she is looking for reliable.'], 0,
      'Adjectives modifying indefinite pronouns (someone, anyone, nothing) sit AFTER the pronoun (postpositive): "someone reliable".', 'Postpositive B1')
  );

  // B2 (15 items)
  items.push(
    q('adj_b2_1', 'B2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Which postpositive adjective sits AFTER the noun in institutional titles?',
      ['President-elect', 'Elect-president', 'Election-president', 'Elected-president'], 0,
      '"President-elect" (like "heir apparent", "court martial") uses postpositive French loan syntax.', 'Oxford B2'),
    q('adj_b2_2', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The museum displays artifacts dating from ancient times to the ______ century.',
      ['present', 'presence', 'presented', 'presently'], 0,
      '"The present century" (adjective meaning current).', 'B2 Vocabulary'),
    q('adj_b2_3', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The wounded was evacuated by helicopter immediately after the explosion."',
      ['Correct if referring to one person, but "the wounded" collectively takes plural "were"', 'Always singular'], 0,
      '"The wounded" as a generic plural takes "were evacuated"; if singular, say "the wounded soldier was...".', 'Plural Adjectives B2'),
    q('adj_b2_4', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "This car is [A: by far] the [B: most expensive] of [C: the two] [D: vehicles]."',
      ['A: by far', 'B: most expensive', 'C: the two - when comparing only two, strict prescriptive grammar uses comparative "the MORE expensive"!', 'D: vehicles'], 1,
      'When comparing strictly two items, traditional grammar requires the comparative: "the MORE expensive of the two".', 'Prescriptive Comparison B2'),
    q('adj_b2_5', 'B2', 'open_bracket', 'Open Bracket (Negative Prefix)', 'Producing',
      'Complete with negative prefix: "His behavior was utterly (defensible) ______."',
      ['indefensible', 'undefensible', 'disdefensible', 'imdefensible'], 0,
      '"Indefensible" takes the prefix in-.', 'B2 Word Formation'),
    q('adj_b2_6', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which of the following is a COMPOUND HYPHENATED ADJECTIVE?',
      ['State-of-the-art', 'Contemporary', 'Sophisticated', 'Modernistic'], 0,
      '"State-of-the-art" is a multi-word compound adjective.', 'Compound Morphology B2'),
    q('adj_b2_7', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Assemble: [heir / prince / the / is / the / to / apparent / throne / the]',
      ['The prince is the heir apparent to the throne.', 'The apparent heir prince is to the throne.', 'The throne is heir apparent to the prince.', 'To the throne the prince heir apparent is.'], 0,
      'Postpositive legal title: "heir apparent".', 'Postpositive Syntax B2'),
    q('adj_b2_8', 'B2', 'cloze', 'Cloze Test', 'Understanding',
      'The company\'s assets are ______ to its accumulated sovereign liabilities.',
      ['inferior', 'less', 'smaller', 'lower'], 0,
      '"Inferior to" is the formal comparative collocation.', 'B2 Collocations'),
    q('adj_b2_9', 'B2', 'matching', 'Matching', 'Understanding',
      'Match the ungradable adjective with its suitable adverb modifier: "dead" ->',
      ['Stone dead / completely dead', 'Very dead', 'Fairly dead', 'A bit dead'], 0,
      'Absolute/ungradable adjectives pair with totalizing intensifiers ("completely dead" or idiom "stone dead").', 'Collocations B2'),
    q('adj_b2_10', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "She is a well-known, highly respected, and deeply committed educator."',
      ['Correct - well-punctuated coordinate compound participial adjectives', 'Incorrect - too many adjectives'], 0,
      'Symmetrical coordinate compound adjectives modifying "educator".', 'Adjective Chains B2'),
    q('adj_b2_11', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'There is ______ little hope of finding survivors after the avalanche.',
      ['precious', 'preciously', 'preciousness', 'more precious'], 0,
      '"Precious little" is an established idiomatic intensifying modifier meaning "almost none".', 'Idiomatic Modifiers B2'),
    q('adj_b2_12', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the error: "The [A: two first] chapters of the dissertation [B: establish] the [C: theoretical] [D: framework]."',
      ['A: two first - ordinal precedes cardinal: "The first two"!', 'B: establish', 'C: theoretical', 'D: framework'], 0,
      'Order of numerals: Ordinal (first) precedes Cardinal (two): "The FIRST TWO chapters".', 'Numeral Order B2'),
    q('adj_b2_13', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which adjective is ATTRIBUTIVE ONLY (never predicative)?',
      ['Former (a former president)', 'Asleep', 'Alive', 'Afraid'], 0,
      '"Former" can only sit before a noun ("the former minister", never *"The minister is former"). Asleep, alive, afraid are predicative only.', 'Attributive Only B2'),
    q('adj_b2_14', 'B2', 'open_bracket', 'Open Bracket', 'Producing',
      'Form the adjective: "His speech was full of (provoke) ______ statements that sparked fierce debate."',
      ['provocative', 'provokingness', 'provocable', 'provokeful'], 0,
      '"Provocative" is the standard qualitative adjective.', 'B2 Vocabulary'),
    q('adj_b2_15', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [available / seats / were / no / the / flight / on]',
      ['There were no seats available on the flight.', 'No seats were there available on the flight.', 'Available seats there were no on the flight.', 'On the flight seats available were no there.'], 0,
      'Postpositive position: "no seats available on the flight".', 'Postpositive Syntax B2')
  );

  // C1 & C2 (20 items: 10 C1 + 10 C2)
  items.push(
    q('adj_c1_1', 'C1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Identify the sentence exhibiting correct postpositive adjective placement in formal register:',
      ['The secretary general addressed all delegates present.', 'The secretary general addressed all present delegates.', 'The secretary general addressed all delegates presentation.', 'The secretary general addressed present all delegates.'], 0,
      '"Delegates present" (postpositive "present" means "who were in attendance"; whereas "present delegates" would mean current).', 'Cambridge C1 Advanced'),
    q('adj_c1_2', 'C1', 'open_bracket', 'Open Bracket', 'Producing',
      'Form the literary adjective meaning unchanging: "The laws of the cosmos remain (mutable) ______."',
      ['immutable', 'unmutable', 'dismutable', 'nonmutable'], 0,
      '"Immutable" (from Latin immutabilis) means unchangeable.', 'Classical Vocabulary C1'),
    q('adj_c1_3', 'C1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the defect: "The [A: proposed] reforms are [B: diametrically] [C: opposed] [D: than] the previous policy."',
      ['A: proposed', 'B: diametrically', 'C: opposed', 'D: than - "opposed" governs "to", not "than"!'], 3,
      'The dependent preposition for "opposed" is "to": "opposed TO the previous policy".', 'Dependent Prepositions C1'),
    q('adj_c1_4', 'C1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "She gave an impromptu, off-the-cuff response to the interrogation."',
      ['Correct - hyphenated idiomatic compound adjective', 'Incorrect'], 0,
      '"Off-the-cuff" is an established hyphenated compound adjective meaning spontaneous/unprepared.', 'Compound Adjectives C1'),
    q('adj_c1_5', 'C1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Assemble: [words / fail / to / express / my / profound / gratitude]',
      ['Words fail to express my profound gratitude.', 'My profound gratitude words fail to express.', 'To express words fail my profound gratitude.', 'Fail words to express my gratitude profound.'], 0,
      'Subject (Words) + Verb (fail to express) + Direct Object (my profound gratitude).', 'C1 Rhetoric'),
    q('adj_c1_6', 'C1', 'cloze', 'Cloze Test', 'Understanding',
      'The treaty contains ______ ambiguous clauses that allow divergent interpretations.',
      ['deliberately', 'deliberate', 'deliberateness', 'in deliberate'], 0,
      'Adverb modifying the participial/qualitative adjective "ambiguous": "deliberately ambiguous".', 'Adverb-Adjective Collocations C1'),
    q('adj_c1_7', 'C1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which adjective means "existing only in name / insignificant"?',
      ['Nominal', 'Formidable', 'Inestimable', 'Prodigious'], 0,
      '"Nominal" (from Latin nomen) means in name only (e.g., "a nominal fee").', 'C1 Academic Lexis'),
    q('adj_c1_8', 'C1', 'matching', 'Matching', 'Understanding',
      'Match the postpositive phrase: "the stars visible" vs "the visible stars". What is the difference?',
      ['"Stars visible" means visible at that specific moment; "visible stars" means inherently capable of being seen', 'They are completely synonymous in every nuance', 'Only "visible stars" is grammatical', 'Only "stars visible" is grammatical'], 0,
      'Postpositive adjectives in English often denote temporary stage states rather than inherent permanent traits.', 'Linguistic Semantics C1'),
    q('adj_c1_9', 'C1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'He was ______ to sudden bouts of melancholy when working in isolation.',
      ['prone', 'prostrate', 'pliant', 'prevailing'], 0,
      '"Prone to" is the idiomatic dependent adjective collocation meaning susceptible/predisposed.', 'C1 Collocations'),
    q('adj_c1_10', 'C1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The ambassador was persona non grata in the host nation."',
      ['Correct - Latinate postpositive diplomatic designation', 'Incorrect - ungrammatical English'], 0,
      '"Persona non grata" is standard diplomatic vocabulary.', 'Diplomatic English C1'),

    // C2 (10 items)
    q('adj_c2_1', 'C2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Which adjective expresses absolute irremediability in formal register?',
      ['Irretrievable', 'Transitory', 'Ephemeral', 'Contingent'], 0,
      '"Irretrievable" means impossible to recover, regain, or remedy.', 'C2 Academic Vocabulary'),
    q('adj_c2_2', 'C2', 'open_bracket', 'Open Bracket (Latin Suffix)', 'Producing',
      'Form the classical adjective meaning all-powerful: "The monarch possessed (omni / potent) ______ authority."',
      ['omnipotent', 'omnipresent', 'omniscient', 'omnivorous'], 0,
      '"Omnipotent" means having unlimited or universal power.', 'Classical Morphology C2'),
    q('adj_c2_3', 'C2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the subtle defect: "His [A: brilliant] [B: but] [C: thoroughly erratic] conduct [D: were noted]."',
      ['A: brilliant', 'B: but', 'C: thoroughly erratic', 'D: were noted - subject is singular "conduct"!'], 3,
      '"Conduct" is an uncountable singular noun, so the passive verb must be "WAS noted".', 'C2 Concord Traps'),
    q('adj_c2_4', 'C2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Reconstruct: [conviction / steadfast / her / in / chancellor / the / signed / treaty / the]',
      ['Steadfast in her conviction, the chancellor signed the treaty.', 'The chancellor signed the treaty steadfast in her conviction.', 'In her conviction steadfast, the chancellor signed the treaty.', 'Signed the treaty the chancellor steadfast in her conviction.'], 0,
      'Fronted participial/adjectival appositive clause for periodic rhetorical suspension.', 'Periodic Sentences C2'),
    q('adj_c2_5', 'C2', 'cloze', 'Cloze Test', 'Understanding',
      'The archaeological relic was deemed to be of ______ cultural and historical significance.',
      ['inestimable', 'unestimate', 'disestimated', 'estimate-less'], 0,
      '"Inestimable" means too great or valuable to be measured.', 'High-Register Lexis C2'),
    q('adj_c2_6', 'C2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which adjective describes an inherently PERIPHERAL / SECONDARY quality?',
      ['Incidental', 'Quintessential', 'Constitutive', 'Cardinal'], 0,
      '"Incidental" means occurring as a minor accompaniment. Quintessential, constitutive, and cardinal mean essential/fundamental.', 'C2 Antonymy'),
    q('adj_c2_7', 'C2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'His reasoning was riddled with ______ fallacies that rendered the thesis untenable.',
      ['egregious', 'gregarious', 'effusive', 'elusive'], 0,
      '"Egregious" denotes conspicuously bad or glaringly offensive errors.', 'C2 Lexical Precision'),
    q('adj_c2_8', 'C2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The treaty made provisions for matters financial and ecclesiastical."',
      ['Correct - stylized postpositive coordination in legal and solemn prose', 'Incorrect - adjectives must precede nouns'], 0,
      'Postpositive coordinate adjectives ("matters financial and ecclesiastical") are hallmark features of formal archaic and statutory English.', 'C2 Stylistic Inversion'),
    q('adj_c2_9', 'C2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "She delivered an [A: impassioned], [B: erudite], and [C: deeply persuasion] [D: address]."',
      ['A: impassioned', 'B: erudite', 'C: deeply persuasion', 'D: address'], 2,
      'Parallelism defect: "persuasion" is a noun; the coordinate series of adjectives requires "persuasive".', 'Syntactic Parallelism C2'),
    q('adj_c2_10', 'C2', 'open_bracket', 'Open Bracket', 'Producing',
      'Provide the adjective meaning impervious to decay or corruption: "He possessed an (corrupt) ______ integrity."',
      ['incorruptible', 'uncorrupting', 'discorruptible', 'noncorrupted'], 0,
      '"Incorruptible" represents highest-register ethical characterization.', 'C2 Lexicogrammar')
  );

  return items;
}

module.exports = { getAdverbs, getAdjectives };
