// scripts/build_conjunctions.js
// Conjunctions (Topic 7)
const { q } = require('./q_helper');

function getConjunctions() {
  const items = [];
  // A1 (15 items)
  items.push(
    q('conj_a1_1', 'A1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Choose the coordinating conjunction to show contrast: "I like milk, ______ I do not like coffee."',
      ['and', 'but', 'so', 'or'], 1,
      '"But" connects contrasting ideas in compound sentences.', 'British Council A1'),
    q('conj_a1_2', 'A1', 'open_bracket', 'Open Bracket', 'Producing',
      'Choose (and / or): "Would you like coffee (and / or) ______ tea?"',
      ['or', 'and', 'but', 'so'], 0,
      '"Or" connects alternatives or choices.', 'test-english A1'),
    q('conj_a1_3', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "She stayed at home because it was raining heavily."',
      ['Correct - "because" introduces the clause of cause/reason', 'Incorrect'], 0,
      '"Because" correctly explains the reason for staying home.', 'Cambridge A1'),
    q('conj_a1_4', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which word is a COORDINATING conjunction (FANBOYS)?',
      ['So', 'Because', 'Although', 'Since'], 0,
      'FANBOYS: For, And, Nor, But, Or, Yet, So. "Because" and "although" are subordinating.', 'Wordwall A1'),
    q('conj_a1_5', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'He was hungry, ______ he ate two bowls of rice.',
      ['so', 'but', 'because', 'or'], 0,
      '"So" introduces the result of being hungry.', 'VOA English A1'),
    q('conj_a1_6', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [tired / was / he / he / went / so / to / bed]',
      ['He was tired so he went to bed.', 'So he went to bed he was tired.', 'He went to bed so was he tired.', 'Tired he was so went he to bed.'], 0,
      'Cause clause (He was tired) + Conjunction (so) + Result clause (he went to bed).', 'Bamboozle A1'),
    q('conj_a1_7', 'A1', 'checking_error', 'Checking Error', 'Explaining',
      'Find the mistake: "She [A: studied hard] [B: because] she [C: wanted to] [D: pass the exam]."',
      ['A: studied hard', 'B: because', 'C: wanted to', 'D: pass the exam - No mistake! Sentence is correct!'], 3,
      'The sentence is completely grammatical: "She studied hard because she wanted to pass the exam."', 'Error Checking A1'),
    q('conj_a1_8', 'A1', 'matching', 'Matching', 'Memory',
      'Match FANBOYS: What does the letter "B" stand for?',
      ['But', 'Because', 'Before', 'By'], 0,
      'In the FANBOYS acronym, B stands for "But".', 'Elementary Acronyms'),
    q('conj_a1_9', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "I will call you when I arrive at the station."',
      ['Correct - "when" introduces the time clause', 'Incorrect - say "when I will arrive"'], 0,
      'Time clauses with "when" take the present tense for future time.', 'test-english A1'),
    q('conj_a1_10', 'A1', 'open_bracket', 'Open Bracket', 'Producing',
      'Complete with (before / after): "Wash your hands (before / after) ______ you eat dinner."',
      ['before', 'after', 'while', 'since'], 0,
      '"Before" indicates prior action.', 'Spelling A1'),
    q('conj_a1_11', 'A1', 'cloze', 'Cloze Test', 'Understanding',
      'Tom is tall ______ his brother is short.',
      ['and', 'but', 'or', 'so'], 1,
      'Contrast between two people uses "but".', 'Cambridge A1'),
    q('conj_a1_12', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which conjunction connects two things that happen at the same time?',
      ['While', 'Before', 'After', 'Until'], 0,
      '"While" indicates simultaneous ongoing actions.', 'Wordwall A1'),
    q('conj_a1_13', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Wait here ______ I come back with the tickets.',
      ['until', 'because', 'so', 'although'], 0,
      '"Until" indicates up to the point in time when an event happens.', 'VOA English A1'),
    q('conj_a1_14', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [likes / apples / and / bananas / she]',
      ['She likes apples and bananas.', 'She likes bananas and apples.', 'Apples and bananas she likes.', 'She apples and bananas likes.'], 0,
      'Subject (She) + Verb (likes) + Compound Object (apples and bananas).', 'Syntax A1'),
    q('conj_a1_15', 'A1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "Although [A: it was raining], [B: but] we [C: went] for [D: a walk]."',
      ['A: it was raining', 'B: but - double conjunction error: do not use "but" with "Although"!', 'C: went', 'D: a walk'], 1,
      'Do not use "Although" and "but" in the same sentence: "Although it was raining, we went for a walk."', 'Double Conjunction Traps A1')
  );

  // A2 (15 items)
  items.push(
    q('conj_a2_1', 'A2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Select the correlative conjunction pair: "You can choose ______ the red car ______ the blue one."',
      ['either / or', 'neither / or', 'both / or', 'either / nor'], 0,
      '"Either" pairs with "or" to present two alternatives.', 'test-english A2'),
    q('conj_a2_2', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
      '______ he felt sick, he still went to work to finish his presentation.',
      ['Although', 'Because', 'Unless', 'So'], 0,
      '"Although" introduces concession/contrast.', 'Cambridge A2'),
    q('conj_a2_3', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "You will fail the exam unless you do not study."',
      ['Correct', 'Incorrect - double negative: "unless" already means "if... not", so say "unless you study"'], 1,
      '"Unless" incorporates negation; say "unless you study".', 'British Council A2'),
    q('conj_a2_4', 'A2', 'open_bracket', 'Open Bracket (Correlative)', 'Producing',
      'Supply the partner: "She speaks (both) ______ French and Spanish fluently."',
      ['both', 'either', 'neither', 'not only'], 0,
      '"Both" pairs with "and".', 'Oxford A2'),
    q('conj_a2_5', 'A2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the mistake: "Neither [A: my father] [B: or] my mother [C: likes] [D: spicy food]."',
      ['A: my father', 'B: or - "Neither" pairs with "NOR"!', 'C: likes', 'D: spicy food'], 1,
      '"Neither" pairs strictly with "nor".', 'Correlative Pairs A2'),
    q('conj_a2_6', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which word is a SUBORDINATING conjunction of condition?',
      ['Unless', 'And', 'Or', 'But'], 0,
      '"Unless" introduces conditional subordinate clauses.', 'Wordwall A2'),
    q('conj_a2_7', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [arrived / as / as / we / called / we / soon]',
      ['We called as soon as we arrived.', 'As soon as we arrived we called.', 'We arrived as soon as we called.', 'As we arrived soon as called we.'], 0,
      'Complex time conjunction: "as soon as".', 'Syntax A2'),
    q('conj_a2_8', 'A2', 'cloze', 'Cloze Test', 'Understanding',
      'He worked overtime ______ he could earn extra money for his family vacation.',
      ['so that', 'unless', 'although', 'whereas'], 0,
      '"So that" expresses purpose followed by a modal clause.', 'test-english A2'),
    q('conj_a2_9', 'A2', 'matching', 'Matching', 'Understanding',
      'Match the conjunction: "as long as" ->',
      ['Provided that / on the condition that', 'At an earlier time', 'In spite of', 'Because of'], 0,
      '"As long as" means on the condition that.', 'Cambridge A2'),
    q('conj_a2_10', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "Take an umbrella in case it rains."',
      ['Correct - "in case" prepares for a future contingency', 'Incorrect - say "in case it will rain"'], 0,
      '"In case" takes the present tense for future possibility.', 'British Council A2'),
    q('conj_a2_11', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
      '______ she was tired, she smiled warmly at her guests.',
      ['Even though', 'Because', 'Unless', 'Since'], 0,
      '"Even though" emphasizes strong concession.', 'Concession A2'),
    q('conj_a2_12', 'A2', 'open_bracket', 'Open Bracket', 'Producing',
      'Supply the partner: "He is (not only) ______ intelligent but also extraordinarily modest."',
      ['not only', 'neither', 'either', 'both'], 0,
      '"Not only" pairs with "but also".', 'Correlatives A2'),
    q('conj_a2_13', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which conjunction indicates TIME sequence?',
      ['After', 'Though', 'Unless', 'Whereas'], 0,
      '"After" introduces a temporal sequence.', 'Wordwall A2'),
    q('conj_a2_14', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [rains / we / stay / will / inside / if / it]',
      ['If it rains, we will stay inside.', 'We will stay inside if it rains.', 'It rains if we will stay inside.', 'Stay inside will we if it rains.'], 0,
      'First conditional: "If it rains, we will stay inside."', 'Conditionals A2'),
    q('conj_a2_15', 'A2', 'checking_error', 'Checking Error', 'Explaining',
      'Find the mistake: "I will [A: wait] here [B: until] you [C: will come] [D: back]."',
      ['A: wait', 'B: until', 'C: will come - time clauses take present tense "come"!', 'D: back'], 2,
      'Subordinate time clauses with "until" do not take "will": "until you come back".', 'Time Clauses A2')
  );

  // B1 (15 items)
  items.push(
    q('conj_b1_1', 'B1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Notice concord with correlatives: "Neither the teacher nor the students ______ present in the auditorium."',
      ['were', 'was', 'is', 'has been'], 0,
      'In "Neither... nor", proximity concord dictates agreement with the nearer subject ("the students were").', 'Cambridge B1'),
    q('conj_b1_2', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'You can borrow my car ______ you promise to return it with a full tank of fuel.',
      ['provided that', 'unless', 'despite', 'whereas'], 0,
      '"Provided that" means on the strict condition that.', 'test-english B1'),
    q('conj_b1_3', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The laboratory was understaffed; however, they completed the analysis on time."',
      ['Correct - conjunctive adverb with semicolon and comma', 'Incorrect'], 0,
      'Conjunctive adverbs connecting independent clauses take semicolon before and comma after: \"; however,\".', 'Punctuation B1'),
    q('conj_b1_4', 'B1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "Not only [A: the director] [B: but also] the actors [C: was] praised by [D: the critics]."',
      ['A: the director', 'B: but also', 'C: was - nearer subject is plural "actors", so use "were"!', 'D: the critics'], 2,
      'Proximity concord requires "were" with "actors".', 'Correlative Concord B1'),
    q('conj_b1_5', 'B1', 'open_bracket', 'Open Bracket (Condition)', 'Producing',
      'Insert formal conditional conjunction: "(Providing / Unless) ______ that all signatures are obtained, the treaty takes effect."',
      ['Providing', 'Unless', 'Although', 'Despite'], 0,
      '"Providing that / Provided that" introduces formal conditions.', 'Oxford B1'),
    q('conj_b1_6', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which word introduces a CLAUSE OF CONTRAST?',
      ['Whereas', 'Because', 'Since', 'So that'], 0,
      '"Whereas" introduces a direct contrast between two clauses.', 'Wordwall B1'),
    q('conj_b1_7', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [nor / he / neither / called / wrote / he]',
      ['He neither called nor did he write.', 'Neither he called nor wrote he.', 'He called neither nor did he write.', 'Nor he wrote neither he called.'], 0,
      'Correlative negation: "He neither called nor did he write" (or "He neither called nor wrote").', 'Syntax B1'),
    q('conj_b1_8', 'B1', 'cloze', 'Cloze Test', 'Understanding',
      'The economy grew rapidly, ______ inflation remained remarkably low.',
      ['while', 'unless', 'because', 'in order that'], 0,
      '"While" here functions concessively meaning "although / at the same time".', 'B1 Concessive Connectors'),
    q('conj_b1_9', 'B1', 'matching', 'Matching', 'Understanding',
      'Match the conjunctive adverb: "Furthermore" ->',
      ['In addition / moreover', 'On the contrary', 'As a consequence', 'In place of'], 0,
      '"Furthermore" adds supporting evidence or points.', 'Cambridge B1'),
    q('conj_b1_10', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "He failed the test, he didn\'t study."',
      ['Incorrect - comma splice: two independent clauses joined by only a comma!', 'Correct'], 0,
      'Comma splice: two independent clauses cannot be joined by a comma alone without a coordinating conjunction (or semicolon).', 'Comma Splices B1'),
    q('conj_b1_11', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Some people prefer living in bustling cities, ______ others cherish the tranquility of rural villages.',
      ['whereas', 'since', 'because', 'unless'], 0,
      '"Whereas" contrasts two distinct preferences.', 'B1 Connectors'),
    q('conj_b1_12', 'B1', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the error: "He [A: is not only] [B: a gifted pianist] [C: but] an accomplished composer [D: as well]."',
      ['A: is not only', 'B: a gifted pianist', 'C: but - standard correlative is "but also", though "but... as well" is colloquial, in standard tests "but also" is required!', 'D: as well'], 2,
      'Formal correlative coordination requires: "not only... but also...".', 'Correlative Standards B1'),
    q('conj_b1_13', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which word is a CAUSAL conjunction (gives reason)?',
      ['Inasmuch as', 'Although', 'Even if', 'Unless'], 0,
      '"Inasmuch as" means since / because.', 'Causal Conjunctions B1'),
    q('conj_b1_14', 'B1', 'open_bracket', 'Open Bracket', 'Producing',
      'Complete with the purpose conjunction: "She wore headphones (so that / in order) ______ she would not disturb her roommate."',
      ['so that', 'in order', 'because', 'despite'], 0,
      '"So that + modal clause" expresses purpose.', 'Clauses of Purpose B1'),
    q('conj_b1_15', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [as / long / you / work / as / hard / you / will / succeed]',
      ['As long as you work hard, you will succeed.', 'You will succeed as long as you work hard.', 'Work hard as long as you will succeed.', 'As you work hard long as will you succeed.'], 0,
      'Conditional clause: "As long as you work hard, you will succeed."', 'B1 Syntax')
  );

  // B2 (15 items)
  items.push(
    q('conj_b2_1', 'B2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Select the concessive structure with fronted adjective: "______ the task was, they accomplished it ahead of schedule."',
      ['Difficult though', 'Although difficult', 'Despite difficult', 'Even though difficult'], 0,
      '"Adjective + though/as + subject + verb": "Difficult though the task was...".', 'Cambridge B2 First'),
    q('conj_b2_2', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The company will continue operations ______ that government subsidies remain available.',
      ['provided', 'unless', 'lest', 'despite'], 0,
      '"Provided that" introduces formal conditional necessity.', 'test-english B2'),
    q('conj_b2_3', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "He decided to reject the promotion, for he wished to spend more time with his children."',
      ['Correct - coordinating conjunction "for" introducing an explanatory clause with a comma', 'Incorrect - "for" cannot be a conjunction'], 0,
      '"For" is the literary coordinating conjunction of the FANBOYS family meaning "because / seeing that".', 'FANBOYS Literary B2'),
    q('conj_b2_4', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "We [A: will proceed] [B: with the project] [C: on condition] [D: unless funding is cut]."',
      ['A: will proceed', 'B: with the project', 'C: on condition', 'D: unless funding is cut - clash of redundant conditions!'], 3,
      '"On condition that" should be followed by positive condition ("on condition that funding is maintained"), not "unless".', 'B2 Redundancy'),
    q('conj_b2_5', 'B2', 'open_bracket', 'Open Bracket (Formal Concession)', 'Producing',
      'Supply the inverted concession: "Much (as / though) ______ I respect his intellect, I find his conclusion flawed."',
      ['as', 'like', 'with', 'by'], 0,
      '"Much as / Much though" introduces fronted concession.', 'Oxford B2'),
    q('conj_b2_6', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which connector CANNOT coordinate two main clauses with only a comma?',
      ['However', 'And', 'But', 'So'], 0,
      '"However" is a conjunctive adverb and cannot coordinate with only a comma (it requires a semicolon or full stop).', 'Punctuation B2'),
    q('conj_b2_7', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Assemble: [not / was / proposal / the / accepted / only / it / but / was / praised / also]',
      ['Not only was the proposal accepted, but it was also praised.', 'The proposal was not only accepted but also it was praised.', 'Accepted was the proposal not only but it was praised also.', 'Was the proposal not only accepted but it was also praised.'], 0,
      'Correlative inversion: "Not only was the proposal accepted, but it was also praised."', 'Correlative Inversion B2'),
    q('conj_b2_8', 'B2', 'cloze', 'Cloze Test', 'Understanding',
      'The expedition pressed onward, ______ the blizzard grew fiercer by the hour.',
      ['even as', 'unless', 'in case', 'provided'], 0,
      '"Even as" emphasizes simultaneous ongoing dramatic occurrence.', 'B2 Narrative Connectors'),
    q('conj_b2_9', 'B2', 'matching', 'Matching', 'Understanding',
      'Match the conjunction: "lest" -> what meaning does it convey?',
      ['For fear that / to prevent', 'In the same manner', 'Since that time', 'As a direct result'], 0,
      '"Lest" means for fear that / in order to avoid.', 'Cambridge B2'),
    q('conj_b2_10', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The meeting will proceed whether or not the chairman attends."',
      ['Correct - "whether or not" expresses alternative condition', 'Incorrect'], 0,
      '"Whether or not" (or "whether... or not") introduces alternative conditions.', 'test-english B2'),
    q('conj_b2_11', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'She locked the confidential files in the safe ______ anyone unauthorized should see them.',
      ['lest', 'unless', 'whereas', 'while'], 0,
      '"Lest + should" expresses purpose to prevent an undesirable outcome.', 'B2 Purpose Clauses'),
    q('conj_b2_12', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the error: "He [A: is neither] [B: qualified] [C: and nor] [D: experienced]."',
      ['A: is neither', 'B: qualified', 'C: and nor - "and" is redundant before "nor"!', 'D: experienced'], 2,
      'Say "neither qualified NOR experienced", never *and nor.', 'Correlative Accuracy B2'),
    q('conj_b2_13', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which word functions as a SUBORDINATING conjunction of concession?',
      ['Notwithstanding that', 'Consequently', 'Therefore', 'Thus'], 0,
      '"Notwithstanding that" introduces a subordinate concessive clause (the others are conjunctive adverbs of result).', 'Concessives B2'),
    q('conj_b2_14', 'B2', 'open_bracket', 'Open Bracket', 'Producing',
      'Supply the conjunction: "(Inasmuch / Insomuch) ______ as the evidence is inconclusive, the indictment must be dismissed."',
      ['Inasmuch', 'Insomuch', 'Insofar', 'Incase'], 0,
      '"Inasmuch as" means considering that / since.', 'Legal Connectors B2'),
    q('conj_b2_15', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [you / whether / or / agree / not / policy / this / enforced / be / will]',
      ['Whether you agree or not, this policy will be enforced.', 'This policy will be enforced whether you agree or not.', 'Agree or not whether you this policy will be enforced.', 'Enforced this policy will be whether you agree or not.'], 0,
      'Alternative conditional clause: "Whether you agree or not, this policy will be enforced."', 'Syntax B2')
  );

  // C1 & C2 (20 items: 10 C1 + 10 C2)
  items.push(
    q('conj_c1_1', 'C1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Choose the formal literary inverted conditional replacing "If you should require further information":',
      ['Should you require further information', 'Had you required further information', 'Were you to require further information', 'If requiring further information'], 0,
      '"Should you require..." is the established formal inversion for tentative conditions.', 'Cambridge C1 Advanced'),
    q('conj_c1_2', 'C1', 'open_bracket', 'Open Bracket', 'Producing',
      'Complete the inverted third conditional: "(Had / If) ______ the board been alerted earlier, the insolvency could have been averted."',
      ['Had', 'If', 'Should', 'Were'], 0,
      'Third conditional inversion: "Had the board been alerted earlier...".', 'C1 Inversion'),
    q('conj_c1_3', 'C1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "Were [A: I was] [B: in your position], I [C: would decline] [D: the invitation]."',
      ['A: I was - inverted subjunctive must use "Were I", never *Were I was!', 'B: in your position', 'C: would decline', 'D: the invitation'], 0,
      'Inversion replaces "if": "Were I in your position", not *Were I was.', 'Inverted Subjunctive C1'),
    q('conj_c1_4', 'C1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The treaty shall remain in force, save that either signatory may give six months\' notice of termination."',
      ['Correct - "save that" is a formal statutory conjunction meaning "except that"', 'Incorrect - ungrammatical English'], 0,
      '"Save that" is standard classical legal/formal English meaning "except that".', 'Statutory Register C1'),
    q('conj_c1_5', 'C1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Assemble: [had / we / known / never / would / we / consented / have]',
      ['Had we known, we never would have consented.', 'Never would we have consented had we known.', 'We never would have consented had we known.', 'Consented never would we have had we known.'], 0,
      'Inverted third conditional: "Had we known, we never would have consented."', 'C1 Inversion'),
    q('conj_c1_6', 'C1', 'cloze', 'Cloze Test', 'Understanding',
      'The resolution was adopted, ______ certain delegations registered strong reservations.',
      ['albeit', 'despite', 'because', 'unless'], 0,
      '"Albeit" functions as a formal concessive conjunction/adverb meaning "although / even though".', 'Academic Lexis C1'),
    q('conj_c1_7', 'C1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which connector functions as an EXCLUSIONARY conjunction meaning "except that"?',
      ['Save that', 'Insofar as', 'Inasmuch as', 'Whereas'], 0,
      '"Save that" expresses exception. Insofar as / inasmuch as express degree/cause.', 'C1 Connectors'),
    q('conj_c1_8', 'C1', 'matching', 'Matching', 'Understanding',
      'Match the structure: "Adjective + as/though + subject + verb" (e.g., "Eloquent though he was..."):',
      ['Fronted concessive subordinate clause', 'Relative clause of manner', 'Causal clause of result', 'Conditional clause'], 0,
      'Fronted concessive syntax expressing "although he was eloquent".', 'C1 Syntactic Analysis'),
    q('conj_c1_9', 'C1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'He guarded the manuscript jealously, ______ it fall into unscrupulous hands.',
      ['lest', 'unless', 'whereas', 'whilst'], 0,
      '"Lest + subjunctive" (fall): "lest it fall into unscrupulous hands".', 'C1 Subjunctive Connectors'),
    q('conj_c1_10', 'C1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "Be that as it may, we must proceed with the scheduled hearing."',
      ['Correct - formulaic concessive discourse transition meaning "nevertheless"', 'Incorrect - ungrammatical structure'], 0,
      '"Be that as it may" is an established formulaic concessive idiom.', 'Formulaic Subjunctive C1'),

    // C2 (10 items)
    q('conj_c2_1', 'C2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Identify the archaic conditional conjunction equivalent to "if / provided that" in Shakespearean English:',
      ['An (or An\'t)', 'Lest', 'Save', 'Ere'], 0,
      '"An" (or "An it please you") was the early modern English conjunction meaning "if".', 'Historical Syntax C2'),
    q('conj_c2_2', 'C2', 'open_bracket', 'Open Bracket (Negative Coordinator)', 'Producing',
      'Supply the inverted coordinator: "He gave no reason for his departure, (nor / neither) ______ did he bid farewell."',
      ['nor', 'neither', 'or', 'so'], 0,
      '"Nor + auxiliary inversion": "nor did he bid farewell".', 'C2 Negative Coordination'),
    q('conj_c2_3', 'C2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the subtle defect: "Except [A: if] [B: a treaty] [C: is ratified], it [D: possesses no legal force]."',
      ['A: if - in formal statutory prose, say "Unless a treaty is ratified" or "Except when"!', 'B: a treaty', 'C: is ratified', 'D: possesses no legal force'], 0,
      '"Except if" is colloquial; formal statutory prose demands "Unless a treaty is ratified".', 'C2 Statutory Precision'),
    q('conj_c2_4', 'C2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Reconstruct: [may / as / be / it / that / verdict / the / stands]',
      ['Be that as it may, the verdict stands.', 'The verdict stands, be that as it may.', 'That as it may be, the verdict stands.', 'As it may be that, the verdict stands.'], 0,
      'Classical formulaic concessive: "Be that as it may, the verdict stands."', 'C2 Rhetoric'),
    q('conj_c2_5', 'C2', 'cloze', 'Cloze Test', 'Understanding',
      'The contract is valid ______ the provisions of Clause 12 are observed in full.',
      ['insofar as', 'insomuch', 'wherever', 'whence'], 0,
      '"Insofar as" marks precise conditional applicability.', 'C2 Legal Drafting'),
    q('conj_c2_6', 'C2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which archaic temporal conjunction means "BEFORE"?',
      ['Ere', 'Since', 'Whilst', 'Whereupon'], 0,
      '"Ere" (from Old English ær) is the classical poetic conjunction meaning "before".', 'Archaic Conjunctions C2'),
    q('conj_c2_7', 'C2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'He had scarce set foot upon the shore ______ the tempest broke forth with unprecedented fury.',
      ['ere', 'than', 'while', 'as'], 0,
      '"Scarce... ere / when" is high classical narrative syntax.', 'Classical Prose C2'),
    q('conj_c2_8', 'C2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "Notwithstanding that the evidence was circumstantial, the jury convicted the defendant."',
      ['Correct - "Notwithstanding that" is a formal compound subordinating conjunction of concession', 'Incorrect'], 0,
      '"Notwithstanding that" is standard high-level legal/academic concession.', 'C2 Legal Jurisprudence'),
    q('conj_c2_9', 'C2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "Neither [A: did he call] [B: nor he wrote] [C: to explain] his [D: absence]."',
      ['A: did he call', 'B: nor he wrote - second clause must also be inverted: "nor did he write"!', 'C: to explain', 'D: absence'], 1,
      'Parallelism in correlative negative clauses requires symmetric inversion: "Neither did he call nor did he write".', 'Parallel Inversion C2'),
    q('conj_c2_10', 'C2', 'open_bracket', 'Open Bracket', 'Producing',
      'Complete the inverted counterfactual without "if": "(Were / Had) ______ it not been for your prompt intervention, tragedy would have ensued."',
      ['Had', 'Were', 'Should', 'Could'], 0,
      '"Had it not been for..." is standard inverted counterfactual syntax.', 'Counterfactual Inversion C2')
  );

  return items;
}

module.exports = { getConjunctions };
