// scripts/build_articles_and_tenses.js
// Articles, Tenses Present, Tenses Past, Tenses Future (Topics 9, 10, 11, 12)
const { q } = require('./q_helper');

function getArticles() {
  const items = [];
  // A1 (15 items)
  items.push(
    q('art_a1_1', 'A1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Choose the correct indefinite article based on sound: "She has been waiting here for ______ hour."',
      ['an', 'a', 'the', 'Ø (no article)'], 0,
      '"Hour" begins with an unpronounced silent "h", producing the vowel sound /aʊə/, so it takes "an".', 'British Council A1'),
    q('art_a1_2', 'A1', 'open_bracket', 'Open Bracket', 'Producing',
      'Choose (a / an): "He attends (a / an) ______ university in Phnom Penh."',
      ['a', 'an', 'the', 'Ø'], 0,
      '"University" begins with a consonant glide sound /j/ ("yoo-ni-ver-si-ty"), requiring "a".', 'test-english A1'),
    q('art_a1_3', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "I bought an umbrella yesterday because of the rain."',
      ['Correct - "umbrella" begins with a vowel sound /^/ and takes "an"', 'Incorrect'], 0,
      '"An umbrella" is the correct standard indefinite article.', 'Cambridge A1'),
    q('art_a1_4', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which noun takes the article "AN"?',
      ['Apple', 'Book', 'Computer', 'Desk'], 0,
      '"Apple" begins with vowel /æ/.', 'Wordwall A1'),
    q('art_a1_5', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Look at ______ moon shining in the night sky.',
      ['the', 'a', 'an', 'Ø'], 0,
      'Unique astronomical entities take the definite article "the" ("the moon", "the sun").', 'VOA English A1'),
    q('art_a1_6', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [cat / the / milk / drank / the]',
      ['The cat drank the milk.', 'The milk drank the cat.', 'Cat the drank milk the.', 'The drank cat the milk.'], 0,
      'Subject (The cat) + Verb (drank) + Object (the milk).', 'Bamboozle A1'),
    q('art_a1_7', 'A1', 'checking_error', 'Checking Error', 'Explaining',
      'Find the mistake: "She [A: wants] to become [B: a] [C: engineer] at a [D: technology firm]."',
      ['A: wants', 'B: a - vowel sound "engineer" requires "an"!', 'C: engineer', 'D: technology firm'], 1,
      '"Engineer" begins with a vowel sound /e/, requiring "an engineer".', 'Oxford A1'),
    q('art_a1_8', 'A1', 'matching', 'Matching', 'Memory',
      'Match the article: "European country" ->',
      ['A European country', 'An European country', 'Ø European country', 'The all European country'], 0,
      '"European" begins with the consonant sound /j/ ("yoo-ro-pe-an"), taking "a".', 'Elementary Traps A1'),
    q('art_a1_9', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "Cats like drinking milk."',
      ['Correct - zero article with plural countables and uncountables in general statements', 'Incorrect - say "The cats like the milk"'], 0,
      'Zero article is used when talking about things or animals in general.', 'British Council A1'),
    q('art_a1_10', 'A1', 'open_bracket', 'Open Bracket', 'Producing',
      'Select (a / an): "It was (a / an) ______ honest mistake."',
      ['an', 'a', 'the', 'Ø'], 0,
      '"Honest" has a silent "h", so use "an honest mistake".', 'test-english A1'),
    q('art_a1_11', 'A1', 'cloze', 'Cloze Test', 'Understanding',
      'I saw a dog and a cat. ______ dog was chasing the cat.',
      ['The', 'A', 'An', 'Ø'], 0,
      'Second mention of a previously introduced noun takes "The".', 'Cambridge A1'),
    q('art_a1_12', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which word takes "A" (not "an")?',
      ['House', 'Hour', 'Heir', 'Honor'], 0,
      '"House" has a pronounced consonant /h/. "Hour", "heir", and "honor" have silent "h" and take "an".', 'Wordwall A1'),
    q('art_a1_13', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'We eat ______ breakfast at 7:00 AM every morning.',
      ['Ø (no article)', 'the', 'a', 'an'], 0,
      'Names of general daily meals take the zero article (Ø).', 'VOA English A1'),
    q('art_a1_14', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [earth / the / the / revolves / sun / around]',
      ['The earth revolves around the sun.', 'The sun revolves around the earth.', 'Around the sun revolves the earth.', 'Revolves the earth around the sun.'], 0,
      'Unique cosmic bodies: "The earth revolves around the sun."', 'Syntax A1'),
    q('art_a1_15', 'A1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "She [A: plays] [B: the football] [C: every] [D: Saturday]."',
      ['A: plays', 'B: the football - sports take zero article: "plays football"!', 'C: every', 'D: Saturday'], 1,
      'Names of sports take zero article: "plays football", never *plays the football.', 'Sports Articles A1')
  );

  // A2 (15 items)
  items.push(
    q('art_a2_1', 'A2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Which musical instrument sentence is correct?',
      ['She plays the guitar very well.', 'She plays guitar very well.', 'She plays a guitar very well.', 'She plays an guitar very well.'], 0,
      'Musical instruments when played take the definite article "the": "plays the guitar".', 'British Council A2'),
    q('art_a2_2', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Mount Everest is the highest mountain in ______ Himalayas.',
      ['the', 'Ø', 'a', 'an'], 0,
      'Mountain ranges (plural) take "the" ("the Himalayas", "the Alps"). Individual peaks take zero article ("Mount Everest").', 'test-english A2'),
    q('art_a2_3', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The burglar was sent to the prison for three years."',
      ['Correct', 'Incorrect - institutions visited for their primary purpose take zero article ("sent to prison")'], 1,
      'Primary institutional purpose takes zero article: "sent to prison" (as an inmate).', 'Cambridge A2'),
    q('art_a2_4', 'A2', 'open_bracket', 'Open Bracket (Geographical)', 'Producing',
      'Select (the / Ø): "We spent our holiday in (the / Ø) ______ United Kingdom."',
      ['the', 'Ø', 'a', 'an'], 0,
      'Countries containing "Kingdom", "States", or "Republic" take "the": "the United Kingdom".', 'Oxford A2'),
    q('art_a2_5', 'A2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "We [A: visited] [B: the Mount Fuji] [C: during our trip to] [D: Japan]."',
      ['A: visited', 'B: the Mount Fuji - individual mountain peaks take zero article: "Mount Fuji"!', 'C: during our trip to', 'D: Japan'], 1,
      'Individual mountain peaks do not take "the": "Mount Fuji".', 'Geographical Rules A2'),
    q('art_a2_6', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which country name takes the definite article "THE"?',
      ['Netherlands', 'Cambodia', 'France', 'Japan'], 0,
      'Plural country names take "the": "the Netherlands", "the Philippines".', 'Wordwall A2'),
    q('art_a2_7', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [pacific / is / ocean / ocean / the / largest / the]',
      ['The Pacific Ocean is the largest ocean.', 'The largest ocean is the Pacific Ocean.', 'The Pacific Ocean the largest is ocean.', 'Largest the ocean is the Pacific Ocean.'], 0,
      'Oceans take "the": "The Pacific Ocean is the largest ocean."', 'Syntax A2'),
    q('art_a2_8', 'A2', 'cloze', 'Cloze Test', 'Understanding',
      'The children go to ______ school at 7:30 AM every morning.',
      ['Ø (no article)', 'the', 'a', 'an'], 0,
      'Attending school as students takes zero article: "go to school".', 'Institutional Articles A2'),
    q('art_a2_9', 'A2', 'matching', 'Matching', 'Understanding',
      'Match the body of water: "Mekong River" ->',
      ['The Mekong River', 'Ø Mekong River', 'A Mekong River', 'Some Mekong River'], 0,
      'Rivers always take the definite article "the": "the Mekong River".', 'Cambridge A2'),
    q('art_a2_10', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "The doctor advised him to stay in bed for three days."',
      ['Correct - "in bed" is a fixed zero article phrase for resting/sleeping', 'Incorrect - say "in the bed"'], 0,
      '"In bed" is an established zero article idiomatic collocation.', 'test-english A2'),
    q('art_a2_11', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'She was taken to ______ hospital in an ambulance after the accident.',
      ['Ø (no article)', 'the', 'a', 'an'], 0,
      'In British English, being hospitalized as a patient takes zero article: "taken to hospital".', 'British Council A2'),
    q('art_a2_12', 'A2', 'open_bracket', 'Open Bracket', 'Producing',
      'Supply article: "(The / Ø) ______ Sahara is the largest hot desert in the world."',
      ['The', 'Ø', 'A', 'An'], 0,
      'Deserts take the definite article: "The Sahara Desert".', 'Deserts A2'),
    q('art_a2_13', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which geographical entity takes ZERO ARTICLE (Ø)?',
      ['Lake Superior (individual lake)', 'Amazon River', 'Pacific Ocean', 'Himalayas'], 0,
      'Individual lakes take zero article ("Lake Superior"). Rivers, oceans, and mountain chains take "the".', 'Wordwall A2'),
    q('art_a2_14', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [piano / she / plays / the / evening / every]',
      ['She plays the piano every evening.', 'Every evening she plays the piano.', 'The piano she plays every evening.', 'She every evening plays the piano.'], 0,
      'Musical instruments take "the": "plays the piano".', 'Syntax A2'),
    q('art_a2_15', 'A2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "He [A: travels to] [B: work] [C: by] [D: the bus] every day."',
      ['A: travels to', 'B: work', 'C: by', 'D: the bus - modes of travel with "by" take zero article: "by bus"!'], 3,
      '"By + transport" takes zero article: "by bus", "by train", "by car".', 'Transport Articles A2')
  );

  // B1 (15 items)
  items.push(
    q('art_b1_1', 'B1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Select the sentence with correct generic reference representing a whole species:',
      ['The blue whale is the largest mammal on Earth.', 'A blue whale is largest mammal.', 'Blue whale is the largest mammal.', 'Some blue whale is largest mammal.'], 0,
      '"The + singular countable noun" represents an entire biological species in formal/scientific style.', 'Cambridge B1'),
    q('art_b1_2', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Alexander Graham Bell invented ______ telephone in 1876.',
      ['the', 'a', 'an', 'Ø'], 0,
      'Inventions taken as a cultural/scientific innovation take "the": "invented the telephone".', 'test-english B1'),
    q('art_b1_3', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The unemployment has risen sharply over the last fiscal quarter."',
      ['Correct', 'Incorrect - abstract uncountables used generally take zero article ("Unemployment has risen")'], 1,
      'General abstract concepts take zero article: "Unemployment has risen", not *The unemployment.', 'Oxford B1'),
    q('art_b1_4', 'B1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "He [A: was appointed] [B: the Chairman] of [C: the board of] [D: directors]."',
      ['A: was appointed', 'B: the Chairman - unique institutional roles after "appoint/elect" take zero article: "appointed Chairman"!', 'C: the board of', 'D: directors'], 1,
      'Unique institutional positions after appoint/elect/become omit the article: "appointed Chairman".', 'Unique Roles B1'),
    q('art_b1_5', 'B1', 'open_bracket', 'Open Bracket (Generic Class)', 'Producing',
      'Choose (The / Ø): "(The / Ø) ______ rich should contribute more to public infrastructure."',
      ['The', 'Ø', 'A', 'An'], 0,
      '"The + adjective" represents a whole collective class of people: "The rich".', 'The + Adjective B1'),
    q('art_b1_6', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which noun phrase takes the ZERO ARTICLE (Ø)?',
      ['At dawn', 'In the morning', 'In the afternoon', 'In the evening'], 0,
      '"At dawn", "at dusk", "at noon" take zero article.', 'Wordwall B1'),
    q('art_b1_7', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [is / dolphin / a / highly / intelligent / the / mammal]',
      ['The dolphin is a highly intelligent mammal.', 'A highly intelligent mammal is the dolphin.', 'The mammal is a highly intelligent dolphin.', 'Dolphin the is a highly intelligent mammal.'], 0,
      'Generic reference: "The dolphin is a highly intelligent mammal."', 'Syntax B1'),
    q('art_b1_8', 'B1', 'cloze', 'Cloze Test', 'Understanding',
      'We crossed ______ Alps on our rail journey from Zurich to Milan.',
      ['the', 'Ø', 'a', 'an'], 0,
      'Mountain chains take "the": "the Alps".', 'Geographical Articles B1'),
    q('art_b1_9', 'B1', 'matching', 'Matching', 'Understanding',
      'Match the illness: "have ______ flu"',
      ['have the flu', 'have a flu', 'have Ø flu', 'have an flu'], 0,
      'In standard English, we say "have the flu" (or "have flu").', 'Illnesses B1'),
    q('art_b1_10', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "She plays chess better than anyone else in our club."',
      ['Correct - board games take zero article (Ø)', 'Incorrect - say "plays the chess"'], 0,
      'Board games and sports take zero article: "plays chess".', 'British Council B1'),
    q('art_b1_11', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'He went to the prison to visit ______ brother who was incarcerated there.',
      ['his', 'the', 'a', 'Ø'], 0,
      'When visiting a prison merely as a visitor, the building takes "the" (or possessive "his brother").', 'B1 Institutional Nuance'),
    q('art_b1_12', 'B1', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the error: "They [A: walked] [B: arm in the arm] [C: along] the [D: moonlit beach]."',
      ['A: walked', 'B: arm in the arm - paired coordinates take zero article: "arm in arm"!', 'C: along', 'D: moonlit beach'], 1,
      'Binominal paired idioms omit articles: "arm in arm", "hand in hand".', 'Binominals B1'),
    q('art_b1_13', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which institution takes "THE" when visited as an external visitor rather than for primary purpose?',
      ['The hospital (The architect visited the hospital to inspect renovations)', 'School', 'Church', 'Prison'], 0,
      'All these institutions take "the" when referring specifically to the physical building rather than primary purpose.', 'Wordwall B1'),
    q('art_b1_14', 'B1', 'open_bracket', 'Open Bracket', 'Producing',
      'Select: "(The / Ø) ______ life in Victorian England was difficult for the working class."',
      ['Ø', 'The', 'A', 'An'], 0,
      'When "life" refers to human existence in general, it takes zero article: "Life in Victorian England...".', 'Abstract Articles B1'),
    q('art_b1_15', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [by / travelled / they / through / night / the / forest]',
      ['They travelled through the forest by night.', 'Through the forest they travelled by night.', 'By night they travelled through the forest.', 'They travelled by night through the forest.'], 0,
      'Idiom "by night / by day" takes zero article: "travelled by night".', 'B1 Syntax')
  );

  // B2 (15 items)
  items.push(
    q('art_b2_1', 'B2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Choose the correct article usage for newspapers and periodicals: "I read an editorial in ______ Times yesterday."',
      ['the', 'Ø', 'a', 'an'], 0,
      'Well-known newspapers take the definite article: "The Times", "The Guardian", "The New York Times".', 'Oxford B2'),
    q('art_b2_2', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The cruise ship will dock in ______ Bahamas before crossing the Atlantic.',
      ['the', 'Ø', 'a', 'an'], 0,
      'Island groups (plural) take "the": "the Bahamas", "the Canary Islands".', 'Cambridge B2 First'),
    q('art_b2_3', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "He was elected President of the Royal Geographic Society."',
      ['Correct - unique elected institutional titles omit the article', 'Incorrect - must say "the President"'], 0,
      'Verbs of election/appointment omit the article before unique offices: "elected President".', 'test-english B2'),
    q('art_b2_4', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "She [A: has been studying] [B: the history of] [C: the medieval Europe] [D: for her doctorate]."',
      ['A: has been studying', 'B: the history of', 'C: the medieval Europe - continents take zero article: "medieval Europe"!', 'D: for her doctorate'], 2,
      'Continents, even with pre-modifying adjectives, do not take "the": "medieval Europe", not *the medieval Europe.', 'Geographical Traps B2'),
    q('art_b2_5', 'B2', 'open_bracket', 'Open Bracket', 'Producing',
      'Choose (the / Ø): "He plays (the / Ø) ______ violin in the city symphony orchestra."',
      ['the', 'Ø', 'a', 'an'], 0,
      'Musical instruments take "the": "plays the violin".', 'British Council B2'),
    q('art_b2_6', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which geographical entity takes THE DEFINITE ARTICLE?',
      ['The Hague (city exception)', 'Paris', 'London', 'Berlin'], 0,
      '"The Hague" is one of the rare cities that historically retains "The". Paris, London, Berlin take zero article.', 'Wordwall B2'),
    q('art_b2_7', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Assemble: [toe / inspected / head / the / doctor / from / to / him]',
      ['The doctor inspected him from head to toe.', 'From head to toe the doctor inspected him.', 'The doctor from head to toe inspected him.', 'Inspected him the doctor from head to toe.'], 0,
      'Binominal zero article idiom: "from head to toe".', 'Syntax B2'),
    q('art_b2_8', 'B2', 'cloze', 'Cloze Test', 'Understanding',
      'The treaty was signed in ______ presence of twenty foreign dignitaries.',
      ['the', 'a', 'Ø', 'an'], 0,
      'Fixed formal phrase: "in the presence of".', 'Formal Collocations B2'),
    q('art_b2_9', 'B2', 'matching', 'Matching', 'Understanding',
      'Match: "go to sea" vs "go to the sea". What does "go to sea" mean?',
      ['To become a sailor / mariner as a profession', 'To spend a vacation on the beach', 'To swim in deep water', 'To sail a yacht for an afternoon'], 0,
      '"Go to sea" (zero article) idiomatically means to take up the career of a sailor.', 'Idiomatic Semantics B2'),
    q('art_b2_10', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The man was accused of treason and committed to the Tower of London."',
      ['Correct - historic buildings and monuments take "The"', 'Incorrect'], 0,
      'Historic public monuments take "The": "The Tower of London", "The Colosseum".', 'British Council B2'),
    q('art_b2_11', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
      '______ English spoken in northern regions exhibits distinctive dialectal traits.',
      ['The', 'Ø', 'A', 'An'], 0,
      'When a language is restricted by a post-modifying clause or participle, it takes "The": "The English spoken in...".', 'Restricted Languages B2'),
    q('art_b2_12', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the defect: "He [A: is learning] [B: the French] [C: in order to] [D: study in Paris]."',
      ['A: is learning', 'B: the French - languages take zero article: "learning French"!', 'C: in order to', 'D: study in Paris'], 1,
      'Languages in general take zero article: "learning French", never *learning the French.', 'Languages B2'),
    q('art_b2_13', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which organization takes the DEFINITE ARTICLE?',
      ['The United Nations', 'NATO (acronym pronounced as word)', 'UNESCO', 'OPEC'], 0,
      'Names spelled out or full institutional titles take "The" ("The United Nations"). Acronyms pronounced as single words take zero article (NATO, UNESCO).', 'Institutional Names B2'),
    q('art_b2_14', 'B2', 'open_bracket', 'Open Bracket', 'Producing',
      'Complete with (the / Ø): "They crossed (the / Ø) ______ Lake Geneva on a steamboat."',
      ['Ø', 'the', 'a', 'an'], 0,
      'Lakes preceded by the word "Lake" take zero article: "Lake Geneva".', 'Geographical B2'),
    q('art_b2_15', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [sick / hospital / visited / he / the / the / in]',
      ['He visited the sick in the hospital.', 'In the hospital he visited the sick.', 'He visited in the hospital the sick.', 'The sick he visited in the hospital.'], 0,
      '"The sick" (plural generic class) + "in the hospital".', 'Syntax B2')
  );

  // C1 & C2 (20 items: 10 C1 + 10 C2)
  items.push(
    q('art_c1_1', 'C1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Analyze the generic reference: "The dodo is an extinct flightless bird." What does "The dodo" denote?',
      ['An entire biological species viewed as an intellectual class', 'One specific individual bird in a zoo', 'A metaphorical idiom', 'An indefinite bird'], 0,
      '"The + singular countable" serves as a high formal scientific representative for an entire biological taxon.', 'Cambridge C1 Advanced'),
    q('art_c1_2', 'C1', 'open_bracket', 'Open Bracket (Double Article Contrast)', 'Producing',
      'Supply the articles: "He was elected (Ø / the) ______ President at (the / a) ______ annual general meeting."',
      ['Ø / the', 'the / the', 'a / an', 'the / a'], 0,
      'Unique elected role takes zero article ("elected President"); specific meeting takes "the".', 'C1 Precision Syntax'),
    q('art_c1_3', 'C1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "She [A: was appointed] to [B: the office of] [C: the Prime Minister] [D: yesterday]."',
      ['A: was appointed', 'B: the office of', 'C: the Prime Minister - after "the office of / title of", omit the article: "the office of Prime Minister"!', 'D: yesterday'], 2,
      'Idiom "the office/post/title of Prime Minister" omits the second article.', 'C1 Institutional Collocations'),
    q('art_c1_4', 'C1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "They stood face to face in silent contemplation."',
      ['Correct - paired coordinate binominal phrases omit articles', 'Incorrect - say "the face to the face"'], 0,
      'Binominal paired anatomical idioms strictly omit articles: "face to face", "shoulder to shoulder".', 'Binominals C1'),
    q('art_c1_5', 'C1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Assemble: [little / does / he / consequences / the / realize]',
      ['Little does he realize the consequences.', 'Does he realize little the consequences.', 'The consequences does he little realize.', 'Realize little does he the consequences.'], 0,
      'Adverbial "Little" with negative fronting takes zero determiner: "Little does he realize...".', 'C1 Stylistic Inversion'),
    q('art_c1_6', 'C1', 'cloze', 'Cloze Test', 'Understanding',
      'He assumed the mantle of leadership in ______ wake of the geopolitical crisis.',
      ['the', 'a', 'Ø', 'an'], 0,
      'Fixed formal metaphor: "in the wake of".', 'C1 Idiomatic Lexis'),
    q('art_c1_7', 'C1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which title takes ZERO ARTICLE after the appositive verb "turn"?',
      ['He turned traitor. (zero article)', 'He became a teacher.', 'She remained an architect.', 'They elected him the leader.'], 0,
      '"Turn traitor / turn politician" uses zero article after "turn" denoting sudden change of loyalty or profession.', 'Zero Article Nuance C1'),
    q('art_c1_8', 'C1', 'matching', 'Matching', 'Understanding',
      'Match the structure: "A lion is a dangerous animal" vs "The lion is an endangered species":',
      ['"A lion" generalizes by any typical specimen; "The lion" generalizes by the whole taxon class', 'They are strictly identical in register', 'Only "The lion" is grammatical', 'Only "A lion" is grammatical'], 0,
      'Generic "a" refers to any individual exemplar; generic "the" refers to the abstract taxonomic category.', 'Theoretical Semantics C1'),
    q('art_c1_9', 'C1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The council met behind ______ closed doors to deliberate the sensitive verdict.',
      ['Ø (no article)', 'the', 'a', 'an'], 0,
      'Fixed idiom: "behind closed doors" (zero article).', 'C1 Idiomatic Expressions'),
    q('art_c1_10', 'C1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "Man is mortal and subject to the immutable laws of nature."',
      ['Correct - "Man" without an article represents the human race universally in classical philosophy', 'Incorrect - say "The man"'], 0,
      'In classical philosophical prose, "Man" (zero article, capitalized) denotes humanity as a whole.', 'Philosophical English C1'),

    // C2 (10 items)
    q('art_c2_1', 'C2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Select the sentence exhibiting zero article in classical rhetorical parallelism:',
      ['Father and son stood united against the tempest.', 'The father and the son stood united.', 'A father and a son stood united.', 'The father and a son stood united.'], 0,
      'Paired coordinate kinship nouns omit articles in elevated and poetic prose: "Father and son stood united".', 'C2 Poetic & Classical Syntax'),
    q('art_c2_2', 'C2', 'open_bracket', 'Open Bracket (Statutory Omission)', 'Producing',
      'Supply the zero article in statutory legal style: "Notice is hereby given to (the / Ø) ______ purchaser of record."',
      ['Ø', 'the', 'a', 'an'], 0,
      'High statutory legal drafting regularly dispenses with articles before functional parties: "purchaser of record", "landlord", "tenant".', 'Statutory Drafting C2'),
    q('art_c2_3', 'C2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the subtle defect: "He [A: was sentenced] [B: to the prison] [C: for the term of] [D: his natural life]."',
      ['A: was sentenced', 'B: to the prison - criminal incarceration requires zero article: "sentenced to prison"!', 'C: for the term of', 'D: his natural life'], 1,
      'Judicial sentences omit the article: "sentenced to prison", not *to the prison.', 'C2 Legal Incarceration Formulas'),
    q('art_c2_4', 'C2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Reconstruct: [hand / they / walked / hand / in / through / meadows / the]',
      ['They walked hand in hand through the meadows.', 'Hand in hand they walked through the meadows.', 'Through the meadows they walked hand in hand.', 'They through the meadows walked hand in hand.'], 0,
      'Binominal zero article: "hand in hand".', 'C2 Stylistics'),
    q('art_c2_5', 'C2', 'cloze', 'Cloze Test', 'Understanding',
      'The treaty was drafted in ______ haste, resulting in numerous interpretive ambiguities.',
      ['Ø (no article)', 'the', 'a', 'an'], 0,
      '"In haste" (or "in great haste") is an adverbial prepositional phrase with zero article.', 'Idiomatic Prepositionals C2'),
    q('art_c2_6', 'C2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which noun phrase features an INCORPORATED ZERO ARTICLE?',
      ['Leave town (e.g. He decided to leave town)', 'Leave the town', 'Leave a town', 'Leave this town'], 0,
      '"Leave town" is an idiom with an incorporated zero article.', 'Syntactic Incorporation C2'),
    q('art_c2_7', 'C2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The suspect was caught in ______ flagrante delicto.',
      ['Ø (no article)', 'the', 'a', 'an'], 0,
      'Latin legal maxims take zero English articles.', 'Latin Maxims C2'),
    q('art_c2_8', 'C2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "Day by day and night by night, the vigilant sentinels kept watch."',
      ['Correct - paired temporal reduplication takes zero article', 'Incorrect'], 0,
      '"Day by day and night by night" strictly takes zero article.', 'Reduplication C2'),
    q('art_c2_9', 'C2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "She [A: was appointed] [B: to the position of] [C: the Chief Justice] [D: of the Supreme Court]."',
      ['A: was appointed', 'B: to the position of', 'C: the Chief Justice - "the position of Chief Justice"!', 'D: of the Supreme Court'], 2,
      '"The position of Chief Justice" omits the second article.', 'C2 Office Titles'),
    q('art_c2_10', 'C2', 'open_bracket', 'Open Bracket', 'Producing',
      'Complete the formal zero-article phrase: "(At / In) ______ close quarters, swordplay demanded extraordinary agility."',
      ['At', 'In', 'On', 'With'], 0,
      '"At close quarters" is the fixed zero article military/combat idiom.', 'C2 Idioms')
  );

  return items;
}

module.exports = { getArticles };
