// scripts/build_tenses.js
// English Tenses: Present, Past, Future (Topics 10, 11, 12)
const { q } = require('./q_helper');

function getTensesPresent() {
  const items = [];
  // A1 (15 items)
  items.push(
    q('t_pres_a1_1', 'A1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Choose the Present Simple for habits: "She ______ coffee every morning at breakfast."',
      ['drinks', 'drink', 'is drinking', 'drinking'], 0,
      'Third-person singular "She" takes "-s" in the Present Simple: "drinks".', 'British Council A1'),
    q('t_pres_a1_2', 'A1', 'open_bracket', 'Open Bracket (Present Simple)', 'Producing',
      'Conjugate the verb in brackets: "They (live) ______ in a quiet neighborhood near the river."',
      ['live', 'lives', 'living', 'are live'], 0,
      '"They" takes the base form: "live".', 'test-english A1'),
    q('t_pres_a1_3', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "The sun rises in the east and sets in the west."',
      ['Correct - scientific and universal facts take the Present Simple', 'Incorrect'], 0,
      'Universal natural laws and permanent facts require the Present Simple.', 'Cambridge A1'),
    q('t_pres_a1_4', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which time expression is typical of the PRESENT CONTINUOUS?',
      ['Right now', 'Every day', 'Usually', 'On Sundays'], 0,
      '"Right now" indicates an action in progress now. Every day, usually, on Sundays are for habits (Present Simple).', 'Wordwall A1'),
    q('t_pres_a1_5', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Listen! The birds ______ sweetly in the trees.',
      ['are singing', 'sing', 'sings', 'sang'], 0,
      'Signal word "Listen!" indicates action happening right now: "are singing".', 'VOA English A1'),
    q('t_pres_a1_6', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [works / hospital / a / in / brother / my]',
      ['My brother works in a hospital.', 'My brother in a hospital works.', 'In a hospital works my brother.', 'Works my brother in a hospital.'], 0,
      'Subject (My brother) + Verb (works) + Place (in a hospital).', 'Bamboozle A1'),
    q('t_pres_a1_7', 'A1', 'checking_error', 'Checking Error', 'Explaining',
      'Find the mistake: "She [A: don\'t] [B: work] on [C: Saturday] [D: mornings]."',
      ['A: don\'t', 'B: work', 'C: Saturday', 'D: mornings'], 0,
      '"She" requires the auxiliary "doesn\'t": "She DOESN\'T work".', 'Oxford A1'),
    q('t_pres_a1_8', 'A1', 'matching', 'Matching', 'Memory',
      'Match the question form: "Where (live / do / you)?"',
      ['Where do you live?', 'Where you live?', 'Where does you live?', 'Where are you live?'], 0,
      'Interrogative: Wh-word + do + subject (you) + base verb (live)?', 'Elementary Questions A1'),
    q('t_pres_a1_9', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "I am understanding the lesson now."',
      ['Incorrect - "understand" is a stative verb of mental state and takes simple aspect ("I understand")', 'Correct'], 0,
      'Stative verbs of cognition (understand, know, realize) do not take continuous aspect: "I understand now".', 'British Council A1'),
    q('t_pres_a1_10', 'A1', 'open_bracket', 'Open Bracket (Present Continuous)', 'Producing',
      'Form Present Continuous: "Be quiet! The baby (sleep) ______ in the cradle."',
      ['is sleeping', 'sleeps', 'is sleep', 'are sleeping'], 0,
      'Temporary action in progress: "is sleeping".', 'test-english A1'),
    q('t_pres_a1_11', 'A1', 'cloze', 'Cloze Test', 'Understanding',
      'Water ______ at 100 degrees Celsius under normal atmospheric pressure.',
      ['boils', 'is boiling', 'boil', 'boiled'], 0,
      'Scientific fact takes Present Simple: "boils".', 'Cambridge A1'),
    q('t_pres_a1_12', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which verb is a STATIVE verb that normally avoids the -ing form?',
      ['Know', 'Run', 'Sing', 'Dance'], 0,
      '"Know" is stative (e.g. "I know him", never *"I am knowing him").', 'Wordwall A1'),
    q('t_pres_a1_13', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Where is Peter? — He ______ dinner in the kitchen.',
      ['is cooking', 'cooks', 'cooked', 'cook'], 0,
      'Action in progress at the time of speaking: "is cooking".', 'VOA English A1'),
    q('t_pres_a1_14', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [at / they / having / lunch / are / moment / the]',
      ['They are having lunch at the moment.', 'At the moment are they having lunch.', 'They at the moment are having lunch.', 'Having lunch are they at the moment.'], 0,
      '"At the moment" signals Present Continuous: "They are having lunch at the moment."', 'Syntax A1'),
    q('t_pres_a1_15', 'A1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "He [A: is wanting] [B: to buy] [C: a new] [D: bicycle]."',
      ['A: is wanting - "want" is a stative verb: say "He wants"!', 'B: to buy', 'C: a new', 'D: bicycle'], 0,
      'Stative verb "want" takes Present Simple: "He wants to buy", not *is wanting.', 'Stative Verbs A1')
  );

  // A2 (15 items)
  items.push(
    q('t_pres_a2_1', 'A2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Choose the Present Perfect for an unfinished experience in life: "______ you ever ______ to Angkor Wat?"',
      ['Have / been', 'Did / go', 'Are / going', 'Do / go'], 0,
      '"Have you ever been...?" asks about life experience up to the present.', 'test-english A2'),
    q('t_pres_a2_2', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'I ______ three emails so far this morning.',
      ['have written', 'wrote', 'am writing', 'had written'], 0,
      '"So far this morning" is an unfinished time period connecting to the present: Present Perfect "have written".', 'Cambridge A2'),
    q('t_pres_a2_3', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "I have lived in Phnom Penh since five years."',
      ['Correct', 'Incorrect - duration of time takes "for", not "since" ("for five years")'], 1,
      '"For" is used with periods/durations (five years); "since" takes specific points in time (since 2019).', 'British Council A2'),
    q('t_pres_a2_4', 'A2', 'open_bracket', 'Open Bracket (Present Perfect)', 'Producing',
      'Conjugate: "She (not / finish) ______ her science assignment yet."',
      ['has not finished', 'did not finish', 'have not finished', 'is not finishing'], 0,
      '"Yet" at the end of a negative sentence takes the Present Perfect: "has not finished".', 'Oxford A2'),
    q('t_pres_a2_5', 'A2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "I [A: have visited] [B: Angkor Wat] [C: two years ago] [D: with my family]."',
      ['A: have visited - specific past time "two years ago" requires Past Simple "visited"!', 'B: Angkor Wat', 'C: two years ago', 'D: with my family'], 0,
      'Specific completed past time expressions (yesterday, two years ago, in 2020) require the Past Simple, never the Present Perfect.', 'Past vs Present Perfect A2'),
    q('t_pres_a2_6', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which time marker pairs with the PRESENT PERFECT SIMPLE?',
      ['Already', 'Yesterday', 'Last night', 'In 1999'], 0,
      '"Already", "yet", "just", "ever", "never", "since", "for" pair with the Present Perfect.', 'Wordwall A2'),
    q('t_pres_a2_7', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [seen / film / that / already / I / have]',
      ['I have already seen that film.', 'Already I have seen that film.', 'I have seen already that film.', 'That film I have already seen.'], 0,
      'Adverb "already" sits between auxiliary and past participle: "have already seen".', 'Syntax A2'),
    q('t_pres_a2_8', 'A2', 'cloze', 'Cloze Test', 'Understanding',
      'How long ______ your English teacher?',
      ['have you known', 'did you know', 'are you knowing', 'do you know'], 0,
      '"How long have you known...?" asks about duration from the past to the present with a stative verb.', 'test-english A2'),
    q('t_pres_a2_9', 'A2', 'matching', 'Matching', 'Understanding',
      'Match: "just" in Present Perfect ->',
      ['Action completed a very short time ago', 'Action that has not happened yet', 'Action at an exact clock time', 'Action happening right now'], 0,
      '"Just" indicates very recent completion: "I have just arrived".', 'Cambridge A2'),
    q('t_pres_a2_10', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "The train departs at 6:30 tomorrow morning."',
      ['Correct - Present Simple expresses fixed public timetables in the future', 'Incorrect - future must use "will"'], 0,
      'Official timetables, schedules, and public itineraries use the Present Simple for future time.', 'Timetable Future A2'),
    q('t_pres_a2_11', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'We ______ each other since our elementary school days.',
      ['have known', 'knew', 'are knowing', 'know'], 0,
      'Duration up to now with stative verb "know": "have known".', 'British Council A2'),
    q('t_pres_a2_12', 'A2', 'open_bracket', 'Open Bracket', 'Producing',
      'Conjugate: "He (already / eat) ______ lunch, so he is not hungry now."',
      ['has already eaten', 'already ate', 'have already eaten', 'is already eating'], 0,
      'Result in the present: "has already eaten".', 'Oxford A2'),
    q('t_pres_a2_13', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which sentence uses Present Simple for a TIMETABLED future event?',
      ['The flight leaves at 9:00 AM tomorrow.', 'I am meeting John tomorrow.', 'It will rain tomorrow.', 'I am going to study tomorrow.'], 0,
      '"The flight leaves..." represents an official public schedule.', 'Wordwall A2'),
    q('t_pres_a2_14', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [arrived / has / plane / the / just / ?]',
      ['Has the plane just arrived?', 'The plane has just arrived?', 'Just arrived has the plane?', 'Has just the plane arrived?'], 0,
      'Interrogative: Has + subject (the plane) + just + past participle (arrived)?', 'Syntax A2'),
    q('t_pres_a2_15', 'A2', 'checking_error', 'Checking Error', 'Explaining',
      'Find the mistake: "She [A: has lived] in [B: London] [C: since] [D: three years]."',
      ['A: has lived', 'B: London', 'C: since - periods of duration take "for three years"!', 'D: three years'], 2,
      '"Since" marks points in time (since 2021); duration takes "for": "FOR three years".', 'Since vs For A2')
  );

  // B1 (15 items)
  items.push(
    q('t_pres_b1_1', 'B1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Choose the Present Perfect Continuous for an action with evident physical results: "Her hands are covered in paint because she ______ the kitchen."',
      ['has been painting', 'has painted', 'painted', 'is painting'], 0,
      'The continuous aspect emphasizes the ongoing physical activity that caused the present visible result.', 'Cambridge B1'),
    q('t_pres_b1_2', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'How long ______ for the delayed train? — For over forty-five minutes!',
      ['have you been waiting', 'have you waited', 'did you wait', 'are you waiting'], 0,
      'Focusing on the ongoing duration of waiting up to the present: "have you been waiting".', 'test-english B1'),
    q('t_pres_b1_3', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "I have been writing ten letters this morning."',
      ['Incorrect - completed quantities/numbers require the Present Perfect Simple ("have written ten letters")', 'Correct'], 0,
      'When stating the completed quantity or number of items produced (ten letters), use the Simple aspect: "have written".', 'Oxford B1'),
    q('t_pres_b1_4', 'B1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "She [A: has been knowing] him [B: since] they [C: were] [D: children]."',
      ['A: has been knowing - "know" is a stative verb and cannot take continuous aspect: "has known"!', 'B: since', 'C: were', 'D: children'], 0,
      'Stative verbs cannot be used in continuous aspect: "has known", not *has been knowing.', 'Stative Present Perfect B1'),
    q('t_pres_b1_5', 'B1', 'open_bracket', 'Open Bracket', 'Producing',
      'Conjugate: "The ground is wet because it (rain) ______ for hours."',
      ['has been raining', 'has rained', 'is raining', 'rained'], 0,
      'Ongoing process with evident present result: "has been raining".', 'British Council B1'),
    q('t_pres_b1_6', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which verb CANNOT be used in the Present Perfect Continuous?',
      ['Belong (stative)', 'Wait', 'Work', 'Study'], 0,
      '"Belong" is stative of ownership and takes simple aspect: "has belonged".', 'Wordwall B1'),
    q('t_pres_b1_7', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [working / here / has / she / been / morning / all]',
      ['She has been working here all morning.', 'She here has been working all morning.', 'All morning she has been working here.', 'Working here she has been all morning.'], 0,
      'Subject (She) + has been working + Place (here) + Duration (all morning).', 'Syntax B1'),
    q('t_pres_b1_8', 'B1', 'cloze', 'Cloze Test', 'Understanding',
      'As soon as he ______ at the venue, please notify the director.',
      ['arrives', 'will arrive', 'is arriving', 'has arrived'], 0,
      'Future time clauses with "as soon as" take the Present Simple (never "will"): "arrives".', 'test-english B1'),
    q('t_pres_b1_9', 'B1', 'matching', 'Matching', 'Understanding',
      'Match the aspect: "I have read that novel" vs "I have been reading that novel":',
      ['"have read" = completed action; "have been reading" = ongoing activity/process', 'They are strictly synonymous', 'Only "have read" is correct', 'Only "have been reading" is correct'], 0,
      'Simple aspect emphasizes completion/achievement; Continuous aspect emphasizes process/duration.', 'Cambridge B1'),
    q('t_pres_b1_10', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "When the conference will end tomorrow, we will celebrate."',
      ['Incorrect - subordinate time clauses introduced by "when" take the present simple ("ends"), not "will end"', 'Correct'], 0,
      'Do not use "will" in temporal subordinate clauses: "When the conference ENDS...".', 'Time Clauses B1'),
    q('t_pres_b1_11', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Why are you out of breath? — Because I ______ all the way from the bus stop.',
      ['have been running', 'have run', 'ran', 'was running'], 0,
      'Continuous aspect highlights the physical exertion producing the present panting: "have been running".', 'British Council B1'),
    q('t_pres_b1_12', 'B1', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the error: "He [A: has been smoking] [B: twenty cigarettes] [C: today] [D: already]."',
      ['A: has been smoking - stated quantity "twenty cigarettes" requires Simple: "has smoked"!', 'B: twenty cigarettes', 'C: today', 'D: already'], 0,
      'When specifying how many times or how many items (quantity), use Present Perfect Simple: "has smoked".', 'Quantity vs Duration B1'),
    q('t_pres_b1_13', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which time expression introduces a FUTURE TIME CLAUSE taking the present tense?',
      ['The moment that...', 'In the past', 'Two years ago', 'Last decade'], 0,
      '"The moment that..." introduces a subordinate time clause taking the Present Simple.', 'Wordwall B1'),
    q('t_pres_b1_14', 'B1', 'open_bracket', 'Open Bracket', 'Producing',
      'Conjugate: "I (study) ______ French for six months, but I still struggle with pronunciation."',
      ['have been studying', 'am studying', 'studied', 'study'], 0,
      'Duration up to now: "have been studying".', 'Oxford B1'),
    q('t_pres_b1_15', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [you / what / doing / been / have / morning / all / ?]',
      ['What have you been doing all morning?', 'All morning what have you been doing?', 'What have doing you been all morning?', 'Have you been doing what all morning?'], 0,
      'Interrogative: What + have + you + been doing + all morning?', 'Syntax B1')
  );

  // B2 (15 items)
  items.push(
    q('t_pres_b2_1', 'B2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Analyze the stative verb dynamic shift: "The chef ______ the soup to check the seasoning."',
      ['is tasting', 'tastes', 'has tasted', 'taste'], 0,
      'When "taste" denotes deliberate physical action (sampling), it functions dynamically and can take progressive -ing.', 'Cambridge B2 First'),
    q('t_pres_b2_2', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'I ______ of moving to a quieter town outside the capital.',
      ['am thinking', 'think', 'thought', 'have thought'], 0,
      '"Thinking of + gerund" denotes active mental contemplation/deliberation.', 'test-english B2'),
    q('t_pres_b2_3', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "He is always interrupting people during staff meetings."',
      ['Correct - "always + continuous" expresses speaker annoyance or characteristic behavior', 'Incorrect - "always" must only take simple present'], 0,
      'Progressive with "always / continually" idiomatically conveys speaker exasperation or critical hyperbole.', 'Oxford B2'),
    q('t_pres_b2_4', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "This is the first time I [A: am seeing] [B: such] a magnificent [C: ancient] [D: temple]."',
      ['A: am seeing - the structure "This is the first time..." requires Present Perfect: "have seen"!', 'B: such', 'C: ancient', 'D: temple'], 0,
      '"This is the first/second time + Subject + Present Perfect": "have seen".', 'First Time Structure B2'),
    q('t_pres_b2_5', 'B2', 'open_bracket', 'Open Bracket (Aspect Shift)', 'Producing',
      'Conjugate: "I (have) ______ lunch with the regional director tomorrow afternoon."',
      ['am having', 'have', 'have had', 'will have had'], 0,
      '"Have" dynamically meaning "eat / attend a meeting" takes continuous for future arrangement: "am having lunch".', 'Dynamic Shifts B2'),
    q('t_pres_b2_6', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which verb shifts meaning between stative perception and dynamic action?',
      ['Smell (The rose smells sweet / He is smelling the rose)', 'Arrive', 'Destroy', 'Construct'], 0,
      '"Smell", "taste", "look", "feel" shift between stative sensation and active dynamic examination.', 'Stative-Dynamic B2'),
    q('t_pres_b2_7', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Assemble: [continually / complaining / is / he / about / workload / his]',
      ['He is continually complaining about his workload.', 'Continually he is complaining about his workload.', 'About his workload he is continually complaining.', 'He complaining is continually about his workload.'], 0,
      'Continuous with frequency adverb: "He is continually complaining...".', 'Syntax B2'),
    q('t_pres_b2_8', 'B2', 'cloze', 'Cloze Test', 'Understanding',
      'This is the third time the server ______ this week.',
      ['has crashed', 'crashes', 'is crashing', 'crashed'], 0,
      '"This is the third time..." requires Present Perfect Simple: "has crashed".', 'B2 Structures'),
    q('t_pres_b2_9', 'B2', 'matching', 'Matching', 'Understanding',
      'Match: "I see what you mean" vs "I am seeing the doctor tomorrow":',
      ['"I see" = understand (stative); "I am seeing" = meeting/consulting (dynamic arrangement)', 'Both are stative', 'Both are dynamic', 'Only the first is correct'], 0,
      'Semantic shift of "see": mental comprehension vs scheduled appointment.', 'Semantics B2'),
    q('t_pres_b2_10', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The committee has been deciding on the merger proposal for months."',
      ['Incorrect - "decide" is a punctual/achievement verb; say "has been deliberating" or "has decided"', 'Correct'], 0,
      'Punctual verbs (decide, break, arrive) resist continuous duration unless expressing repeated attempts; use "has been deliberating".', 'Punctual vs Durative B2'),
    q('t_pres_b2_11', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Unless the witness ______ under oath, her testimony cannot be admitted.',
      ['testifies', 'will testify', 'is testifying', 'testified'], 0,
      'Conditional clause with "unless" takes Present Simple: "testifies".', 'B2 Conditions'),
    q('t_pres_b2_12', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "She [A: is resembling] [B: her grandmother] in [C: both] appearance [D: and demeanor]."',
      ['A: is resembling - "resemble" is strictly stative: "resembles"!', 'B: her grandmother', 'C: both', 'D: and demeanor'], 0,
      '"Resemble" is an uninflectable stative middle verb: "resembles", never *is resembling.', 'Stative Middle Verbs B2'),
    q('t_pres_b2_13', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which verb CANNOT be used dynamically with progressive aspect?',
      ['Possess (ownership)', 'Have (eating/partying)', 'Think (contemplating)', 'Taste (sampling)'], 0,
      '"Possess" is strictly stative and never takes progressive (*"I am possessing a car").', 'Wordwall B2'),
    q('t_pres_b2_14', 'B2', 'open_bracket', 'Open Bracket', 'Producing',
      'Conjugate: "It is essential that she (be) ______ present at the deposition."',
      ['be', 'is', 'was', 'are'], 0,
      'Mandative subjunctive with "essential": base form "be".', 'Subjunctive B2'),
    q('t_pres_b2_15', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [time / is / this / the / has / broken / first / promise / he / a]',
      ['This is the first time he has broken a promise.', 'He has broken a promise this is the first time.', 'The first time this is he has broken a promise.', 'A promise this is the first time he has broken.'], 0,
      '"This is the first time + Present Perfect": "This is the first time he has broken a promise."', 'Syntax B2')
  );

  // C1 & C2 (20 items: 10 C1 + 10 C2)
  items.push(
    q('t_pres_c1_1', 'C1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Analyze the HISTORIC PRESENT in storytelling: "Suddenly the door flies open and this mysterious figure steps into the tavern." What is its rhetorical effect?',
      ['It brings past narrative events dramatically into the immediate psychological present', 'It denotes a future scheduled appointment', 'It expresses habitual action', 'It describes a hypothetical condition'], 0,
      'The historic present creates narrative immediacy and dramatic suspense in literary prose.', 'Cambridge C1 Advanced'),
    q('t_pres_c1_2', 'C1', 'open_bracket', 'Open Bracket', 'Producing',
      'Conjugate performative verb: "I hereby (pronounce) ______ you husband and wife."',
      ['pronounce', 'am pronouncing', 'have pronounced', 'will pronounce'], 0,
      'Explicit performative speech acts executing an institutional action require the simple present: "I hereby pronounce".', 'Speech Acts C1'),
    q('t_pres_c1_3', 'C1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "I am [A: hereby resigning] [B: from my position] [C: as director] [D: of the board]."',
      ['A: hereby resigning - performatives take simple present: "I hereby RESIGN"!', 'B: from my position', 'C: as director', 'D: of the board'], 0,
      'Performatives with "hereby" (resign, declare, swear) take simple present: "I hereby resign".', 'Performatives C1'),
    q('t_pres_c1_4', 'C1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The ambassador is to meet with the foreign secretary in Brussels on Thursday."',
      ['Correct - "be to + infinitive" expresses formal diplomatic arrangement/decree', 'Incorrect'], 0,
      '"Be to + infinitive" is standard high-register syntax for official diplomatic schedules.', 'Official Schedules C1'),
    q('t_pres_c1_5', 'C1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Assemble: [resign / hereby / from / I / office / public]',
      ['I hereby resign from public office.', 'From public office I hereby resign.', 'Hereby I resign from public office.', 'Resign I hereby from public office.'], 0,
      'Performative declaration: "I hereby resign from public office."', 'C1 Syntax'),
    q('t_pres_c1_6', 'C1', 'cloze', 'Cloze Test', 'Understanding',
      'Shakespeare ______ human nature with unparalleled psychological acuity.',
      ['portrays', 'is portraying', 'was portrayed', 'has been portraying'], 0,
      'Literary/critical present tense discusses ongoing works of literature: "Shakespeare portrays...".', 'Critical Present C1'),
    q('t_pres_c1_7', 'C1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which verb is an EXPLICIT PERFORMATIVE verb?',
      ['Declare (I declare the assembly open)', 'Swim', 'Contemplate', 'Reflect'], 0,
      '"Declare" performs the act in the utterance itself (performative verb).', 'Linguistic Pragmatics C1'),
    q('t_pres_c1_8', 'C1', 'matching', 'Matching', 'Understanding',
      'Match the discourse present: "The report states that revenue has increased." Why is "states" in the present?',
      ['Timeless documentary present in academic citations', 'The report is speaking right now', 'Historic narrative fiction', 'Future schedule'], 0,
      'Timeless documentary present is standard when citing texts, articles, and research reports.', 'Academic Citation C1'),
    q('t_pres_c1_9', 'C1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The treaty ______ that all prisoners of war shall be repatriated immediately.',
      ['stipulates', 'is stipulating', 'has been stipulating', 'stipulatedly'], 0,
      'Formal statutory present: "The treaty stipulates that...".', 'C1 Legal Lexis'),
    q('t_pres_c1_10', 'C1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "Newton posits that an object remains at rest unless acted upon by an external force."',
      ['Correct - timeless scientific/academic present', 'Incorrect - Newton lived in the 17th century so it must be past'], 0,
      'Academic citation convention represents established scientific laws in the timeless present.', 'Academic Discourse C1'),

    // C2 (10 items)
    q('t_pres_c2_1', 'C2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'In theoretical linguistics, what distinguishes the "instantaneous present" from the "habitual present"?',
      ['The instantaneous present describes events synchronized precisely with the speech event (e.g. sports commentary or stage directions)', 'It describes ancient mythology', 'It is an archaic dialect', 'It only occurs with negative polarity'], 0,
      'The instantaneous present (e.g. "Messi passes to Iniesta and he scores!") coincides with the moment of utterance.', 'C2 Theoretical Linguistics'),
    q('t_pres_c2_2', 'C2', 'open_bracket', 'Open Bracket (Stage Direction)', 'Producing',
      'Complete the dramatic stage direction: "Hamlet (enter) ______ carrying an unread manuscript."',
      ['enters', 'is entering', 'entered', 'has entered'], 0,
      'Theatrical stage directions strictly employ the simple present: "Hamlet enters".', 'Dramatic Present C2'),
    q('t_pres_c2_3', 'C2', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the defect: "The constitution [A: provides that] sovereignty [B: resides] in the people, who [C: exercises it] [D: through representatives]."',
      ['A: provides that', 'B: resides', 'C: exercises it - antecedent "the people" takes plural "exercise it"!', 'D: through representatives'], 2,
      '"The people" is plural: "who EXERCISE it", not *exercises.', 'C2 Statutory Concord'),
    q('t_pres_c2_4', 'C2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Reconstruct: [enters / dagger / Macbeth / bearing / drawn / a]',
      ['Macbeth enters, bearing a drawn dagger.', 'Bearing a drawn dagger Macbeth enters.', 'A drawn dagger Macbeth enters bearing.', 'Enters Macbeth bearing a drawn dagger.'], 0,
      'Classical theatrical present: "Macbeth enters, bearing a drawn dagger."', 'C2 Drama'),
    q('t_pres_c2_5', 'C2', 'cloze', 'Cloze Test', 'Understanding',
      'I hereby ______ that the statements submitted herein are true and accurate to the best of my knowledge.',
      ['attest', 'am attesting', 'have attested', 'attested'], 0,
      'Legal performative: "I hereby attest".', 'C2 Legal Drafting'),
    q('t_pres_c2_6', 'C2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which verb serves as an ASCRIPTIVE performative?',
      ['Bequeath (I bequeath my estate to my daughter)', 'Run', 'Sing', 'Climb'], 0,
      '"Bequeath" is a legal performative disposing of property.', 'C2 Legal Verbs'),
    q('t_pres_c2_7', 'C2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The philosopher argues that virtue ______ its own reward.',
      ['is', 'was', 'has been', 'being'], 0,
      'Timeless proverbial truth in academic discourse: "is".', 'Philosophical Discourse C2'),
    q('t_pres_c2_8', 'C2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "I name this vessel \'HMS Sovereign\'."',
      ['Correct - classical performative christening speech act', 'Incorrect'], 0,
      'Performative speech act executing the naming of a ship.', 'Speech Acts C2'),
    q('t_pres_c2_9', 'C2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "The treaty [A: stipulates that] neither signatory [B: have] the authority to [C: deploy armaments] [D: unilaterally]."',
      ['A: stipulates that', 'B: have - "neither signatory" requires singular "HAS"!', 'C: deploy armaments', 'D: unilaterally'], 1,
      '"Neither signatory" is singular and takes "has".', 'C2 Statutory Grammar'),
    q('t_pres_c2_10', 'C2', 'open_bracket', 'Open Bracket', 'Producing',
      'Conjugate performative: "We, the jury, (find) ______ the defendant not guilty as charged."',
      ['find', 'are finding', 'have found', 'found'], 0,
      'Juridical performative verdict: "find".', 'C2 Jurisprudence')
  );

  return items;
}

module.exports = { getTensesPresent };
