// scripts/build_past_future.js
// Tenses Past & Tenses Future (Topics 11 & 12)
const { q } = require('./q_helper');

function getTensesPast() {
  const items = [];
  // A1 (15 items)
  items.push(
    q('t_past_a1_1', 'A1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'What is the past simple of the irregular verb "buy"?',
      ['bought', 'buyed', 'boated', 'boughten'], 0,
      '"Buy" is irregular: past tense is "bought".', 'British Council A1'),
    q('t_past_a1_2', 'A1', 'open_bracket', 'Open Bracket', 'Producing',
      'Conjugate into Past Simple: "Yesterday, she (visit) ______ her grandmother."',
      ['visited', 'visitted', 'visiting', 'visit'], 0,
      'Regular verb adds -ed: "visited".', 'test-english A1'),
    q('t_past_a1_3', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "We didn\'t went to the park yesterday."',
      ['Incorrect - auxiliary "didn\'t" takes bare infinitive: "didn\'t go"', 'Correct'], 0,
      'Negative Past Simple uses "didn\'t + base form": "didn\'t go".', 'Cambridge A1'),
    q('t_past_a1_4', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which verb has an IRREGULAR past form?',
      ['See (saw)', 'Watch (watched)', 'Clean (cleaned)', 'Open (opened)'], 0,
      '"See" -> "saw" is irregular.', 'Wordwall A1'),
    q('t_past_a1_5', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Where ______ you last night at eight o\'clock?',
      ['were', 'was', 'are', 'did'], 0,
      'Plural/second-person "you" takes "were" in the past: "Where were you?".', 'VOA English A1'),
    q('t_past_a1_6', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [saw / yesterday / an / elephant / we]',
      ['We saw an elephant yesterday.', 'Yesterday saw we an elephant.', 'An elephant saw we yesterday.', 'We yesterday an elephant saw.'], 0,
      'Subject (We) + Past verb (saw) + Object (an elephant) + Time (yesterday).', 'Bamboozle A1'),
    q('t_past_a1_7', 'A1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "Did you [A: ate] [B: dinner] [C: with] your [D: friends]?"',
      ['A: ate - questions with "Did" take base verb "eat"!', 'B: dinner', 'C: with', 'D: friends'], 0,
      'Say "Did you EAT", not *did you ate.', 'Oxford A1'),
    q('t_past_a1_8', 'A1', 'matching', 'Matching', 'Memory',
      'Match the past simple of "take":',
      ['took', 'taked', 'taken', 'taking'], 0,
      '"Take" -> "took".', 'Elementary Verbs A1'),
    q('t_past_a1_9', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "They was very happy with the results."',
      ['Incorrect - plural "They" takes "were"', 'Correct'], 0,
      'Subject "They" takes "were": "They WERE very happy".', 'test-english A1'),
    q('t_past_a1_10', 'A1', 'open_bracket', 'Open Bracket', 'Producing',
      'Supply past form: "He (write) ______ a letter to his penfriend last week."',
      ['wrote', 'written', 'writed', 'writing'], 0,
      '"Write" -> "wrote".', 'Cambridge A1'),
    q('t_past_a1_11', 'A1', 'cloze', 'Cloze Test', 'Understanding',
      'I ______ a great movie on television last Sunday.',
      ['watched', 'watch', 'was watch', 'watching'], 0,
      'Past completed action takes Past Simple: "watched".', 'VOA English A1'),
    q('t_past_a1_12', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which verb has an IDENTICAL base and past form (no change)?',
      ['Cut (cut / cut)', 'Eat (ate)', 'Go (went)', 'Drive (drove)'], 0,
      '"Cut" remains "cut" in the past tense.', 'Wordwall A1'),
    q('t_past_a1_13', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'She ______ a delicious chocolate cake for my birthday party.',
      ['made', 'maked', 'make', 'making'], 0,
      '"Make" -> "made".', 'British Council A1'),
    q('t_past_a1_14', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [went / bed / to / early / they / night / last]',
      ['They went to bed early last night.', 'Last night went they to bed early.', 'Early to bed they went last night.', 'They to bed went early last night.'], 0,
      'Subject + Verb + Place + Manner + Time.', 'Syntax A1'),
    q('t_past_a1_15', 'A1', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the error: "He [A: didn\'t] [B: knew] the [C: correct] [D: answer]."',
      ['A: didn\'t', 'B: knew - use base form "know"!', 'C: correct', 'D: answer'], 1,
      '"Didn\'t know", not *didn\'t knew.', 'Common Traps A1')
  );

  // A2 (15 items)
  items.push(
    q('t_past_a2_1', 'A2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Choose the interrupted action: "While I ______ dinner, the telephone ______."',
      ['was cooking / rang', 'cooked / was ringing', 'was cooking / was ringing', 'cooked / rang'], 0,
      'Ongoing background action takes Past Continuous ("was cooking"); the shorter interruption takes Past Simple ("rang").', 'test-english A2'),
    q('t_past_a2_2', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'What ______ at 8:00 PM last night when the lights went out?',
      ['were you doing', 'did you do', 'have you done', 'had you done'], 0,
      'Action in progress at a specific past point in time: "were you doing".', 'Cambridge A2'),
    q('t_past_a2_3', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "While he was walking home, it started to rain."',
      ['Correct - past continuous background interrupted by past simple', 'Incorrect'], 0,
      'Standard interrupted past narrative pattern.', 'British Council A2'),
    q('t_past_a2_4', 'A2', 'open_bracket', 'Open Bracket (Past Continuous)', 'Producing',
      'Conjugate: "The children (play) ______ in the garden when the storm began."',
      ['were playing', 'was playing', 'played', 'are playing'], 0,
      'Plural subject "children" takes "were playing".', 'Oxford A2'),
    q('t_past_a2_5', 'A2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "While I [A: was walking] in the park, I [B: was finding] a gold [C: watch on] the [D: ground]."',
      ['A: was walking', 'B: was finding - sudden discovery is a momentary event: "found"!', 'C: watch on', 'D: ground'], 1,
      'Sudden punctual events take Past Simple: "found", not *was finding.', 'Punctual Past A2'),
    q('t_past_a2_6', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which time conjunction typically introduces the ONGOING background clause?',
      ['While', 'Suddenly', 'Then', 'Next'], 0,
      '"While" introduces continuous background actions.', 'Wordwall A2'),
    q('t_past_a2_7', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [reading / when / arrived / was / he / I / book / a]',
      ['I was reading a book when he arrived.', 'When he arrived was I reading a book.', 'A book was I reading when he arrived.', 'He arrived when I was reading a book.'], 0,
      'Continuous background + when + past simple interruption.', 'Syntax A2'),
    q('t_past_a2_8', 'A2', 'cloze', 'Cloze Test', 'Understanding',
      'They ______ television when the power failed.',
      ['were watching', 'watched', 'was watching', 'are watching'], 0,
      '"Were watching" (interrupted continuous).', 'test-english A2'),
    q('t_past_a2_9', 'A2', 'matching', 'Matching', 'Understanding',
      'Match: "used to" in past sentences ->',
      ['Past habit or state that no longer exists today', 'Action happening right now', 'Future plan', 'Recent past with result'], 0,
      '"Used to" expresses discontinued past habits or states.', 'Cambridge A2'),
    q('t_past_a2_10', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "I used to play basketball every weekend when I was in school."',
      ['Correct - discontinued past habit', 'Incorrect'], 0,
      '"Used to play" correctly describes a past habit.', 'British Council A2'),
    q('t_past_a2_11', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'He ______ live in Paris before he relocated to London.',
      ['used to', 'was used to', 'is used to', 'use to'], 0,
      '"Used to + base verb" expresses past state.', 'VOA English A2'),
    q('t_past_a2_12', 'A2', 'open_bracket', 'Open Bracket', 'Producing',
      'Conjugate: "At midnight, the wind (blow) ______ violently against the shutters."',
      ['was blowing', 'blew', 'has blown', 'had blown'], 0,
      'Specific ongoing moment in past: "was blowing".', 'Oxford A2'),
    q('t_past_a2_13', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which irregular verb forms its past with "-ought"?',
      ['Think (thought)', 'Sing', 'Drive', 'Speak'], 0,
      '"Think" -> "thought" (-ought pattern).', 'Wordwall A2'),
    q('t_past_a2_14', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [sleeping / soundly / were / children / the]',
      ['The children were sleeping soundly.', 'Soundly were the children sleeping.', 'Were the children sleeping soundly.', 'The children soundly were sleeping.'], 0,
      'Subject + were + sleeping soundly.', 'Syntax A2'),
    q('t_past_a2_15', 'A2', 'checking_error', 'Checking Error', 'Explaining',
      'Find the mistake: "She [A: used to] [B: went] swimming [C: every morning] in [D: summer]."',
      ['A: used to', 'B: went - "used to" takes bare infinitive "go"!', 'C: every morning', 'D: summer'], 1,
      '"Used to GO", not *used to went.', 'Used to Traps A2')
  );

  // B1 (15 items)
  items.push(
    q('t_past_b1_1', 'B1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Choose the Past Perfect for an earlier past action: "When we arrived at the cinema, the movie ______."',
      ['had already started', 'already started', 'has already started', 'was already starting'], 0,
      'The earlier of two past actions requires the Past Perfect: "had already started".', 'Cambridge B1'),
    q('t_past_b1_2', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'He couldn\'t board the aircraft because he ______ his passport at home.',
      ['had left', 'left', 'has left', 'was leaving'], 0,
      'Action occurring prior to arriving at the airport: "had left".', 'test-english B1'),
    q('t_past_b1_3', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "By the time the fire brigade arrived, the neighbors had extinguished the flames."',
      ['Correct - "By the time + past simple" paired with past perfect', 'Incorrect'], 0,
      'Action completed before a past deadline: Past Perfect "had extinguished".', 'Oxford B1'),
    q('t_past_b1_4', 'B1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "When I [A: reached] the station, the [B: train] [C: already] [D: departed]."',
      ['A: reached', 'B: train', 'C: already', 'D: departed - requires past perfect "HAD already departed"!'], 3,
      'Earlier event requires Past Perfect: "had already departed".', 'Past Perfect B1'),
    q('t_past_b1_5', 'B1', 'open_bracket', 'Open Bracket (Past Perfect Continuous)', 'Producing',
      'Conjugate: "He was exhausted because he (drive) ______ for six hours without a break."',
      ['had been driving', 'was driving', 'has been driving', 'drove'], 0,
      'Duration up to a specific past moment: "had been driving".', 'British Council B1'),
    q('t_past_b1_6', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which structure CANNOT express past habit with a STATIVE verb?',
      ['Would (e.g. He would be shy)', 'Used to (He used to be shy)', 'Past simple (He was shy)', 'Past continuous'], 0,
      '"Would" for past habits cannot be used with stative verbs (be, have, live); only dynamic repeated actions.', 'Would vs Used to B1'),
    q('t_past_b1_7', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [already / had / they / eaten / arrived / we / when]',
      ['They had already eaten when we arrived.', 'When we arrived had they already eaten.', 'Already eaten they had when we arrived.', 'We arrived when they had already eaten.'], 0,
      'Past perfect before past simple: "They had already eaten when we arrived."', 'Syntax B1'),
    q('t_past_b1_8', 'B1', 'cloze', 'Cloze Test', 'Understanding',
      'She told the police that she ______ the suspect near the bank earlier that afternoon.',
      ['had seen', 'saw', 'has seen', 'was seeing'], 0,
      'Reported speech backshift to earlier past: "had seen".', 'Backshift B1'),
    q('t_past_b1_9', 'B1', 'matching', 'Matching', 'Understanding',
      'Match: "By 2010" in past narrative ->',
      ['Past Perfect Simple (had completed)', 'Present Perfect', 'Past Continuous', 'Future in the past'], 0,
      '"By + past year" typically takes the Past Perfect.', 'Cambridge B1'),
    q('t_past_b1_10', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "As children, we would swim in the clear mountain lake every summer."',
      ['Correct - "would" correctly expresses repeated dynamic past actions', 'Incorrect - must use "used to"'], 0,
      '"Would swim" is authentic storytelling style for repeated past dynamic actions.', 'test-english B1'),
    q('t_past_b1_11', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The garden was completely flooded because it ______ for forty-eight hours.',
      ['had been raining', 'rained', 'was raining', 'has rained'], 0,
      'Continuous duration explaining a past condition: "had been raining".', 'British Council B1'),
    q('t_past_b1_12', 'B1', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the error: "When I [A: lived] in Paris, I [B: would have] a small [C: apartment near] the [D: Seine]."',
      ['A: lived', 'B: would have - "would" cannot express past states! Say "used to have"!', 'C: apartment near', 'D: Seine'], 1,
      '"Would" cannot be used with state verbs like "have": say "used to have".', 'Would vs Used to B1'),
    q('t_past_b1_13', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which tense highlights DURATION leading up to a past reference point?',
      ['Past Perfect Continuous', 'Past Simple', 'Past Continuous', 'Present Perfect'], 0,
      'Past Perfect Continuous emphasizes ongoing duration before a past moment.', 'Wordwall B1'),
    q('t_past_b1_14', 'B1', 'open_bracket', 'Open Bracket', 'Producing',
      'Conjugate: "Before she moved to Tokyo, she (never / study) ______ Japanese."',
      ['had never studied', 'never studied', 'has never studied', 'was never studying'], 0,
      'Life experience up to a past time: "had never studied".', 'Oxford B1'),
    q('t_past_b1_15', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [working / had / for / been / he / hours / when / arrived / help]',
      ['He had been working for hours when help arrived.', 'When help arrived he had been working for hours.', 'Help arrived when he had been working for hours.', 'For hours had he been working when help arrived.'], 0,
      'Past perfect continuous with duration clause.', 'Syntax B1')
  );

  // B2 (15 items)
  items.push(
    q('t_past_b2_1', 'B2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Express an unfulfilled past intention: "I ______ to attend the lecture, but an urgent matter detained me."',
      ['had hoped', 'have hoped', 'was hoping to have', 'would hope'], 0,
      'Past Perfect ("had hoped / had intended") expresses a past hope or intention that was not realized.', 'Oxford B2'),
    q('t_past_b2_2', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'If only we ______ the train earlier, we would not be stranded here now!',
      ['had caught', 'caught', 'have caught', 'would catch'], 0,
      'Expressing past regret with "If only" takes the Past Perfect: "had caught".', 'Cambridge B2 First'),
    q('t_past_b2_3', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "No sooner had the curtain fallen than the audience erupted into applause."',
      ['Correct - inverted past perfect with "no sooner... than"', 'Incorrect'], 0,
      'Inverted Past Perfect with "No sooner... than": "No sooner had the curtain fallen...".', 'test-english B2'),
    q('t_past_b2_4', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "Hardly [A: the prime minister had] finished speaking [B: when] the journalists [C: clamored] with [D: questions]."',
      ['A: the prime minister had - negative fronting requires inversion: "Hardly HAD the prime minister finished"!', 'B: when', 'C: clamored', 'D: questions'], 0,
      'Negative fronting requires inversion: "Hardly had the prime minister finished...".', 'Negative Inversion B2'),
    q('t_past_b2_5', 'B2', 'open_bracket', 'Open Bracket (Third Conditional)', 'Producing',
      'Conjugate: "If she (consult) ______ a specialist earlier, the disease could have been treated."',
      ['had consulted', 'consulted', 'has consulted', 'would consult'], 0,
      'Third conditional if-clause takes the Past Perfect: "had consulted".', 'Conditionals B2'),
    q('t_past_b2_6', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which construction expresses a PAST COUNTERFACTUAL WISH?',
      ['I wish I had accepted the scholarship.', 'I wish I were taller.', 'I wish you would listen.', 'I wish to speak to the manager.'], 0,
      '"Wish + Past Perfect" expresses regret about past events.', 'Wishes B2'),
    q('t_past_b2_7', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Assemble: [had / departed / train / the / already / station / the / from]',
      ['The train had already departed from the station.', 'Already the train had departed from the station.', 'From the station the train had already departed.', 'Departed had the train already from the station.'], 0,
      'Past perfect completed action.', 'Syntax B2'),
    q('t_past_b2_8', 'B2', 'cloze', 'Cloze Test', 'Understanding',
      'The scientists realized that their calculations ______ flawed from the outset.',
      ['had been', 'were being', 'have been', 'are'], 0,
      'Past perfect state preceding the realization: "had been flawed".', 'B2 Academic Narrative'),
    q('t_past_b2_9', 'B2', 'matching', 'Matching', 'Understanding',
      'Match: "I had intended to call you" ->',
      ['Unfulfilled past plan / intention', 'Action completed in present', 'Routine past habit', 'Uncertain future'], 0,
      '"Had intended" signals an unrealized past intention.', 'Cambridge B2'),
    q('t_past_b2_10', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "Galileo proved that the Earth revolved around the Sun."',
      ['Acceptable in informal backshift, but timeless scientific truths retain the Present Simple ("revolves")', 'Strictly mandatory'], 0,
      'In academic reporting, enduring scientific truths typically retain the present tense: "proves that the Earth revolves".', 'Sequence of Tenses B2'),
    q('t_past_b2_11', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'By midnight, the rescue team ______ searching the ruins for fifteen consecutive hours.',
      ['had been', 'was', 'has been', 'had'], 0,
      '"By midnight... had been searching": Past Perfect Continuous.', 'British Council B2'),
    q('t_past_b2_12', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the defect: "I [A: wish] [B: I didn\'t spend] all my [C: savings] on that [D: depreciating asset last month]."',
      ['A: wish', 'B: I didn\'t spend - past regret requires Past Perfect: "hadn\'t spent"!', 'C: savings', 'D: depreciating asset last month'], 1,
      'Regret about a past action requires "hadn\'t spent", not *didn\'t spend.', 'Wishes B2'),
    q('t_past_b2_13', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which verb pairs with "used to" but CANNOT take "would" for past descriptions?',
      ['Reside (He used to reside here)', 'Play', 'Visit', 'Swim'], 0,
      '"Reside" is stative; "would" only takes repeated dynamic actions.', 'Wordwall B2'),
    q('t_past_b2_14', 'B2', 'open_bracket', 'Open Bracket', 'Producing',
      'Conjugate: "Scarcely had she closed her eyes when the alarm (ring) ______."',
      ['rang', 'had rung', 'was ringing', 'rings'], 0,
      'The time clause with "when" takes Past Simple: "rang".', 'Correlatives B2'),
    q('t_past_b2_15', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [had / known / if / I / I / spoken / would / have]',
      ['If I had known, I would have spoken.', 'Had I known, I would have spoken.', 'I would have spoken if I had known.', 'Known if I had, I would have spoken.'], 0,
      'Third conditional: "If I had known, I would have spoken."', 'Syntax B2')
  );

  // C1 & C2 (20 items: 10 C1 + 10 C2)
  items.push(
    q('t_past_c1_1', 'C1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Analyze historical narrative destiny: "He was to become one of the twentieth century\'s pre-eminent statesmen." What does "was to become" signify?',
      ['Retrospective destiny viewed from a past vantage point', 'A command given to him', 'A conditional hypothesis', 'An interrupted action'], 0,
      '"Was/were to + infinitive" conveys historical retrospective destiny in elevated narrative prose.', 'Cambridge C1 Advanced'),
    q('t_past_c1_2', 'C1', 'open_bracket', 'Open Bracket', 'Producing',
      'Conjugate inverted third conditional: "(Had / If) ______ the sovereign listened to wise counsel, the catastrophe might have been averted."',
      ['Had', 'If', 'Should', 'Were'], 0,
      'Inverted third conditional: "Had the sovereign listened...".', 'C1 Inversion'),
    q('t_past_c1_3', 'C1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "Had I [A: have known] of the [B: imminent danger], I [C: would never have] [D: ventured forth]."',
      ['A: have known - redundant auxiliary: say "Had I known"!', 'B: imminent danger', 'C: would never have', 'D: ventured forth'], 0,
      'Say "Had I known", not *Had I have known.', 'C1 Traps'),
    q('t_past_c1_4', 'C1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The ambassador had hoped to have concluded the negotiations before winter."',
      ['Correct - double perfect expressing deep unfulfilled retrospective intention in formal register', 'Incorrect'], 0,
      'Double perfect with "had hoped to have concluded" is an authentic classical idiom of unfulfilled intention.', 'High-Register Syntax C1'),
    q('t_past_c1_5', 'C1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Assemble: [had / no / fallen / sooner / darkness / than / started / wolves / the / howling]',
      ['No sooner had darkness fallen than the wolves started howling.', 'Had darkness fallen no sooner than the wolves started howling.', 'The wolves started howling no sooner had darkness fallen than.', 'No sooner than darkness fallen had the wolves started howling.'], 0,
      'Inverted narrative syntax: "No sooner had darkness fallen than...".', 'C1 Syntax'),
    q('t_past_c1_6', 'C1', 'cloze', 'Cloze Test', 'Understanding',
      'The expedition was ______ to have departed at dawn, but adverse gales intervened.',
      ['due', 'intended', 'having', 'about'], 0,
      '"Was due to have departed" expresses an official schedule that was thwarted.', 'C1 Retrospective Schedules'),
    q('t_past_c1_7', 'C1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which construction expresses UNREALIZED PAST DESTINY?',
      ['He was to have succeeded to the dukedom.', 'He succeeded to the dukedom.', 'He was succeeding to the dukedom.', 'He has succeeded to the dukedom.'], 0,
      '"Was to have succeeded" explicitly denotes that the anticipated destiny was never fulfilled.', 'Historical Modality C1'),
    q('t_past_c1_8', 'C1', 'matching', 'Matching', 'Understanding',
      'Match: "I had hoped to meet you" ->',
      ['Unfulfilled past hope', 'Certain past fact', 'Present obligation', 'Future arrangement'], 0,
      'Past perfect expresses an unrealized hope.', 'C1 Semantics'),
    q('t_past_c1_9', 'C1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Scarcely ______ set foot on the continent when revolutionary fervour erupted.',
      ['had he', 'he had', 'did he', 'was he'], 0,
      '"Scarcely had he set foot...": inverted past perfect.', 'C1 Inversion'),
    q('t_past_c1_10', 'C1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The delegates had been meeting behind closed doors for a week before accord was reached."',
      ['Correct - past perfect continuous duration preceding past simple event', 'Incorrect'], 0,
      'Impeccable narrative past perfect continuous aspect.', 'Narrative Tenses C1'),

    // C2 (10 items)
    q('t_past_c2_1', 'C2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'In literary stylistics, what function does the "free indirect discourse" past tense perform?',
      ['It blends third-person narrator voice with a character\'s internal past thoughts without reporting clauses', 'It denotes scientific truths', 'It functions as a future modal', 'It replaces passive voice'], 0,
      'Free indirect style renders a character\'s subjective interior monologue using third-person past tenses.', 'C2 Literary Stylistics'),
    q('t_past_c2_2', 'C2', 'open_bracket', 'Open Bracket (Subjunctive Counterfactual)', 'Producing',
      'Conjugate: "(Were / Had) ______ the sovereign been made aware of the conspiracy, the rebels would have met instant retribution."',
      ['Had', 'Were', 'Should', 'Could'], 0,
      'Inverted third conditional: "Had the sovereign been made aware...".', 'C2 Inversion'),
    q('t_past_c2_3', 'C2', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the defect: "He was to have [A: delivered] the keynote address, but [B: his sudden indisposition] [C: had prevented] him [D: from attending]."',
      ['A: delivered', 'B: his sudden indisposition', 'C: had prevented - the preventing event is in the same time frame as the speech event: use Past Simple "prevented"!', 'D: from attending'], 2,
      'Use Past Simple "prevented", avoiding past perfect pile-up.', 'C2 Narrative Economy'),
    q('t_past_c2_4', 'C2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Reconstruct: [become / was / premier / the / to / celebrated / most / architect / his / of / era]',
      ['He was to become the most celebrated architect of his era.', 'The most celebrated architect of his era was he to become.', 'Of his era he was to become the most celebrated architect.', 'To become he was the most celebrated architect of his era.'], 0,
      'Elevated historical biography prose: "He was to become the most celebrated architect of his era."', 'C2 Biography Style'),
    q('t_past_c2_5', 'C2', 'cloze', 'Cloze Test', 'Understanding',
      'Little ______ that their clandestine correspondence had been intercepted by imperial censors.',
      ['did they suspect', 'they suspected', 'had they suspected', 'were they suspecting'], 0,
      'Fronted negative: "Little did they suspect...".', 'C2 Negative Inversion'),
    q('t_past_c2_6', 'C2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which verb form in classical English conveys past irrealis subjunctive?',
      ['Were (e.g. If I were king)', 'Was', 'Am', 'Been'], 0,
      '"Were" is the past subjunctive irrealis marker.', 'Historical Subjunctive C2'),
    q('t_past_c2_7', 'C2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The dynasty had ______ fallen into decay before the barbarian incursions began.',
      ['already', 'yet', 'still', 'hitherto'], 0,
      '"Had already fallen" confirms prior decay.', 'C2 Historical Prose'),
    q('t_past_c2_8', 'C2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "He spoke as though he had witnessed the battle with his own eyes."',
      ['Correct - "as though + past perfect" expresses hypothetical counterfactual manner', 'Incorrect'], 0,
      '"As though + past perfect" conveys counterfactual comparison.', 'Counterfactual Manner C2'),
    q('t_past_c2_9', 'C2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "Never [A: had the empire] [B: witnessed] such devastation, [C: nor had] [D: its armies suffered such ignominy.]"',
      ['A: had the empire', 'B: witnessed', 'C: nor had', 'D: its armies suffered - Flawless double inversion!'], 3,
      'The sentence is completely flawless in elevated style.', 'C2 Coordinate Inversion'),
    q('t_past_c2_10', 'C2', 'open_bracket', 'Open Bracket', 'Producing',
      'Complete the inverted counterfactual: "(Had / If) ______ not the archives been consumed by flames, the provenance would be indisputable."',
      ['Had', 'If', 'Were', 'Should'], 0,
      '"Had not the archives been consumed...": standard negative third conditional inversion.', 'C2 Syntax')
  );

  return items;
}

function getTensesFuture() {
  const items = [];
  // A1 (15 items)
  items.push(
    q('t_fut_a1_1', 'A1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Choose "will" for a spontaneous decision made right now: "The phone is ringing! — Don\'t worry, I ______ it."',
      ['will answer', 'answer', 'am answering', 'answered'], 0,
      'Instant spontaneous decisions made at the moment of speaking take "will": "I will answer".', 'British Council A1'),
    q('t_fut_a1_2', 'A1', 'open_bracket', 'Open Bracket (Intention)', 'Producing',
      'Use "be going to" for a prior plan: "We (visit) ______ our grandparents next Sunday."',
      ['are going to visit', 'will visit', 'visit', 'visited'], 0,
      'Pre-planned intentions use "be going to": "are going to visit".', 'test-english A1'),
    q('t_fut_a1_3', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "Look at those dark black clouds! It is going to rain."',
      ['Correct - "be going to" expresses predictions based on present physical evidence', 'Incorrect - say "It will rain"'], 0,
      'Observable sensory evidence takes "be going to": "It is going to rain".', 'Cambridge A1'),
    q('t_fut_a1_4', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which modal verb expresses simple future prediction or spontaneous promise?',
      ['Will', 'Can', 'Must', 'May'], 0,
      '"Will" is the primary modal of future prediction and spontaneous decision.', 'Wordwall A1'),
    q('t_fut_a1_5', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'I promise I ______ your secret to anyone.',
      ['will not tell', 'am not telling', 'do not tell', 'didn\'t tell'], 0,
      'Promises take "will / will not": "I will not tell".', 'VOA English A1'),
    q('t_fut_a1_6', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [help / I / carry / will / you / bag / that]',
      ['I will help you carry that bag.', 'I will carry you help that bag.', 'Will I help you carry that bag.', 'You will help I carry that bag.'], 0,
      'Spontaneous offer: Subject (I) + will help + you + bare infinitive (carry that bag).', 'Bamboozle A1'),
    q('t_fut_a1_7', 'A1', 'checking_error', 'Checking Error', 'Explaining',
      'Find the mistake: "She [A: will] [B: goes] to the [C: market] [D: tomorrow]."',
      ['A: will', 'B: goes - modal "will" takes bare infinitive "go"!', 'C: market', 'D: tomorrow'], 1,
      '"Will" takes the base form: "will GO", not *will goes.', 'Oxford A1'),
    q('t_fut_a1_8', 'A1', 'matching', 'Matching', 'Memory',
      'Match: "I\'ll" -> contraction of:',
      ['I will / I shall', 'I would', 'I had', 'I am'], 0,
      '"I\'ll" is the contraction of "I will".', 'Contractions A1'),
    q('t_past_a1_9', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "I think people will travel to Mars in the future."',
      ['Correct - "think + will" for personal future predictions', 'Incorrect'], 0,
      'Personal opinions and predictions take "think + will": "will travel".', 'test-english A1'),
    q('t_fut_a1_10', 'A1', 'open_bracket', 'Open Bracket', 'Producing',
      'Supply future form: "Don\'t worry, I (carry) ______ that heavy suitcase for you."',
      ['will carry', 'am going to carry', 'carry', 'carried'], 0,
      'Instant offer of help: "will carry".', 'Cambridge A1'),
    q('t_fut_a1_11', 'A1', 'cloze', 'Cloze Test', 'Understanding',
      'They ______ their final high school examination next month.',
      ['are going to take', 'will take', 'took', 'takes'], 0,
      'Planned intention: "are going to take".', 'VOA English A1'),
    q('t_fut_a1_12', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which sentence expresses an INSTANT DECISION made right now?',
      ['I\'m hungry. I\'ll make a sandwich.', 'I am going to study medicine next year.', 'The train leaves at 8:00.', 'We are flying to Tokyo tomorrow.'], 0,
      '"I\'ll make a sandwich" is made on the spot.', 'Wordwall A1'),
    q('t_fut_a1_13', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Watch out! You ______ drop that glass vase!',
      ['are going to', 'will', 'shall', 'do'], 0,
      'Immediate imminent danger based on sensory evidence: "are going to drop".', 'British Council A1'),
    q('t_fut_a1_14', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [sunny / be / it / tomorrow / will]',
      ['It will be sunny tomorrow.', 'Tomorrow it will be sunny.', 'Sunny it will be tomorrow.', 'Will it be sunny tomorrow.'], 0,
      'Weather prediction: "It will be sunny tomorrow."', 'Syntax A1'),
    q('t_fut_a1_15', 'A1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "We [A: are going] [B: visit] our [C: cousins] [D: next weekend]."',
      ['A: are going', 'B: visit - requires "to visit": "are going TO visit"!', 'C: cousins', 'D: next weekend'], 1,
      '"Be going to + base verb": "are going TO visit".', 'Be going to A1')
  );

  // A2 (15 items)
  items.push(
    q('t_fut_a2_1', 'A2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Choose Present Continuous for fixed personal arrangements: "I ______ the dentist tomorrow at 10:00 AM; I already have my appointment card."',
      ['am seeing', 'will see', 'see', 'saw'], 0,
      'Fixed personal arrangements booked in advance take the Present Continuous: "am seeing".', 'test-english A2'),
    q('t_fut_a2_2', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The train for Battambang ______ at 6:45 AM from Platform 2.',
      ['leaves', 'is leaving', 'will leave', 'is going to leave'], 0,
      'Timetabled public transport uses the Present Simple for future time: "leaves".', 'Cambridge A2'),
    q('t_fut_a2_3', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "We are flying to Singapore next Friday; the tickets are already booked."',
      ['Correct - fixed arrangement with tickets booked takes Present Continuous', 'Incorrect - must use "will"'], 0,
      'Fixed arrangement with arrangements/tickets already completed: Present Continuous.', 'British Council A2'),
    q('t_fut_a2_4', 'A2', 'open_bracket', 'Open Bracket (Arrangement)', 'Producing',
      'Conjugate: "They (have) ______ a barbecue party this Saturday evening."',
      ['are having', 'will have', 'have', 'had'], 0,
      'Social arrangement: "are having".', 'Oxford A2'),
    q('t_fut_a2_5', 'A2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "The conference [A: will start] [B: at 9:00 AM] [C: tomorrow] according to [D: the official schedule]."',
      ['A: will start - official timetables use Present Simple: "starts"!', 'B: at 9:00 AM', 'C: tomorrow', 'D: the official schedule'], 0,
      'Official public timetable schedules take Present Simple: "starts".', 'Timetable Future A2'),
    q('t_fut_a2_6', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which structure expresses a PRE-PLANNED INTENTION (decision made before now)?',
      ['Be going to (I am going to buy a car)', 'Will for instant offer', 'Present simple timetable', 'Past simple'], 0,
      '"Be going to" expresses intentions planned before speaking.', 'Wordwall A2'),
    q('t_fut_a2_7', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [tomorrow / meeting / are / we / director / the]',
      ['We are meeting the director tomorrow.', 'Tomorrow we are meeting the director.', 'The director are we meeting tomorrow.', 'Are we meeting the director tomorrow.'], 0,
      'Arrangement: "We are meeting the director tomorrow."', 'Syntax A2'),
    q('t_fut_a2_8', 'A2', 'cloze', 'Cloze Test', 'Understanding',
      'I will call you as soon as I ______ at the hotel.',
      ['arrive', 'will arrive', 'arrived', 'am arriving'], 0,
      'Future time clause with "as soon as" takes Present Simple: "arrive".', 'test-english A2'),
    q('t_fut_a2_9', 'A2', 'matching', 'Matching', 'Understanding',
      'Match: "Shall I help you?" -> What does "Shall I" express?',
      ['Polite offer to do something for the listener', 'Past obligation', 'Strict prohibition', 'Certain prediction'], 0,
      '"Shall I...?" offers assistance politely.', 'Cambridge A2'),
    q('t_fut_a2_10', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "Shall we go for a walk in the park?"',
      ['Correct - "Shall we" makes a polite joint suggestion', 'Incorrect'], 0,
      '"Shall we...?" is standard polite joint suggestion.', 'British Council A2'),
    q('t_fut_a2_11', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Be careful on that icy ladder; you ______ slip!',
      ['are going to', 'will', 'shall', 'do'], 0,
      'Imminent prediction from present evidence: "are going to slip".', 'VOA English A2'),
    q('t_fut_a2_12', 'A2', 'open_bracket', 'Open Bracket', 'Producing',
      'Conjugate: "What time (do) ______ the museum open tomorrow morning?"',
      ['does', 'will', 'is', 'did'], 0,
      'Timetable question: "What time DOES the museum open...?".', 'Timetable A2'),
    q('t_fut_a2_13', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which sentence expresses a SCHEDULED PUBLIC TIMETABLE?',
      ['The semester begins on September 1st.', 'I\'ll visit you soon.', 'I am buying milk.', 'Look at the clouds.'], 0,
      '"The semester begins on September 1st" is a scheduled calendar timetable.', 'Wordwall A2'),
    q('t_fut_a2_14', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [shall / we / dinner / where / have / ?]',
      ['Where shall we have dinner?', 'Shall we have dinner where?', 'Where we shall have dinner?', 'Have dinner where shall we?'], 0,
      'Interrogative suggestion: Where + shall + we + have dinner?', 'Syntax A2'),
    q('t_fut_a2_15', 'A2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the defect: "If it [A: will rain] tomorrow, the [B: outdoor match] [C: will be] [D: cancelled]."',
      ['A: will rain - conditional if-clause takes present simple: "If it rains"!', 'B: outdoor match', 'C: will be', 'D: cancelled'], 0,
      'First conditional if-clause takes Present Simple: "If it rains", never *will rain.', 'Conditionals A2')
  );

  // B1 (15 items)
  items.push(
    q('t_fut_b1_1', 'B1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Choose the Future Continuous for an action in progress at a future moment: "This time tomorrow, I ______ on the beach in Sihanoukville."',
      ['will be relaxing', 'will relax', 'relax', 'will have relaxed'], 0,
      '"This time tomorrow" specifies ongoing activity at that future point: Future Continuous "will be relaxing".', 'Cambridge B1'),
    q('t_fut_b1_2', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
      '______ you ______ your laptop this afternoon? If not, could I borrow it?',
      ['Will / be using', 'Do / use', 'Did / use', 'Are / used'], 0,
      'Polite inquiry about plans without pressuring: Future Continuous "Will you be using...?".', 'test-english B1'),
    q('t_fut_b1_3', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "By 2030, scientists will have discovered a cure for the disease."',
      ['Correct - "By + future time" requires Future Perfect Simple ("will have discovered")', 'Incorrect'], 0,
      'Action completed before a future deadline: Future Perfect Simple "will have discovered".', 'Oxford B1'),
    q('t_fut_b1_4', 'B1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "By [A: next December], they [B: will complete] the [C: new] suspension [D: bridge]."',
      ['A: next December', 'B: will complete - "By + deadline" takes Future Perfect: "will have completed"!', 'C: new', 'D: bridge'], 1,
      '"By next December... will have completed".', 'Future Perfect B1'),
    q('t_fut_b1_5', 'B1', 'open_bracket', 'Open Bracket (Future Perfect)', 'Producing',
      'Conjugate: "By five o\'clock, she (finish) ______ all the reports."',
      ['will have finished', 'will finish', 'will be finishing', 'has finished'], 0,
      'Completion prior to five o\'clock: "will have finished".', 'British Council B1'),
    q('t_fut_b1_6', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which time expression triggers the FUTURE PERFECT SIMPLE?',
      ['By the end of this month', 'Right now', 'Every day', 'At present'], 0,
      '"By the end of this month" indicates completion prior to that deadline.', 'Wordwall B1'),
    q('t_fut_b1_7', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange: [be / this / flying / time / will / to / London / tomorrow / we]',
      ['This time tomorrow we will be flying to London.', 'We will be flying to London this time tomorrow.', 'To London we will be flying this time tomorrow.', 'Tomorrow this time will we be flying to London.'], 0,
      'Future continuous ongoing action: "This time tomorrow we will be flying to London."', 'Syntax B1'),
    q('t_fut_b1_8', 'B1', 'cloze', 'Cloze Test', 'Understanding',
      'Don\'t phone between 7:00 and 8:00 PM; we ______ dinner.',
      ['will be having', 'have', 'had', 'will have had'], 0,
      'Action in progress during that time: "will be having".', 'test-english B1'),
    q('t_fut_b1_9', 'B1', 'matching', 'Matching', 'Understanding',
      'Match: "be about to" -> What does it convey?',
      ['Action on the verge of happening immediately', 'Action completed long ago', 'Routine habit', 'Distant uncertain possibility'], 0,
      '"Be about to + infinitive" indicates immediate imminent occurrence.', 'Cambridge B1'),
    q('t_past_b1_10', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The train is about to depart; please step aboard immediately."',
      ['Correct - immediate future on the verge of happening', 'Incorrect'], 0,
      '"Is about to depart" correctly indicates immediate departure.', 'British Council B1'),
    q('t_fut_b1_11', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'By next year, they ______ married for twenty-five years.',
      ['will have been', 'will be', 'are', 'have been'], 0,
      'Duration completed by a future point: "will have been married".', 'Future Perfect B1'),
    q('t_fut_b1_12', 'B1', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the error: "When [A: you will arrive] [B: at the airport], [C: I will be waiting] [D: at the arrivals gate]."',
      ['A: you will arrive - subordinate time clause with "When" takes present simple: "you arrive"!', 'B: at the airport', 'C: I will be waiting', 'D: at the arrivals gate'], 0,
      'Time clauses take Present Simple: "When you arrive...".', 'Time Clauses B1'),
    q('t_fut_b1_13', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which structure indicates an action IN PROGRESS at a specified future moment?',
      ['Future Continuous (will be doing)', 'Future Simple', 'Future Perfect', 'Present Simple'], 0,
      'Future Continuous conveys in-progress activity at a future point.', 'Wordwall B1'),
    q('t_fut_b1_14', 'B1', 'open_bracket', 'Open Bracket', 'Producing',
      'Conjugate: "Hurry up! The ceremony is (about / begin) ______."',
      ['about to begin', 'about beginning', 'about begin', 'about began'], 0,
      '"Be about to + bare infinitive": "about to begin".', 'Immediate Future B1'),
    q('t_fut_b1_15', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [have / by / left / will / noon / they]',
      ['They will have left by noon.', 'By noon they will have left.', 'Will they have left by noon.', 'Left they will have by noon.'], 0,
      'Future perfect: "They will have left by noon."', 'Syntax B1')
  );

  // B2 (15 items)
  items.push(
    q('t_fut_b2_1', 'B2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Choose the Future Perfect Continuous: "By next October, Dr. Bennett ______ at the university for thirty years."',
      ['will have been teaching', 'will be teaching', 'will teach', 'has been teaching'], 0,
      'Duration continuing up to a future reference point: Future Perfect Continuous "will have been teaching".', 'Cambridge B2 First'),
    q('t_fut_b2_2', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The flight left on time, so they ______ in Bangkok by now.',
      ['should have arrived', 'would arrive', 'must arrive', 'will arrive'], 0,
      'Modal of expectation: "should have arrived" conveys high likelihood based on schedule.', 'test-english B2'),
    q('t_fut_b2_3', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The foreign minister is to visit Tokyo next month for bilateral trade talks."',
      ['Correct - "be to + infinitive" expresses official diplomatic itineraries/decrees', 'Incorrect'], 0,
      '"Be to + infinitive" is standard formal syntax for official arrangements.', 'Official Future B2'),
    q('t_fut_b2_4', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "By the time [A: the new stadium] [B: will open], the team [C: will have played] fifty games [D: elsewhere]."',
      ['A: the new stadium', 'B: will open - "By the time" is a time clause taking Present Simple: "opens"!', 'C: will have played', 'D: elsewhere'], 1,
      '"By the time the new stadium OPENS...".', 'Time Clauses B2'),
    q('t_fut_b2_5', 'B2', 'open_bracket', 'Open Bracket (Future Perfect Continuous)', 'Producing',
      'Conjugate: "By the end of this marathon, the athletes (run) ______ for over four hours."',
      ['will have been running', 'will be running', 'will run', 'have been running'], 0,
      'Continuous duration up to a future milestone: "will have been running".', 'Oxford B2'),
    q('t_fut_b2_6', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which structure conveys an IMMINENT EVENT about to take place immediately?',
      ['Be on the verge of + V-ing', 'Future Simple', 'Future Perfect', 'Present Simple'], 0,
      '"Be on the verge of doing" indicates imminent immediate action.', 'Wordwall B2'),
    q('t_fut_b2_7', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Assemble: [due / is / at / flight / land / to / five / the]',
      ['The flight is due to land at five.', 'At five the flight is due to land.', 'Due to land is the flight at five.', 'The flight at five is due to land.'], 0,
      '"Be due to + infinitive" expresses scheduled future time.', 'Syntax B2'),
    q('t_fut_b2_8', 'B2', 'cloze', 'Cloze Test', 'Understanding',
      'Scientists are on the ______ of making a breakthrough in quantum computing.',
      ['verge', 'about', 'due', 'bound'], 0,
      'Collocation: "on the verge of + gerund".', 'B2 Collocations'),
    q('t_fut_b2_9', 'B2', 'matching', 'Matching', 'Understanding',
      'Match: "be bound to" -> What does it mean?',
      ['Certain / inevitable to happen', 'Unlikely to happen', 'Past event', 'Impossible'], 0,
      '"Be bound to" expresses inevitability or strong certainty.', 'Cambridge B2'),
    q('t_fut_b2_10', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "With his talent and work ethic, he is bound to succeed."',
      ['Correct - "bound to" expresses certainty/inevitability', 'Incorrect'], 0,
      '"Bound to succeed" is standard natural English for certainty.', 'British Council B2'),
    q('t_fut_b2_11', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The company is on the ______ of collapse unless an emergency bailout is agreed.',
      ['brink', 'about', 'due', 'verging'], 0,
      'Fixed idiom: "on the brink of collapse".', 'Idioms B2'),
    q('t_fut_b2_12', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the defect: "The treaty [A: is to signed] [B: by both] heads of state [C: in Geneva] [D: on Friday]."',
      ['A: is to signed - passive requires "is to BE signed"!', 'B: by both', 'C: in Geneva', 'D: on Friday'], 0,
      'Passive official decree: "is to BE signed".', 'Official Passive B2'),
    q('t_fut_b2_13', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which future phrase conveys HIGH PROBABILITY based on normal expectation?',
      ['Should (The train should arrive on time)', 'Will not', 'Might not', 'Could possibly'], 0,
      '"Should" expresses normal deduction/expectation of future events.', 'Modals B2'),
    q('t_fut_b2_14', 'B2', 'open_bracket', 'Open Bracket', 'Producing',
      'Conjugate: "By midnight, the storm (pass) ______ and clear skies will return."',
      ['will have passed', 'will pass', 'passes', 'passed'], 0,
      'Completion before midnight: "will have passed".', 'Future Perfect B2'),
    q('t_fut_b2_15', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [bound / mistake / you / are / make / to / a]',
      ['You are bound to make a mistake.', 'To make a mistake you are bound.', 'Are you bound to make a mistake.', 'A mistake you are bound to make.'], 0,
      'Certainty: "You are bound to make a mistake."', 'Syntax B2')
  );

  // C1 & C2 (20 items: 10 C1 + 10 C2)
  items.push(
    q('t_fut_c1_1', 'C1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Analyze behavioral generic "will": "A venomous snake will only strike if cornered." What does "will" convey here?',
      ['Characteristic behavioral predictability rather than future time', 'Spontaneous offer made now', 'Scheduled public appointment', 'Past habit'], 0,
      '"Will" functions epistemically to express characteristic habit or law-like behavioral disposition.', 'Cambridge C1 Advanced'),
    q('t_fut_c1_2', 'C1', 'open_bracket', 'Open Bracket', 'Producing',
      'Supply the official diplomatic future: "The Prime Minister (meet) ______ with his European counterparts in Paris."',
      ['is to meet', 'will be met', 'meets with', 'meeting'], 0,
      '"Be to + infinitive" expresses official diplomatic schedule.', 'C1 Diplomatic Register'),
    q('t_fut_c1_3', 'C1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "Provided that the treaty [A: will be ratified] [B: next week], trade sanctions [C: will be lifted] [D: forthwith]."',
      ['A: will be ratified - conditional "provided that" takes Present Simple: "is ratified"!', 'B: next week', 'C: will be lifted', 'D: forthwith'], 0,
      'Conditional clauses take Present Simple: "is ratified", never *will be ratified.', 'Conditional Tenses C1'),
    q('t_fut_c1_4', 'C1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "Oil will float on water."',
      ['Correct - "will" expresses inherent scientific disposition / general truth', 'Incorrect - must only use simple present'], 0,
      '"Will" conveys inherent characteristic property or natural law.', 'Scientific Will C1'),
    q('t_fut_c1_5', 'C1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Assemble: [summit / to / in / take / place / is / Geneva / the]',
      ['The summit is to take place in Geneva.', 'In Geneva the summit is to take place.', 'To take place the summit is in Geneva.', 'Is the summit to take place in Geneva.'], 0,
      'Official diplomatic arrangement: "The summit is to take place in Geneva."', 'C1 Syntax'),
    q('t_fut_c1_6', 'C1', 'cloze', 'Cloze Test', 'Understanding',
      'The spacecraft is ______ to touch down on Mars at 14:00 GMT.',
      ['slated', 'about', 'bound', 'verging'], 0,
      '"Be slated to + infinitive" is formal high-register American/international English for scheduled future events.', 'Academic Register C1'),
    q('t_fut_c1_7', 'C1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which modal use of "will" expresses VOLITIONAL OBSTINACY (stubborn refusal)?',
      ['The car won\'t start! (obstinate refusal)', 'I will buy milk.', 'It will rain.', 'The shop will open at 9.'], 0,
      '"Won\'t start" expresses volitional refusal attributed metaphorically to an inanimate object.', 'Volitional Will C1'),
    q('t_fut_c1_8', 'C1', 'matching', 'Matching', 'Understanding',
      'Match: "Boys will be boys" -> What does "will" convey?',
      ['Proverbial characteristic inevitability', 'Future time prediction', 'Spontaneous intention', 'Subjunctive mood'], 0,
      'Proverbial predictability of human nature.', 'Proverbial Will C1'),
    q('t_fut_c1_9', 'C1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The consortium is on the ______ of finalizing the multi-billion dollar acquisition.',
      ['cusp', 'verge', 'brink', 'point'], 0,
      '"On the cusp of + V-ing": on the threshold or verge of major accomplishment.', 'C1 Idioms'),
    q('t_fut_c1_10', 'C1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "By December 2030, the consortium will have been operating the facility for half a century."',
      ['Correct - Future Perfect Continuous with duration prepositional phrase', 'Incorrect'], 0,
      'Impeccable Future Perfect Continuous syntax.', 'C1 Aspectual Mastery'),

    // C2 (10 items)
    q('t_fut_c2_1', 'C2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'In statutory legislative drafting, what does the modal "SHALL" express in: "The lessee shall maintain the premises in good repair"?',
      ['A mandatory legal obligation / imperative duty', 'A future prediction of probability', 'A polite suggestion', 'A hypothetical condition'], 0,
      'Statutory "shall" denotes mandatory, legally binding obligation.', 'C2 Statutory Drafting'),
    q('t_fut_c2_2', 'C2', 'open_bracket', 'Open Bracket (Statutory Prohibition)', 'Producing',
      'Complete the statutory prohibition: "No officer (shall / will) ______ disclose classified intelligence without prior authorization."',
      ['shall', 'will', 'may', 'can'], 0,
      'High statutory drafting strictly employs "shall": "No officer shall disclose...".', 'C2 Legal English'),
    q('t_fut_c2_3', 'C2', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the defect: "The treaty [A: stipulates that] the commission [B: will be convened] [C: within thirty days] of [D: ratification]."',
      ['A: stipulates that', 'B: will be convened - statutory instruments require mandatory "SHALL be convened"!', 'C: within thirty days', 'D: of ratification'], 1,
      'Formal legal instruments use "shall be convened" to express legal imperative, not predictive "will".', 'Legal Drafting C2'),
    q('t_fut_c2_4', 'C2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Reconstruct: [binding / terms / the / shall / upon / parties / be / all]',
      ['The terms shall be binding upon all parties.', 'Binding upon all parties the terms shall be.', 'Shall the terms be binding upon all parties.', 'All parties shall the terms be binding upon.'], 0,
      'Statutory legal clause: "The terms shall be binding upon all parties."', 'C2 Jurisprudence'),
    q('t_fut_c2_5', 'C2', 'cloze', 'Cloze Test', 'Understanding',
      'All disputes arising hereunder ______ be resolved by binding arbitration in Geneva.',
      ['shall', 'will', 'may', 'would'], 0,
      'Statutory arbitration covenant requires "shall".', 'Arbitration C2'),
    q('t_fut_c2_6', 'C2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which verb phrase in formal contracts expresses CONDITION PRECEDENT to future performance?',
      ['Subject to the fulfillment of (Subject to Clause 4, the closing shall occur)', 'Will be', 'Was', 'Had been'], 0,
      '"Subject to the fulfillment of..." sets a condition precedent.', 'C2 Contracts'),
    q('t_fut_c2_7', 'C2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Payment ______ become due and payable within thirty days of invoice presentation.',
      ['shall', 'will', 'may', 'must to'], 0,
      'Commercial contract standard: "shall become due".', 'C2 Commercial Law'),
    q('t_fut_c2_8', 'C2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The tenant shall not sublet the premises without the landlord\'s written consent."',
      ['Correct - standard statutory covenant of prohibition using "shall not"', 'Incorrect'], 0,
      '"Shall not" is the standard legal formula for prohibitive covenants.', 'C2 Legal English'),
    q('t_fut_c2_9', 'C2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "Nothing in this agreement [A: shall be construed] as [B: creating] [C: an partnership] [D: between the parties]."',
      ['A: shall be construed', 'B: creating', 'C: an partnership - consonant sound requires "A partnership"!', 'D: between the parties'], 2,
      'Spelling flaw: "a partnership", not *an partnership.', 'C2 Precision'),
    q('t_fut_c2_10', 'C2', 'open_bracket', 'Open Bracket', 'Producing',
      'Conjugate: "This agreement (remain) ______ in force until terminated in writing by either signatory."',
      ['shall remain', 'will remaining', 'remains to be', 'shall remaining'], 0,
      '"This agreement shall remain in force...": standard term clause.', 'C2 Legal Drafting')
  );

  return items;
}

module.exports = { getTensesPast, getTensesFuture };
