// scripts/gen_topics_2_to_5.js
// Pronouns, Verbs, Adverbs, Adjectives (Topics 2, 3, 4, 5)
const { q } = require('./q_helper');

function getPronouns() {
  const items = [];
  // A1: 15 items
  items.push(
    q('pron_a1_1', 'A1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Replace the subject: "Mary is a doctor." -> "______ is a doctor."',
      ['He', 'She', 'It', 'They'], 1,
      '"Mary" is a singular female person, so the subject personal pronoun is "She".', 'British Council A1'),
    q('pron_a1_2', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Please give that red apple to ______; I am hungry.',
      ['I', 'me', 'my', 'mine'], 1,
      'Following a preposition ("to"), use the objective pronoun "me".', 'test-english A1'),
    q('pron_a1_3', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "Him is my best friend from school."',
      ['Correct', 'Incorrect - "He" is the subject pronoun'], 1,
      '"He" must be used as the subject of the sentence, not object pronoun "him".', 'Cambridge A1'),
    q('pron_a1_4', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which word is an OBJECT pronoun?',
      ['He', 'They', 'Us', 'She'], 2,
      '"Us" is an objective pronoun (subject form is "we").', 'Wordwall A1'),
    q('pron_a1_5', 'A1', 'open_bracket', 'Open Bracket (Possessive)', 'Producing',
      'Fill with the possessive adjective: "I have a cat. (I) ______ cat is white."',
      ['My', 'Me', 'Mine', 'Myself'], 0,
      'The possessive adjective before a noun is "My".', 'Elementary Pronouns'),
    q('pron_a1_6', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange the words: [sister / she / is / my / younger]',
      ['She is my younger sister.', 'My sister is she younger.', 'She my younger is sister.', 'Younger sister she is my.'], 0,
      'Subject (She) + Verb (is) + Possessive Noun Phrase (my younger sister).', 'Bamboozle A1'),
    q('pron_a1_7', 'A1', 'checking_error', 'Checking Error', 'Explaining',
      'Find the mistake: "David and [A: me] [B: went] [C: to] the [D: market]."',
      ['A: me', 'B: went', 'C: to', 'D: market'], 0,
      'As part of the compound subject performing the action, use "I": "David and I went...".', 'Oxford A1'),
    q('pron_a1_8', 'A1', 'matching', 'Matching', 'Memory',
      'Match the pronoun "we" with its corresponding possessive pronoun:',
      ['our', 'ours', 'us', 'ourselves'], 1,
      '"Ours" is the standalone possessive pronoun for "we" (e.g., "This classroom is ours").', 'British Council A1'),
    q('pron_a1_9', 'A1', 'cloze', 'Cloze Test', 'Understanding',
      'Look at those birds! ______ are flying south for the winter.',
      ['It', 'They', 'Them', 'Their'], 1,
      'Plural animals/things take the subject pronoun "They".', 'test-english A1'),
    q('pron_a1_10', 'A1', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "This pencil belongs to me. It is mine."',
      ['Correct - "mine" is the possessive pronoun', 'Incorrect - say "It is my"'], 0,
      '"Mine" correctly stands alone without a following noun.', 'Cambridge A1'),
    q('pron_a1_11', 'A1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Where are my keys? I cannot find ______ anywhere.',
      ['it', 'them', 'they', 'their'], 1,
      '"Keys" is plural, so the direct object pronoun is "them".', 'VOA English A1'),
    q('pron_a1_12', 'A1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which pronoun is a DEMONSTRATIVE pronoun?',
      ['This', 'You', 'Him', 'We'], 0,
      '"This" (along with that, these, those) is a demonstrative pronoun.', 'Wordwall A1'),
    q('pron_a1_13', 'A1', 'open_bracket', 'Open Bracket', 'Producing',
      'Change into plural: "That book is interesting." -> "(Those) ______ books are interesting."',
      ['Those', 'These', 'This', 'Them'], 0,
      'The plural form of "that" is "those".', 'Demonstratives A1'),
    q('pron_a1_14', 'A1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [give / can / you / your / pen / me / ?]',
      ['Can you give me your pen?', 'Can you give your pen me?', 'Give can you me your pen?', 'Your pen can you give me?'], 0,
      'Modal (Can) + Subject (you) + Verb (give) + Indirect Object (me) + Direct Object (your pen)?', 'Syntax A1'),
    q('pron_a1_15', 'A1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the error: "The dog [A: is] wagging [B: it\'s] [C: tail] [D: happily]."',
      ['A: is', 'B: it\'s', 'C: tail', 'D: happily'], 1,
      'Possessive determiner is "its" (without apostrophe). "It\'s" is a contraction of "it is".', 'Common Traps A1')
  );

  // A2: 15 items
  items.push(
    q('pron_a2_1', 'A2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Choose the reflexive pronoun: "Be careful with that boiling water, or you will scald ______."',
      ['you', 'your', 'yourself', 'yourselves'], 2,
      'When the subject and object are the same person (singular you), use "yourself".', 'test-english A2'),
    q('pron_a2_2', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'Nobody came to the party, so she sat by ______ the entire evening.',
      ['her', 'hers', 'herself', 'she'], 2,
      '"By herself" is an idiomatic phrase meaning alone / without company.', 'British Council A2'),
    q('pron_a2_3', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The two brothers always look after each other."',
      ['Correct - "each other" is a reciprocal pronoun for two parties', 'Incorrect - say "themselves"'], 0,
      '"Each other" denotes mutual reciprocal action between two individuals.', 'Cambridge A2'),
    q('pron_a2_4', 'A2', 'open_bracket', 'Open Bracket (Reflexive)', 'Producing',
      'Complete with reflexive form: "He taught (he) ______ how to write computer code."',
      ['himself', 'hisself', 'him', 'he'], 0,
      'The masculine singular reflexive pronoun is "himself" (never *hisself).', 'Oxford A2'),
    q('pron_a2_5', 'A2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the mistake: "Is [A: there] [B: anybody] in the office who [C: can] help [D: we]?"',
      ['A: there', 'B: anybody', 'C: can', 'D: we'], 3,
      'Object of the verb "help" must be the objective pronoun "us", not subjective "we".', 'test-english A2'),
    q('pron_a2_6', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which word is an INDEFINITE pronoun?',
      ['Someone', 'They', 'Mine', 'Himself'], 0,
      '"Someone" refers to an unspecified person (indefinite pronoun).', 'Wordwall A2'),
    q('pron_a2_7', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Arrange into a question: [phone / is / this / whose / mobile / ?]',
      ['Whose mobile phone is this?', 'This mobile phone whose is?', 'Whose is mobile phone this?', 'Mobile phone whose this is?'], 0,
      'Interrogative possessive "Whose" + Noun (mobile phone) + Verb (is) + Demonstrative (this)?', 'Syntax A2'),
    q('pron_a2_8', 'A2', 'matching', 'Matching', 'Understanding',
      'Which relative pronoun refers to human beings as subject?',
      ['Who', 'Which', 'Where', 'When'], 0,
      '"Who" is the relative pronoun used for persons.', 'Relative Pronouns A2'),
    q('pron_a2_9', 'A2', 'cloze', 'Cloze Test', 'Understanding',
      'The jacket belongs to Sarah; this blue one is ______.',
      ['my', 'mine', 'me', 'myself'], 1,
      '"Mine" replaces the noun phrase "my jacket".', 'test-english A2'),
    q('pron_a2_10', 'A2', 'correct_incorrect', 'Correct or Incorrect', 'Understanding',
      'Evaluate: "Everyone have finished their lunch in the cafeteria."',
      ['Correct', 'Incorrect - "Everyone" takes a singular verb "has"'], 1,
      'Indefinite pronouns ending in -one and -body are grammatically singular: "Everyone has...".', 'Concord A2'),
    q('pron_a2_11', 'A2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'I don\'t know ______ about this topic; could you explain it to me?',
      ['something', 'anything', 'nothing', 'everything'], 1,
      'In negative sentences, use "anything" (not "nothing").', 'Indefinite Pronouns A2'),
    q('pron_a2_12', 'A2', 'open_bracket', 'Open Bracket', 'Producing',
      'Complete with relative pronoun: "The boy (who / which) ______ won the competition received a gold medal."',
      ['who', 'which', 'whom', 'where'], 0,
      'Use "who" for a person in a defining relative clause.', 'Cambridge A2'),
    q('pron_a2_13', 'A2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which pronoun is a POSSESSIVE pronoun (not adjective)?',
      ['Yours', 'Your', 'My', 'Their'], 0,
      '"Yours" is a standalone possessive pronoun. "Your", "my", and "their" are possessive adjectives.', 'Possessives A2'),
    q('pron_a2_14', 'A2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Order the sentence: [painted / living / the / they / room / themselves]',
      ['They painted the living room themselves.', 'Themselves they painted the living room.', 'They the living room themselves painted.', 'The living room they painted themselves.'], 0,
      'Emphatic reflexive "themselves" sits naturally at the end of the clause.', 'Word Order A2'),
    q('pron_a2_15', 'A2', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the error: "Neither of [A: the] [B: answers] [C: are] [D: correct]."',
      ['A: the', 'B: answers', 'C: are', 'D: correct'], 2,
      '"Neither of..." is grammatically singular in standard English and takes "is": "Neither of the answers IS correct".', 'Standard ELT A2')
  );

  // B1: 15 items
  items.push(
    q('pron_b1_1', 'B1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Choose the relative pronoun indicating possession: "The musician ______ violin was stolen was devastated."',
      ['who', 'whom', 'whose', 'which'], 2,
      '"Whose" represents the possessive relative pronoun ("the musician\'s violin").', 'Cambridge B1'),
    q('pron_b1_2', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'If anybody calls while I am out, please take ______ message.',
      ['his', 'her', 'their', 'its'], 2,
      'Singular "their" is standard gender-neutral pronominal concord for indefinite pronouns.', 'Oxford B1'),
    q('pron_b1_3', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "The committee has published their annual financial report."',
      ['Correct', 'Incorrect - shift from singular "has" to plural "their"'], 1,
      'Concord consistency: either "The committee HAS published ITS report" or "The committee HAVE published THEIR report".', 'test-english B1'),
    q('pron_b1_4', 'B1', 'open_bracket', 'Open Bracket', 'Producing',
      'Insert the reciprocal: "The three business partners regularly collaborate with (each other / one another) ______."',
      ['one another', 'each other', 'themselves', 'theirselves'], 0,
      'Traditionally, "one another" is preferred for interactions involving three or more parties.', 'Grammar B1'),
    q('pron_b1_5', 'B1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "Between you and [A: I], [B: there] [C: are] some serious [D: concerns]."',
      ['A: I', 'B: there', 'C: are', 'D: concerns'], 0,
      'Preposition "Between" governs objective pronouns: "Between you and me" (not "I").', 'British Council B1'),
    q('pron_b1_6', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which relative pronoun can refer to a WHOLE PRECEDING CLAUSE?',
      ['Which', 'Who', 'Whom', 'That'], 0,
      'Sentential relative clauses use \", which\": "He arrived late, which annoyed the boss."', 'B1 Sentential Relatives'),
    q('pron_b1_7', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Assemble the sentence: [car / is / this / that / than / faster / of / mine]',
      ['This car is faster than that of mine.', 'That car is faster than this of mine.', 'Faster is this car than that of mine.', 'Than that of mine this car is faster.'], 0,
      'Comparative structure using demonstrative pro-form "that of mine".', 'B1 Comparison'),
    q('pron_b1_8', 'B1', 'cloze', 'Cloze Test', 'Understanding',
      'Neither the manager nor the assistant ______ aware of the schedule change.',
      ['was', 'were', 'have been', 'are'], 0,
      'In "Neither... nor", the verb agrees with the nearer subject ("the assistant was").', 'Proximity Concord B1'),
    q('pron_b1_9', 'B1', 'matching', 'Matching', 'Understanding',
      'Match the pronoun with its formal replacement: "people who" ->',
      ['those who', 'them who', 'these that', 'ones which'], 0,
      '"Those who..." is the standard formal demonstrative antecedent.', 'Cambridge B1'),
    q('pron_b1_10', 'B1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "He introduced hisself to the newly arrived guests."',
      ['Correct', 'Incorrect - the standard reflexive pronoun is "himself"'], 1,
      '*Hisself is non-standard dialectal; standard English requires "himself".', 'test-english B1'),
    q('pron_b1_11', 'B1', 'fill_blank', 'Fill in the Blank', 'Producing',
      '______ of the two applicants had the necessary qualifications for the job.',
      ['Neither', 'None', 'Nobody', 'Nothing'], 0,
      '"Neither" is used when referring specifically to two entities ("None" is used for three or more).', 'B1 Quantifiers'),
    q('pron_b1_12', 'B1', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the mistake: "She [A: blamed] [B: herself] [C: for] [D: what happened]."',
      ['A: blamed', 'B: herself', 'C: for', 'D: what happened - No mistake!'], 3,
      'The sentence is grammatically flawless: "She blamed herself for what happened."', 'Error Checking B1'),
    q('pron_b1_13', 'B1', 'open_bracket', 'Open Bracket', 'Producing',
      'Use the correct relative pronoun: "The hotel (in which / where) ______ we stayed was near the coast."',
      ['where', 'which', 'that', 'whom'], 0,
      '"Where" replaces "in which" for locations: "The hotel where we stayed...".', 'Relative Clauses B1'),
    q('pron_b1_14', 'B1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which word CANNOT function as a relative pronoun in a non-defining clause?',
      ['That', 'Which', 'Who', 'Whom'], 0,
      '"That" can NEVER be used in non-defining (comma-separated) relative clauses.', 'Cambridge B1 Traps'),
    q('pron_b1_15', 'B1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Put in order: [wants / to / speak / someone / to / you / outside]',
      ['Someone outside wants to speak to you.', 'To speak to you wants someone outside.', 'Outside someone wants to speak you to.', 'Wants someone to speak outside to you.'], 0,
      'Subject (Someone outside) + Verb (wants to speak) + Prepositional Object (to you).', 'Word Order B1')
  );

  // B2: 15 items
  items.push(
    q('pron_b2_1', 'B2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Select the formal sentence with correct preposition + relative pronoun:',
      ['The professor to whom the manuscript was dedicated has retired.', 'The professor to who the manuscript was dedicated has retired.', 'The professor who the manuscript was dedicated has retired.', 'The professor which the manuscript was dedicated has retired.'], 0,
      'Preposition fronting in formal English governs "whom": "to whom the manuscript was dedicated".', 'Cambridge B2 First'),
    q('pron_b2_2', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The salary of an experienced surgeon is considerably higher than ______ of a resident doctor.',
      ['that', 'this', 'those', 'these'], 0,
      '"That" is the formal demonstrative pro-form replacing the singular noun "the salary".', 'test-english B2'),
    q('pron_b2_3', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "Whoever wins the election will face immediate economic challenges."',
      ['Correct - "Whoever" functions as the subject of "wins" in the nominal clause', 'Incorrect - should be "Whomever"'], 0,
      '"Whoever" acts as the subject of the finite verb "wins".', 'Oxford B2'),
    q('pron_b2_4', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the error: "Give the prize to [A: whomever] [B: has] [C: submitted] the best [D: essay]."',
      ['A: whomever', 'B: has', 'C: submitted', 'D: essay'], 0,
      'Even following the preposition "to", the nominal clause requires a subjective pronoun "whoever" to serve as subject of "has submitted".', 'B2 Traps'),
    q('pron_b2_5', 'B2', 'open_bracket', 'Open Bracket', 'Producing',
      'Supply the demonstrative pro-form: "The challenges of today are far greater than (that / those) ______ of the last century."',
      ['those', 'that', 'this', 'these'], 0,
      'For plural referents ("the challenges"), use the demonstrative pro-form "those".', 'Formal Grammar B2'),
    q('pron_b2_6', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which pronoun is an EMPHATIC reflexive pronoun rather than a true reflexive?',
      ['The Queen herself opened the new hospital wing.', 'He cut himself with a knife.', 'She looked at herself in the mirror.', 'They introduced themselves.'], 0,
      'In A, "herself" simply emphasizes "The Queen" and can be omitted without changing core syntax.', 'Reflexive vs Emphatic B2'),
    q('pron_b2_7', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Order into a formal sentence: [delighted / were / with / the / results / themselves / they]',
      ['They were delighted with the results themselves.', 'Themselves were they delighted with the results.', 'With the results they were delighted themselves.', 'They themselves delighted were with the results.'], 0,
      'Subject (They) + Verb (were) + Predicate (delighted with the results) + Emphatic pronoun (themselves).', 'Syntax B2'),
    q('pron_b2_8', 'B2', 'cloze', 'Cloze Test', 'Understanding',
      'The committee members were divided in ______ opinions regarding the restructuring plan.',
      ['their', 'its', 'his', 'our'], 0,
      'When members of a collective body disagree or act separately, use plural "their".', 'British Council B2'),
    q('pron_b2_9', 'B2', 'matching', 'Matching', 'Understanding',
      'Match the pronoun function: "It is raining" - what type of "It" is this?',
      ['Dummy / Ambient "it"', 'Anaphoric personal pronoun', 'Demonstrative pronoun', 'Possessive pronoun'], 0,
      '"It" in weather expressions is an ambient / dummy (expletive) pronoun devoid of semantic referent.', 'Linguistic Grammar B2'),
    q('pron_b2_10', 'B2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "One must not forget his obligations to the community."',
      ['Correct in informal speech, but inconsistent with "one" in formal English', 'Completely standard in formal British English'], 0,
      'In strictly formal British English, "one" requires "one\'s obligations".', 'Cambridge B2'),
    q('pron_b2_11', 'B2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The author ______ novel became a bestseller has agreed to an exclusive interview.',
      ['whose', 'who', 'whom', 'which'], 0,
      '"Whose" expresses possession for persons in relative clauses.', 'B2 Relative Clauses'),
    q('pron_b2_12', 'B2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the flaw: "Neither of [A: the] two delegates [B: were] prepared to concede [C: their] [D: position]."',
      ['A: the', 'B: were - in formal English, "Neither" takes singular "was"', 'C: their', 'D: position'], 1,
      'Standard formal written English requires singular agreement with "neither": "was prepared".', 'Formal Concord B2'),
    q('pron_b2_13', 'B2', 'open_bracket', 'Open Bracket', 'Producing',
      'Provide the indefinite pronoun: "(None / Neither) ______ of the twelve board members voted against the motion."',
      ['None', 'Neither', 'Nobody', 'Nothing'], 0,
      'For more than two entities ("twelve members"), use "None", not "Neither".', 'Precision B2'),
    q('pron_b2_14', 'B2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which of the following is a COMPOUND INDEFINITE PRONOUN?',
      ['Everywhere', 'Somebody', 'Each', 'Either'], 1,
      '"Somebody" is a compound indefinite pronoun (some + body). "Everywhere" is an adverb.', 'Morphology B2'),
    q('pron_b2_15', 'B2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Assemble: [it / to / necessary / is / reserve / advance / seats / in]',
      ['It is necessary to reserve seats in advance.', 'To reserve seats in advance is it necessary.', 'In advance it is necessary to reserve seats.', 'Necessary it is in advance to reserve seats.'], 0,
      'Anticipatory "It" + Copula (is) + Adjective (necessary) + Extraposed Infinitive (to reserve seats in advance).', 'Anticipatory Syntax B2')
  );

  // C1 & C2: 20 items (10 C1 + 10 C2)
  items.push(
    q('pron_c1_1', 'C1', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Select the sentence with impeccable formal anticipatory "it":',
      ['It was thought advisable to postpone the referendum until next spring.', 'There was thought advisable to postpone the referendum.', 'It was thought advisable postponing the referendum.', 'It had thought advisable to postpone the referendum.'], 0,
      'Formal extraposition with anticipatory "It" and to-infinitive complement.', 'Cambridge C1 Advanced'),
    q('pron_c1_2', 'C1', 'open_bracket', 'Open Bracket', 'Producing',
      'Complete with the formal relative pronoun: "The archive contains historical documents, many of (which / that) ______ have never been transcribed."',
      ['which', 'that', 'whom', 'what'], 0,
      'Quantifier + "of which" (quantified relative clause) cannot use "that": "many of which".', 'C1 Relative Syntax'),
    q('pron_c1_3', 'C1', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the flaw: "He is one of those scholars who [A: believes] that the text [B: is] an 18th-century [C: forgery]."',
      ['A: believes - the antecedent of "who" is plural "scholars", so it requires "believe"!', 'B: is', 'C: forgery', 'No error'], 0,
      'In "one of those [plural noun] who...", the relative pronoun "who" refers to the plural antecedent ("scholars believe").', 'Advanced Concord C1'),
    q('pron_c1_4', 'C1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "They awarded the fellowship to whomever demonstrated the greatest merit."',
      ['Correct', 'Incorrect - "whoever" must be used as subject of "demonstrated"'], 1,
      '"Whoever" acts as the subject of the clause "demonstrated the greatest merit", despite following preposition "to".', 'C1 Traps'),
    q('pron_c1_5', 'C1', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Reconstruct: [whom / the / ambassador / to / was / presented / credential / the / smiled]',
      ['The ambassador to whom the credential was presented smiled.', 'To whom the ambassador the credential was presented smiled.', 'The credential was presented to whom the ambassador smiled.', 'Smiled the ambassador to whom the credential was presented.'], 0,
      'Formal pied-piping relative clause: "The ambassador to whom the credential was presented smiled."', 'C1 Syntax'),
    q('pron_c1_6', 'C1', 'cloze', 'Cloze Test', 'Understanding',
      'The government introduced a policy, the implementation ______ proved exceptionally contentious.',
      ['whereof', 'of which', 'whose', 'to which'], 1,
      '"...the implementation of which proved..." is high-register genitive relative syntax.', 'Academic Register C1'),
    q('pron_c1_7', 'C1', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which archaic relative pronoun means "the thing which / that which"?',
      ['What', 'Wherewith', 'Whence', 'Whither'], 0,
      '"What" functions as a fused relative pronoun incorporating its antecedent: "What she said" = "The thing which she said".', 'Linguistic Syntax C1'),
    q('pron_c1_8', 'C1', 'matching', 'Matching', 'Understanding',
      'Match the structure: "It is no use crying over spilled milk." What role does "It" play?',
      ['Anticipatory "it" with gerund complement', 'Personal anaphoric pronoun', 'Deictic pronoun', 'Reflexive substitute'], 0,
      'Anticipatory "It" licenses a gerundial complement in fixed idiomatic constructions.', 'C1 Syntax Analysis'),
    q('pron_c1_9', 'C1', 'fill_blank', 'Fill in the Blank', 'Producing',
      'The committee consists of ten experts, none of ______ holds a political affiliation.',
      ['whom', 'who', 'which', 'whose'], 0,
      'Following preposition "of" with human referents, formal syntax demands objective "whom".', 'C1 Formal Register'),
    q('pron_c1_10', 'C1', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "One should always do what they believe to be right in their conscience."',
      ['Acceptable in informal speech, but inconsistent with "one\'s" in formal prose', 'Completely ungrammatical in all registers'], 0,
      'Traditional formal grammar insists on "One should do what one believes...".', 'Stylistic Concord C1'),

    // C2 (10 items)
    q('pron_c2_1', 'C2', 'multiple_choice', 'Multiple Choice', 'Understanding',
      'Select the sentence with strictly consistent formal impersonal pronoun concord:',
      ['If one aspires to academic excellence, one must dedicate oneself tirelessly to one\'s research.', 'If one aspires to academic excellence, they must dedicate themselves tirelessly to their research.', 'If one aspires to academic excellence, you must dedicate yourself tirelessly to your research.', 'If one aspires to academic excellence, he must dedicate himself tirelessly to his research.'], 0,
      'Strict formal consistency requires "one -> oneself -> one\'s" throughout.', 'C2 Stylistics'),
    q('pron_c2_2', 'C2', 'open_bracket', 'Open Bracket (Archaic Pronoun)', 'Producing',
      'Supply the archaic objective relative: "Give homage unto (he / him) ______ the king delighteth to honor."',
      ['him whom', 'he who', 'him who', 'he whom'], 0,
      'Classical biblical/literary English: "unto him whom the king...".', 'Historical English C2'),
    q('pron_c2_3', 'C2', 'checking_error', 'Checking Error', 'Explaining',
      'Spot the subtle defect: "The treaty, [A: the signatories] [B: whereof] [C: were] six sovereign nations, [D: was ratified]."',
      ['A: the signatories', 'B: whereof - archaic but grammatical', 'C: were', 'D: was ratified - Sentence is fully correct in high legal register!'], 3,
      '"Whereof" is an archaic pronominal adverb meaning "of which". The sentence is impeccable in formal legal prose.', 'C2 Legal Registers'),
    q('pron_c2_4', 'C2', 'sentence_unscramble', 'Sentence Unscramble', 'Producing',
      'Assemble this periodic sentence: [whoever / dispute / this / may / truth / the / evidence / speaks / for / itself]',
      ['Whoever may dispute this truth, the evidence speaks for itself.', 'The evidence speaks for itself whoever may dispute this truth.', 'Dispute this truth whoever may the evidence speaks for itself.', 'For itself speaks the evidence whoever may dispute this truth.'], 0,
      'Concessive nominal relative clause fronted for rhetorical weight.', 'C2 Rhetoric'),
    q('pron_c2_5', 'C2', 'cloze', 'Cloze Test', 'Understanding',
      'He was bereft of any financial support, ______ circumstance drove him into deep melancholy.',
      ['which', 'that', 'what', 'whose'], 0,
      'Sentential relative determiner: "which circumstance drove him..." (= and this circumstance).', 'C2 Classical Syntax'),
    q('pron_c2_6', 'C2', 'odd_one_out', 'Odd One Out', 'Memory',
      'Which item is a PRONOMINAL ADVERB equivalent to "about which"?',
      ['Whereabout', 'Thereabout', 'Hereabout', 'Whereby'], 0,
      '"Whereabout" (or "whereabouts") historically functioned as a pronominal adverb meaning "about which / concerning which".', 'C2 Morphology'),
    q('pron_c2_7', 'C2', 'fill_blank', 'Fill in the Blank', 'Producing',
      'They reached an amicable accord, by virtue ______ hostilities ceased immediately.',
      ['whereof', 'wherein', 'whereby', 'whereat'], 0,
      '"By virtue whereof" is the established classical legal connective meaning "by virtue of which".', 'Legal English C2'),
    q('pron_c2_8', 'C2', 'correct_incorrect', 'Correct or Incorrect', 'Explaining',
      'Evaluate: "It is me whom you must blame for the catastrophe."',
      ['Grammatically flawed in strict formal syntax - should be "It is I whom you must blame"', 'Impeccable in all formal academic contexts'], 0,
      'In strict classical prescriptive grammar, the predicate after the copula takes nominative case: "It is I whom...".', 'Prescriptive C2'),
    q('pron_c2_9', 'C2', 'checking_error', 'Checking Error', 'Explaining',
      'Identify the defect: "The diplomat [A: upon] [B: whose] advice the treaty [C: was signed] [D: have died]."',
      ['A: upon', 'B: whose', 'C: was signed', 'D: have died - subject is singular "The diplomat"!'], 3,
      'The subject "The diplomat" requires singular agreement: "has died", not "have died".', 'Subject-Verb Concord C2'),
    q('pron_c2_10', 'C2', 'open_bracket', 'Open Bracket', 'Producing',
      'Complete with the fused relative: "(What / That which) ______ was once considered impossible has now become everyday reality."',
      ['What', 'Which', 'That', 'Whom'], 0,
      'Fused relative "What" seamlessly embeds antecedent and relative pronoun.', 'C2 Fused Relatives')
  );

  return items;
}

module.exports = { getPronouns };
